'use strict';
// Explicit, isolated execution. Original law bodies are loaded unchanged; their
// repair controls are deliberately inaccessible through this adapter.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const crypto = require('node:crypto');
const { spawnSync } = require('node:child_process');
const {graphEncoderV2}=require('./trace-v2.cjs');
const NativeDate = Date;
const sha = x => crypto.createHash('sha256').update(x).digest('hex');
function fail(code) { throw Object.assign(new Error(code), {code}); }
function clock(day = '2026-09-03') {
  let current = day;
  return { today: () => current, hour: () => 12,
    nowMs: () => new NativeDate(...current.split('-').map((x,i) => +x-(i===1?1:0)),12).getTime(),
    nowISO() { return new NativeDate(this.nowMs()).toISOString(); },
    dow() { return new NativeDate(this.nowMs()).getDay(); }, tz:'America/New_York',
    set(next) { current=next; } };
}
function ids(c) {
  let sequence=0, randomSequence=0;
  return {fresh(prefix) { const r=((++randomSequence*104729)%1048576)/1048576;
    return (prefix||'')+c.nowMs().toString(36)+(sequence++).toString(36)+r.toString(36).slice(2,6); },count:()=>sequence};
}
// A snapshot carries tagged values and stable object identities across calls.
// Tags are arrays generated by the encoder, never user-object magic properties.
function graphEncoder() {
  const identities=new Map(); let next=0;
  const identity = value => { if(!identities.has(value))identities.set(value,++next);return identities.get(value); };
  return function snapshot(root) {
    const visited=new Set();
    function visit(v) {
      if(v===null)return ['null'];
      const type=typeof v;
      if(type==='undefined')return ['undefined'];
      if(type==='number')return ['number',Number.isNaN(v)?'NaN':v===Infinity?'+Infinity':v===-Infinity?'-Infinity':Object.is(v,-0)?'-0':String(v)];
      if(type==='string'||type==='boolean'||type==='bigint')return [type,String(v)];
      if(type==='symbol')return ['symbol',identity(v),v.description??null];
      if(type==='function')return ['function',identity(v)];
      const id=identity(v); if(visited.has(v))return ['ref',id]; visited.add(v);
      const tag=Object.prototype.toString.call(v);
      if(tag==='[object Date]')return ['Date',id,visit(v.getTime())];
      if(tag==='[object Map]')return ['Map',id,[...v].map(([k,x])=>[visit(k),visit(x)])];
      if(tag==='[object Set]')return ['Set',id,[...v].map(visit)];
      if(ArrayBuffer.isView(v))return [tag,id,Buffer.from(v.buffer,v.byteOffset,v.byteLength).toString('hex')];
      if(tag==='[object ArrayBuffer]')return [tag,id,Buffer.from(v).toString('hex')];
      if(!['[object Array]','[object Object]','[object Error]'].includes(tag))fail('UNSUPPORTED-TRACE-TYPE');
      if(tag==='[object Object]'&&Object.getPrototypeOf(v)!==null&&Object.getPrototypeOf(v)!==Object.prototype)fail('UNSUPPORTED-TRACE-PROTOTYPE');
      const props=Reflect.ownKeys(v).filter(k=>!(tag==='[object Error]'&&k==='stack')).map(k=>{
        const d=Object.getOwnPropertyDescriptor(v,k);if(!Object.hasOwn(d,'value'))fail('UNSUPPORTED-TRACE-ACCESSOR');
        return [visit(k),!!d.enumerable,!!d.writable,!!d.configurable,visit(d.value)];
      });
      return [tag,id,Object.getPrototypeOf(v)===null?'null-prototype':'standard',props];
    }
    return visit(root);
  };
}
function compile(file, requireFn) {
  const mod={exports:{}};
  const fn=new vm.Script('(function(exports,require,module,__filename,__dirname){\n'+fs.readFileSync(file,'utf8')+'\n})',{filename:file}).runInThisContext();
  fn(mod.exports,requireFn,mod,file,path.dirname(file));return mod.exports;
}
function loadCandidate(directory, inventory, loaded = []) {
  const root=fs.realpathSync(directory), cache=new Map();
  function load(file) {
    const real=fs.realpathSync(file), relative=path.relative(root,real).split(path.sep).join('/');
    if(!Object.hasOwn(inventory,relative)||relative.startsWith('../')||path.isAbsolute(relative))fail('CANDIDATE-IMPORT-OUTSIDE-INVENTORY');
    if(sha(fs.readFileSync(real))!==inventory[relative])fail('CANDIDATE-SOURCE-PIN');
    if(cache.has(real))return cache.get(real);
    loaded.push(relative);
    const exported=compile(real,request=>{
      if(!request.startsWith('./'))fail('CANDIDATE-IMPORT-OUTSIDE-INVENTORY');
      return load(path.resolve(path.dirname(real),request));
    });cache.set(real,exported);return exported;
  }
  const factory=load(path.join(root,'index.cjs'));
  if(typeof factory.createEngine!=='function')fail('CANDIDATE-FACTORY-MISSING');
  return factory.createEngine;
}
function fixtures(baseline) {
  // Load the pinned helper file with only inert boundary dependencies. Its exact
  // state/lift/clone functions are used, but no candidate or reference is loaded.
  const file=path.join(baseline,'rebuild/conform/v4/helpers.cjs');
  const unavailable=()=>fail('LEGACY-REPAIR-OR-REFERENCE-FORBIDDEN');
  const helpers=compile(file,request=>{
    if(request==='../../engine/index.cjs')return {createEngine:unavailable};
    if(request==='../../engine/test/writers-reference.cjs')return {createWriterReference:unavailable,deterministicRandom:unavailable,deterministicIds:unavailable};
    if(['node:path','node:crypto','node:child_process'].includes(request))return require(request);
    fail('LEGACY-HELPER-IMPORT');
  });
  return Object.freeze({state:helpers.state,lift:helpers.lift,clone:helpers.clone,patch:unavailable});
}
function rawLaw(baseline, descriptor) {
  const file=path.join(baseline,descriptor.file);
  if(sha(fs.readFileSync(file))!==descriptor.fileSha256)fail('LAW-SOURCE-PIN');
  const helper=fixtures(baseline);
  const mod=compile(file,request=>request==='./helpers.cjs'?helper:fail('LAW-IMPORT-FORBIDDEN'));
  if(JSON.stringify(mod.INVENTORY)!==JSON.stringify(mod.laws.map(l=>l.id)))fail('LAW-INVENTORY');
  const law=mod.laws.find(l=>l.defect===descriptor.defect&&l.id===descriptor.id);
  if(!law||sha(Function.prototype.toString.call(law.run))!==descriptor.runSha256)fail('RAW-LAW-PIN');
  return law;
}
function wrapFactory(factory,{day='2026-09-03',traceProfile=1,boundaryDateProfile=false},frames,loaded=[]) {
  if(![1,2].includes(traceProfile))fail('TRACE-PROFILE');
  const encode=traceProfile===2?graphEncoderV2({boundaryDateProfile}):graphEncoder();let instance=0;
  function engine(options={}) {
    if(!options||typeof options!=='object'||Array.isArray(options))fail('TARGET-OPTIONS');
    const c=options.clock||clock(day), idProvider=options.ids||ids(c), drafts=options.drafts||Object.freeze({length:0,key:()=>null});
    const table=factory({clock:c,ids:idProvider,drafts}).__test;
    if(!table||Object.hasOwn(table,'__auditOriginal'))fail('REPAIR-CONTROL-TARGET');
    const n=++instance, facade={...table};
    for(const [name,fn] of Object.entries(table))if(typeof fn==='function')facade[name]=(...args)=>{
      const before=encode(args);
      try {const result=Reflect.apply(fn,table,args);frames.push({instance:n,name,before,after:encode({args,result})});return result;}
      catch(e){frames.push({instance:n,name,before,after:encode({args,error:e})});throw e;}
    };
    return facade;
  }
  function record(name,value){if(typeof name!=='string'||!name)fail('OBSERVATION-NAME');frames.push({observation:name,value:encode(value)});}
  return {engine,record,legacy:Object.freeze({kind:'candidate',clock,engine(value=day){return engine({clock:typeof value==='string'?clock(value):value});}}),loaded};
}
function createTarget(input,frames=[]){const loaded=[];return wrapFactory(loadCandidate(input.candidate,input.inventory,loaded),input,frames,loaded);}
function pinnedHelper(input,file){
  if(!input.helperRoot||!input.helperPins)fail('HELPER-INVENTORY');
  const root=fs.realpathSync(input.helperRoot),cache=new Map();
  function load(file){const real=fs.realpathSync(file),rel=path.relative(root,real).split(path.sep).join('/');if(rel.startsWith('../')||path.isAbsolute(rel)||!Object.hasOwn(input.helperPins,rel)||sha(fs.readFileSync(real))!==input.helperPins[rel])fail('HELPER-SOURCE-PIN');if(cache.has(real))return cache.get(real);
    const req=request=>{if(['node:fs','node:path','node:vm','node:crypto','node:child_process','node:assert/strict','node:url','node:util'].includes(request))return require(request);
      if(['direct-frozen','raw-frozen'].includes(input.kind)&&input.bundle&&path.resolve(request)===path.resolve(input.bundle)){if(sha(fs.readFileSync(input.bundle))!==input.bundleSha256)fail('FROZEN-BUNDLE-PIN');delete require.cache[require.resolve(input.bundle)];return require(input.bundle);}
      if(input.kind==='raw-frozen'&&path.resolve(path.dirname(real),request)===path.join(root,'rebuild/engine/index.cjs'))return {createEngine(){fail('FROZEN-CANDIDATE-FACTORY-FORBIDDEN');}};
      if(!path.isAbsolute(request)&&!request.startsWith('./')&&!request.startsWith('../'))fail('HELPER-IMPORT');return load(path.resolve(path.dirname(real),request));};
    req.resolve=request=>{const resolved=path.resolve(path.dirname(real),request);if(['direct-frozen','raw-frozen'].includes(input.kind)&&resolved===path.resolve(input.bundle))return resolved;const rel=path.relative(root,resolved).split(path.sep).join('/');if(!Object.hasOwn(input.helperPins,rel))fail('HELPER-IMPORT');return resolved;};req.cache=Object.create(null);
    const out=compile(real,req);cache.set(real,out);return out;}
  return load(path.resolve(root,file));
}
async function worker(input) {
  process.env.TZ='America/New_York';
  if(!['frozen','native'].includes(input.mode))fail('DATE-MODE');
  if(input.mode==='frozen') { const c=clock(input.day); globalThis.Date=class FrozenDate extends NativeDate {constructor(...a){super(...(a.length?a:[c.nowMs()]));}static now(){return c.nowMs();}}; }
  const before=globalThis.Date,frames=[];let target;
  if(input.kind==='direct-frozen'){
    if(!input.bundle||sha(fs.readFileSync(input.bundle))!==input.bundleSha256)fail('FROZEN-BUNDLE-PIN');
    const helper=pinnedHelper(input,input.frozenHelper);
    target=wrapFactory(options=>{const table=helper.createFrozenEngine({...options,bundle:input.bundle,root:input.helperRoot});return table.__test?table:{__test:table};},{...input,boundaryDateProfile:true},frames);
  }else if(input.kind==='raw-frozen'){
    if(!input.bundle||sha(fs.readFileSync(input.bundle))!==input.bundleSha256)fail('FROZEN-BUNDLE-PIN');
    const helper=pinnedHelper(input,'rebuild/conform/v4/helpers.cjs'),B=helper.bundle('frozen',input.bundle);
    target=wrapFactory(options=>({__test:B.engine(options.clock)}),{...input,boundaryDateProfile:true},frames);
  }else target=createTarget(input,frames);
  let result,thrown=null;
  if(input.kind==='direct'||input.kind==='direct-frozen') {
    if(sha(fs.readFileSync(input.caseFile))!==input.caseSha256)fail('DIRECT-CASE-PIN');
    const successor=path.resolve(input.caseFile)===path.resolve(input.helperRoot||'.','rebuild/conform/v4/postfix/laws/step-efficacy.cjs');
    const mod=compile(input.caseFile,request=>{
      if(!successor||request!=='./import-guards.cjs')fail('DIRECT-CASE-IMPORT');
      return pinnedHelper(input,'rebuild/conform/v4/postfix/laws/import-guards.cjs');
    });
    const law=mod.laws.find(x=>x.id===input.lawId);
    if(!law||law.implementation!=='PRESENT'||typeof law.run!=='function')fail('DIRECT-CASE-PENDING');
    const api={engine:target.engine,record:target.record,caseId:input.caseId,day:input.day,clock:()=>clock(input.day)};
    if(input.hostsHelper){const helper=pinnedHelper(input,input.hostsHelper);api.createHosts=engine=>helper.createHosts({engine,record:target.record,clock:clock(input.day),root:input.helperRoot});}
    result=await law.run(Object.freeze(api));
  } else {
    const law=rawLaw(input.baseline,input.law); // Pin/import errors are outside the outcome catch.
    try{result=await law.run(target.legacy);}catch(error){
      const message=Object.getOwnPropertyDescriptor(error,'message');
      if(input.traceProfile!==2||input.rawFixtureOutcome!=='D44-NONDEFAULT-FIXTURE'||input.day!=='2026-09-07'||input.law.defect!=='D44'||Object.getPrototypeOf(error)!==TypeError.prototype||!message||!Object.hasOwn(message,'value')||message.value!=="Cannot read properties of null (reading 'agentProposals')")throw error;
      thrown={name:'TypeError',message:message.value};
    }
  }
  if(globalThis.Date!==before)fail('AMBIENT-DATE-MUTATED');
  if(thrown){if(!frames.length)fail('RAW-LAW-RESULT-OR-NO-CALL');return {status:'THROWS',error:thrown,frames,detail:graphEncoderV2()(undefined),assertions:null,loaded:target.loaded};}
  if(!result||typeof result.ok!=='boolean'||!frames.length)fail('RAW-LAW-RESULT-OR-NO-CALL');
  return {status:result.ok?'GREEN':'RED',frames,detail:graphEncoder()(result.detail),assertions:result.assertions??null,loaded:target.loaded};
}
function runRaw(input) {
  const child=spawnSync(process.execPath,[__filename,'--worker'],{input:JSON.stringify(input),encoding:'utf8',maxBuffer:32*1024*1024,timeout:30000,windowsHide:true,
    env:{...process.env,NODE_OPTIONS:'',NODE_V8_COVERAGE:input.coverageDirectory||'',TZ:'America/New_York',MEASURED_TEST_NOW:'2026-09-03',ENGINE_MAIN:'',ENGINE_OLD:''}});
  if(child.error||child.signal||child.status!==0)fail('RAW-CHILD-HARNESS-ERROR');
  try {const r=JSON.parse(child.stdout);if(!['RED','GREEN','THROWS'].includes(r.status)||!Array.isArray(r.frames)||!r.frames.length)fail('RAW-CHILD-PROTOCOL');if(r.status==='THROWS'&&(input.rawFixtureOutcome!=='D44-NONDEFAULT-FIXTURE'||input.law?.defect!=='D44'||input.day!=='2026-09-07'||r.error?.name!=='TypeError'||r.error?.message!=="Cannot read properties of null (reading 'agentProposals')"))fail('RAW-CHILD-PROTOCOL');return r;}
  catch(e){fail('RAW-CHILD-PROTOCOL');}
}
if(require.main===module) {
  if(process.argv.length!==3||process.argv[2]!=='--worker'){console.error('TARGET USAGE ERROR');process.exitCode=1;}
  else worker(JSON.parse(fs.readFileSync(0,'utf8'))).then(result=>process.stdout.write(JSON.stringify(result))).catch(e=>{console.error('TARGET HARNESS_ERROR '+(e.code||e.name));process.exitCode=1;});
}
module.exports={clock,ids,graphEncoder,graphEncoderV2,loadCandidate,rawLaw,createTarget,wrapFactory,runRaw,worker,sha,fail};
