'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function parseStat(raw){const open=raw.indexOf('('),close=raw.lastIndexOf(')');if(open<1||close<open)throw Error('PROC_STAT_INVALID');const pid=Number(raw.slice(0,open).trim()),parts=raw.slice(close+1).trim().split(/\s+/);if(!Number.isSafeInteger(pid)||pid<1||parts.length<20||!/^\d+$/.test(parts[1])||!/^\d+$/.test(parts[19]))throw Error('PROC_STAT_INVALID');const parent=Number(parts[1]);if(!Number.isSafeInteger(parent))throw Error('PROC_STAT_INVALID');return {pid,parent,created:parts[19]};}
function identity(pid,io=fs){if(!Number.isSafeInteger(pid)||pid<1)throw Error('OWNED_PID_INVALID');try{const a=parseStat(io.readFileSync('/proc/'+pid+'/stat','utf8')),exe=io.readlinkSync('/proc/'+pid+'/exe'),b=parseStat(io.readFileSync('/proc/'+pid+'/stat','utf8'));if(a.pid!==pid||a.pid!==b.pid||a.parent!==b.parent||a.created!==b.created||!path.posix.isAbsolute(exe)||exe.endsWith(' (deleted)'))throw Error('PROC_IDENTITY_CHANGED');return {...b,exe};}catch(e){if(e.code==='ENOENT'||e.code==='ESRCH')return null;throw e;}}
function killVerified(record,{readIdentity=identity,kill=process.kill.bind(process)}={}){if(!record?.pid||!record.created||!record.exe)throw Error('OWNERSHIP_NOT_PROVEN');const actual=readIdentity(record.pid);if(!actual)return;if(actual.pid!==record.pid||actual.parent!==record.parent||actual.created!==record.created||actual.exe!==record.exe)throw Error('OWNERSHIP_CHANGED');try{kill(record.pid,'SIGKILL');}catch(e){if(e.code!=='ESRCH')throw e;}}
function captureOwnership(child,{readIdentity=identity,parent=process.pid,expectedExe,args=[],records,save,onFailure}){try{const r=readIdentity(child.pid);if(!r||r.parent!==parent||r.exe!==expectedExe)throw Error('OWNERSHIP_SETUP_FAILED');r.role='workerd';r.argumentsSha256=sha(JSON.stringify(args));records.push(r);save(records);return r;}catch(e){if(child.exitCode===null&&child.signalCode===null)try{child.kill('SIGKILL');}catch{}onFailure('OWNERSHIP_SETUP_FAILED');throw e;}}
function trackChildren({pins,save,onFailure}){const original=cp.spawn,records=[],children=[];let spawned=false;
  cp.spawn=function(file,args=[],options={}){if(spawned||fs.realpathSync(file)!==pins.workerdExecutable||sha(fs.readFileSync(file))!==pins.workerdSha256)throw Error('WORKER_CHILD_PIN_OR_REPEAT');spawned=true;const child=original.call(cp,file,args,{...options,windowsHide:true});children.push(child);child.on('error',()=>onFailure('OWNED_CHILD_FAILURE'));captureOwnership(child,{expectedExe:pins.workerdExecutable,args,records,save,onFailure});return child;};
  return {records,verify(pid){const actual=identity(pid),known=records.find(r=>r.pid===pid);const direct=fs.readFileSync('/proc/'+process.pid+'/task/'+process.pid+'/children','utf8').trim().split(/\s+/).filter(Boolean).map(Number);if(records.length!==1||!known||!actual||actual.parent!==process.pid||actual.exe!==pins.workerdExecutable||actual.created!==known.created||!direct.includes(pid))throw Error('OWNERSHIP_MISMATCH');return actual;},terminate(){for(const child of children)if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');},restore(){cp.spawn=original;}};
}
module.exports={parseStat,identity,killVerified,captureOwnership,trackChildren,sha};
