'use strict';
// Remote preparation only: verify the existing source/dependencies; static build
// into this transport's generated directory. Never install or launch workerd.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{createRequire}=require('node:module');const {sha}=require('./owned.cjs');const {inventory,inside}=require('./paths.cjs');const {compile}=require('./loader.cjs');const {verifyTransport,hashFile,scopedEnvironment}=require('./pins.cjs');const root=__dirname;
function replace(s,a,b){if(s.split(a).length!==2)throw Error('INSTRUMENT_ANCHOR_MISMATCH');return s.replace(a,b);}
async function scopedCwd(directory,action){const previous=process.cwd();try{process.chdir(directory);return await action();}finally{process.chdir(previous);}}
function packageFor(entry,name){let dir=path.dirname(entry);for(let n=0;n<10;n++,dir=path.dirname(dir)){const file=path.join(dir,'package.json');if(fs.existsSync(file)){const p=JSON.parse(fs.readFileSync(file));if(p.name===name)return {file,version:p.version};}}throw Error('PACKAGE_IDENTITY_MISSING');}
async function prepare({sourceRoot,dependencyRoot}){
  if(process.platform!=='linux'||process.arch!=='x64')throw Error('LINUX_X64_PREPARATION_REQUIRED');if(process.execArgv.length)throw Error('INHERITED_NODE_FLAGS');verifyTransport();const original=require('./SOURCE-PINS.json');
  if(fs.realpathSync(process.execPath)!==original.nodeExecutable||hashFile(process.execPath)!==original.nodeSha256||process.version!==original.nodeVersion)throw Error('NODE_PIN');const envReceipt=scopedEnvironment().receipt;
  sourceRoot=fs.realpathSync(sourceRoot);dependencyRoot=fs.realpathSync(dependencyRoot);const w5=sourceRoot+'/rebuild/m3/w5';if(fs.realpathSync(w5+'/node_modules')!==dependencyRoot)throw Error('DEPENDENCY_ROOT_MISMATCH');
  const expected={};for(const [f,h]of Object.entries(original.files)){if(!f.startsWith('rebuild/')||/(?:private|ledger|golden|\.\.)/.test(f))throw Error('PUBLIC_SOURCE_ONLY');const full=sourceRoot+'/'+f;if(!inside(sourceRoot,fs.realpathSync(full))||hashFile(full)!==h)throw Error('PUBLIC_SOURCE_PIN');expected[full]=h;}
  const dependencies=inventory(dependencyRoot),req=createRequire(w5+'/package.json'),wranglerEntry=req.resolve('wrangler'),wranglerReq=createRequire(wranglerEntry),mfEntry=wranglerReq.resolve('miniflare'),mfReq=createRequire(mfEntry),workerdEntry=mfReq.resolve('workerd'),workerdReq=createRequire(workerdEntry),esbuildEntry=req.resolve('esbuild');
  const packages={wrangler:packageFor(wranglerEntry,'wrangler'),miniflare:packageFor(mfEntry,'miniflare'),workerd:packageFor(workerdEntry,'workerd'),esbuild:packageFor(esbuildEntry,'esbuild')};
  for(const [name,version]of Object.entries({wrangler:'4.129.0',miniflare:'5.20260903.0-alpha',workerd:'1.20260903.1',esbuild:'0.28.1'}))if(packages[name].version!==version)throw Error('PACKAGE_VERSION_PIN');
  const workerdExecutable=fs.realpathSync(workerdReq(workerdEntry).default);if(!inside(dependencyRoot,workerdExecutable)||hashFile(workerdExecutable)!==original.workerdSha256||fs.readFileSync(workerdExecutable).subarray(0,4).toString('hex')!=='7f454c46')throw Error('NATIVE_WORKERD_PIN');
  let wsModule;try{wsModule=req.resolve('ws');}catch{wsModule=mfReq.resolve('ws');}wsModule=fs.realpathSync(wsModule);if(!inside(dependencyRoot,wsModule))throw Error('WS_OUTSIDE_DEPENDENCIES');
  const generated=root+'/generated';fs.mkdirSync(generated,{recursive:true});if(fs.existsSync(root+'/PLANNED-MANIFEST.json'))throw Error('ALREADY_PREPARED_NO_OVERWRITE');
  const core=generated+'/core.cjs';await scopedCwd(sourceRoot,()=>req(w5+'/build.cjs').buildCore({outfile:core}));const sourceCore=w5+'/.generated/core.cjs';if(!fs.existsSync(sourceCore)||hashFile(sourceCore)!==hashFile(core))throw Error('EXISTING_GENERATED_CORE_MISMATCH');expected[sourceCore]=hashFile(sourceCore);
  const runtimeOriginal=fs.readFileSync(w5+'/test/r1-workerd.cjs','utf8').replace(/\r\n/g,'\n'),split=runtimeOriginal.indexOf('  const authorityKey=generateSigningKey');if(split<0)throw Error('RUNTIME_SPLIT');
  let buildOnly=runtimeOriginal.slice(0,split)+'  return bundle.outputFiles[0].text;\n}\nmodule.exports={prepareBundle:createR1Runtime};\n';buildOnly=replace(buildOnly,'  await buildCore(authorityRoot === undefined ? {} : { authorityRoot });','  // Existing generated core was independently rebuilt and matched before this static bundle.');
  const bundlePath=generated+'/application-bundle.mjs';fs.writeFileSync(bundlePath,await scopedCwd(sourceRoot,()=>compile(buildOnly,w5+'/test/prepare-retaining-bundle.cjs').prepareBundle()));
  const instrumentedRuntime=generated+'/runtime.cjs',instrumentedWitness=generated+'/witness.cjs';fs.copyFileSync(root+'/templates/runtime.cjs',instrumentedRuntime);
  let witness=fs.readFileSync(root+'/templates/witness.cjs','utf8');witness=replace(witness,"const {createR1Runtime}=require('../r1-workerd.retaining.cjs');","const {createR1Runtime}=global.__retainingCapture.instrumentedRuntime;");const meterLine=witness.split(/\r?\n/).find(line=>line.startsWith('const {createResourceMeter}=require('));if(!meterLine)throw Error('METER_IMPORT_ANCHOR');witness=replace(witness,meterLine,'const {createResourceMeter}=require('+JSON.stringify(root+'/meter.cjs')+');');fs.writeFileSync(instrumentedWitness,witness);
  for(const [f,h]of Object.entries(verifyTransport().files))expected[root+'/'+f]=h;for(const f of [core,bundlePath,instrumentedRuntime,instrumentedWitness,process.execPath])expected[f]=hashFile(f);
  // Static esbuild must not mutate installed bytes or source inputs.
  require('./paths.cjs').verifyInventory(dependencies);for(const [f,h]of Object.entries(expected))if(hashFile(f)!==h)throw Error('PREPARATION_INPUT_DRIFT');
  const manifest={resourceAcceptance:false,prepared:true,platform:'linux',sourcePin:original.sourcePin,sourceRoot,dependencyRoot:w5,dependencies,expected,nodeExecutable:original.nodeExecutable,nodeSha256:original.nodeSha256,workerdExecutable,workerdSha256:original.workerdSha256,packages,wsModule,bundlePath,bundleSha256:hashFile(bundlePath),instrumentedRuntime,instrumentedWitness,originalTemp:path.resolve(os.tmpdir()),environmentReceipt:envReceipt,compatibilityDate:'2026-09-03',compatibilityFlags:['nodejs_compat'],target:'workerd: worker core:user:earned-r1-metered-application',limits:{runtimeMs:300000,cleanupMs:10000,pauseMs:5000,captureMs:30000,snapshotBytes:268435456},expectedNaturalCompletion:{attempts:4,measuredRequests:159},originalInstalledBuildInference:false};
  fs.writeFileSync(root+'/PLANNED-MANIFEST.json',JSON.stringify(manifest,null,2)+'\n',{flag:'wx'});require('./pins.cjs').verify();console.log('LINUX PREPARED: public inputs, installed bytes, native executable and generated bundle pinned; no runtime launched.');
}
if(require.main===module){const args=process.argv.slice(2);if(args.length!==4||args[0]!=='--source-root'||args[2]!=='--dependency-root')throw Error('EXPLICIT_SOURCE_AND_DEPENDENCY_ROOTS_REQUIRED');prepare({sourceRoot:args[1],dependencyRoot:args[3]}).catch(e=>{console.error(/^[A-Z0-9_]+$/.test(e.message)?e.message:'LINUX_PREPARATION_FAILED');process.exitCode=2;});}
module.exports={replace,packageFor,prepare,scopedCwd};
