'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{EventEmitter}=require('node:events');const {parseStat,identity,killVerified,captureOwnership,sha}=require('./owned.cjs');const {inventory,verifyInventory}=require('./paths.cjs');const {scopedEnvironment}=require('./pins.cjs');const {supervise}=require('./supervisor.cjs');
const tests=[],test=(name,fn)=>tests.push([name,fn]);
function stat(pid=23,parent=7,start='98765432101234567890',comm='workerd (test) )'){const fields=Array(24).fill('0');fields[0]='S';fields[1]=String(parent);fields[19]=start;return pid+' ('+comm+') '+fields.join(' ');}
test('proc stat parses embedded spaces/parentheses and exact field22 without numeric precision loss',()=>{assert.deepEqual(parseStat(stat()),{pid:23,parent:7,created:'98765432101234567890'});assert.throws(()=>parseStat('23 bad'),/INVALID/);assert.throws(()=>parseStat(stat().replace('98765432101234567890','bad')),/INVALID/);});
test('proc identity reads executable and stable parent/starttime across two reads',()=>{const io={readFileSync:()=>stat(),readlinkSync:()=>'/deps/workerd'};assert.deepEqual(identity(23,io),{pid:23,parent:7,created:'98765432101234567890',exe:'/deps/workerd'});let count=0;assert.throws(()=>identity(23,{...io,readFileSync:()=>stat(23,7,String(++count))}),/CHANGED/);assert.throws(()=>identity(23,{...io,readlinkSync:()=>'/deps/workerd (deleted)'}),/CHANGED/);assert.equal(identity(23,{readFileSync:()=>{throw Object.assign(Error(),{code:'ENOENT'});}}),null);});
test('Linux termination refuses PID reuse, changed parent/executable and uses one positive identity',()=>{const record={pid:23,parent:7,created:'99',exe:'/deps/workerd'},kills=[];killVerified(record,{readIdentity:()=>record,kill:(...v)=>kills.push(v)});assert.deepEqual(kills,[[23,'SIGKILL']]);for(const patch of [{created:'100'},{parent:8},{exe:'/other/workerd'}])assert.throws(()=>killVerified(record,{readIdentity:()=>({...record,...patch}),kill:()=>assert.fail('unowned kill')}),/OWNERSHIP_CHANGED/);killVerified(record,{readIdentity:()=>null,kill:()=>assert.fail('absent kill')});});
class Child extends EventEmitter{constructor(){super();this.pid=23;this.exitCode=null;this.signalCode=null;this.sent=[];this.signals=[];}send(m,cb){this.sent.push(m);cb?.();}kill(signal){this.signals.push(signal);this.signalCode=signal;this.emit('exit');}}
test('Linux direct handle cleanup survives proc ownership and receipt write failures',()=>{for(const failure of ['proc','write']){const child=new Child();assert.throws(()=>captureOwnership(child,{parent:7,expectedExe:'/deps/workerd',records:[],readIdentity:()=>{if(failure==='proc')throw Error('synthetic');return {pid:23,parent:7,created:'9',exe:'/deps/workerd'};},save:()=>{throw Error('synthetic');},onFailure:()=>{}}));assert.deepEqual(child.signals,['SIGKILL']);}});
function vfs(){const nodes={'/deps':{dir:['.pnpm','pkg']},'/deps/.pnpm':{dir:['pkg@1']},'/deps/.pnpm/pkg@1':{dir:['node_modules']},'/deps/.pnpm/pkg@1/node_modules':{dir:['pkg']},'/deps/.pnpm/pkg@1/node_modules/pkg':{dir:['index.js','workerd']},'/deps/.pnpm/pkg@1/node_modules/pkg/index.js':{file:'public-js'},'/deps/.pnpm/pkg@1/node_modules/pkg/workerd':{file:'public-binary'},'/deps/pkg':{link:'/deps/.pnpm/pkg@1/node_modules/pkg'}};
  const get=p=>{if(!nodes[p])throw Object.assign(Error('synthetic missing'),{code:'ENOENT'});return nodes[p];};const resolve=(p,seen=new Set())=>{if(seen.has(p))throw Error('synthetic ELOOP');seen.add(p);const n=get(p);return n.link?resolve(n.link,seen):p;};const type=n=>({isDirectory:()=>!!n.dir,isFile:()=>n.file!==undefined,isSymbolicLink:()=>!!n.link});return {nodes,io:{realpathSync:resolve,lstatSync:p=>type(get(p)),statSync:p=>type(get(resolve(p))),readdirSync:p=>get(resolve(p)).dir,readFileSync:p=>Buffer.from(get(resolve(p)).file)}};}
test('pnpm internal links resolve and pin native/JS bytes without copying directories',()=>{const {io}=vfs(),p=inventory('/deps',{io,p:path.posix});assert.equal(Object.keys(p.files).length,2);assert.equal(p.links['/deps/pkg'],'/deps/.pnpm/pkg@1/node_modules/pkg');verifyInventory(p,{io,p:path.posix});});
test('dependency links outside selected root, unresolved targets and ancestor cycles fail closed',()=>{for(const kind of ['outside','missing','cycle']){const {io,nodes}=vfs();if(kind==='outside'){nodes['/deps/pkg'].link='/outside';nodes['/outside']={dir:[]};}if(kind==='missing')nodes['/deps/pkg'].link='/missing';if(kind==='cycle'){nodes['/deps/.pnpm/pkg@1/node_modules/pkg'].dir.push('self');nodes['/deps/.pnpm/pkg@1/node_modules/pkg/self']={link:'/deps/.pnpm/pkg@1/node_modules/pkg'};}assert.throws(()=>inventory('/deps',{io,p:path.posix}));}});
test('installed native byte change invalidates prelaunch dependency pins',()=>{const {io,nodes}=vfs(),p=inventory('/deps',{io,p:path.posix});nodes['/deps/.pnpm/pkg@1/node_modules/pkg/workerd'].file='changed';assert.throws(()=>verifyInventory(p,{io,p:path.posix}),/PIN_MISMATCH/);});
test('environment preserves parent and unrelated fields; rejects hooks and memory override drift',()=>{const clean={OTHER:'synthetic'};assert.deepEqual(scopedEnvironment(clean).env,clean);assert.deepEqual(clean,{OTHER:'synthetic'});for(const value of ['--require=a','--max-old-space-size=123 --require=a','--max-old-space-size=1'])assert.throws(()=>scopedEnvironment({NODE_OPTIONS:value}),/NOT_APPROVED/);for(const key of ['WORKERD_BINARY_PATH','MINIFLARE_WORKERD_PATH','WORKERD_BINARY','NODE_V8_COVERAGE'])assert.throws(()=>scopedEnvironment({[key]:'/other'}),/OVERRIDE/);});
for(const stage of ['identity','write'])test('Linux supervisor '+stage+' failure kills owned child before start handshake',async()=>{const child=new Child();let result;await supervise({spawn:()=>child,parentPid:7,identity:()=>{if(stage==='identity')throw Error('PROC_FAILED');return {pid:23,parent:7};},killVerified:()=>assert.fail('No descendant recorded'),writeActual:()=>{throw Error('WRITE_FAILED');},writeResult:r=>result=r,runtimeMs:30,cleanupMs:5});assert.deepEqual(child.signals,['SIGKILL']);assert(!child.sent.some(m=>m.kind==='start'));assert.equal(result.resourceAcceptance,false);});
test('Linux supervisor timeout preserves bounded handshake then SIGKILL fallback',async()=>{const child=new Child();let result;await supervise({spawn:()=>child,parentPid:7,identity:()=>({pid:23,parent:7}),killVerified:()=>{},writeActual:()=>{},writeResult:r=>result=r,runtimeMs:5,cleanupMs:5});assert(child.sent.some(m=>m.kind==='start'));assert(child.sent.some(m=>m.kind==='deadline'));assert.deepEqual(child.signals,['SIGKILL']);assert.equal(result.timedOut,true);});
test('instrument loader resolves unchanged relative imports at explicit original location',()=>{const dir=__dirname+'/synthetic-output';fs.mkdirSync(dir,{recursive:true});const owned=fs.mkdtempSync(dir+'/loader-');fs.writeFileSync(owned+'/value.cjs','module.exports=42;');const result=require('./loader.cjs').compile('module.exports={value:require("./value.cjs"),dir:__dirname};',owned+'/virtual.cjs');assert.equal(result.value,42);assert.equal(path.resolve(result.dir),path.resolve(owned));});
test('static build cwd is explicitly scoped and restored on failure',async()=>{const {scopedCwd}=require('./prepare.cjs'),before=process.cwd();await assert.rejects(scopedCwd(__dirname,async()=>{assert.equal(process.cwd(),__dirname);throw Error('synthetic');}),/synthetic/);assert.equal(process.cwd(),before);});
test('portable capture core and original templates retain reviewed exact bytes',()=>{const pins=require('./WINDOWS-REUSE-PINS.json');for(const f of pins.unchanged)assert.equal(sha(fs.readFileSync(__dirname+'/'+f)),pins.originalFiles[f]);});
async function main(){const results=[];for(const [name,fn]of tests)try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}const report={syntheticOnly:true,hostPlatform:process.platform,linuxRuntimeExecuted:false,productWorkloadExecuted:false,resourceAcceptance:false,passed:results.filter(r=>r.pass).length,total:results.length,results};fs.writeFileSync(__dirname+'/SYNTHETIC-RESULTS.json',JSON.stringify(report,null,2)+'\n');console.log('LINUX ADAPTER SYNTHETIC '+report.passed+'/'+report.total+' PASS; Linux/runtime runs=0');for(const r of results.filter(r=>!r.pass))console.log(r.name+': '+r.error);process.exitCode=report.passed===report.total?0:1;}
if(require.main===module)main();
