/* APPENDIX D13 / D14 LAWS v2 — CANDIDATE-BOUND. Every law runs against a POLICY bundle: the reference model
   (reference/policy.cjs) must be GREEN on all of them; the product binding (adapters/policy.cjs, tranche T4) is
   RED(as specified) until it exists and must then reproduce every result; each law carries targeted mutants.
   Sol suite-pass-1: "cover every ruled D13 branch, not only synthetic athlete A" — currency, endpoints, source
   kinds, linked weight, legacy third-party estimate, re-attestation, units, abstention, nonzero training energy,
   boundary-adjacent values, the full action_constraint contract. Cites: sheet v1.7.38 appendix v1.37 lines. */
const { NotImplemented, JP, canon } = require("../lib/harness.cjs");
const mk = (B, cfg) => { if (!B || !B.policy) throw new NotImplemented("adapters/policy.cjs — the D13/D14 binding in the new engine (tranche T4)"); return B.policy(cfg); };
const hm = (name, hooks) => ({ name, make: (ref) => ({ ...ref, policy: (cfg) => ref.policy(cfg, hooks) }) });
const lb = (v) => ({ value: v, unit: "lb" }), kg = (v) => ({ value: v, unit: "kg" });
const A = () => ({ age: 31, sex: "M", d11: "HEALTHY", rt_plan: { effective: true, suspended: false }, rt_months: 48, phase: "deficit", weigh_in: { weight: lb(160.0), effective_date: "2026-09-01" }, missing_dates: 0 });
const E1 = (o) => ({ op_id: "E1", seq: 10, kind: "estimate", quantity: "body_fat_fraction", bf_low: 0.12, bf_high: 0.16, bf_point: 0.14, provenance: "your estimate", effective_date: "2026-09-01", linked_weight: lb(160.0), linked_weight_op_id: "W1", ...(o || {}) });
const D = (o) => ({ op_id: "D1", seq: 5, kind: "measurement", quantity: "lean_mass", low: kg(60.0), high: kg(62.0), provenance: "DEXA", effective_date: "2026-08-20", ...(o || {}) });
const P1 = (B, cfg) => mk(B, cfg).protein();
const laws = [
  { id: "D13-P1-synthetic-A-147-about-144-range-140-147-on-lean-HIGH", cite: "appendix D13 P1 + Sol's witness recomputed (v1.7.38 lines 2236–2243)", expect: "GREEN",
    run: (B) => { const r = P1(B, { athlete: A(), sources: [E1()], evaluation_date: "2026-09-04" }); return { ok: r.branch === "P1" && r.operative_g === 147 && r.display_point_g === 144 && canon(r.evidence_range_g) === "[140,147]" && Math.abs(r.raw_minimum_g - 146.8913531008) < 1e-6 && r.anchor_label === "point", detail: JP(r).slice(0, 300) }; },
    mutants: [hm("2.3-on-the-central-anchor", { floorOnLeanHigh: false, c1: 2.3 * (62.414310112 / 63.865805696) }), hm("lean-equals-fat-mass", { leanFrom: "bf" })] },
  { id: "D13-P2-synthetic-A-117-from-a-point-weigh-in-no-interval", cite: "appendix D13 P2 (1.6 g/kg body mass; raw 116.11964672 → 117; POINT_SOURCE_NO_INTERVAL)", expect: "GREEN",
    run: (B) => { const r = P1(B, { athlete: { ...A(), phase: "maintenance" }, sources: [] }); return { ok: r.branch === "P2" && r.operative_g === 117 && Math.abs(r.raw_minimum_g - 116.11964672) < 1e-6 && r.evidence_range_g === null && r.evidence_range_reason === "POINT_SOURCE_NO_INTERVAL", detail: JP(r).slice(0, 300) }; },
    mutants: [hm("1.6-on-lean-instead-of-body-mass", { c2: 1.6 * 0.86 })] },
  { id: "D13-gate-order-first-failure-names-the-branch-D11-then-RT-plan-then-phase", cite: "appendix D13 GATE ORDER (v1.7.38 lines 2159–2163) + P3", expect: "GREEN",
    run: (B) => { const minor = P1(B, { athlete: { ...A(), age: 17 }, sources: [E1()] }); const noRT = P1(B, { athlete: { ...A(), rt_plan: { effective: false } }, sources: [E1()] }); const susp = P1(B, { athlete: { ...A(), rt_plan: { effective: true, suspended: true } }, sources: [E1()] }); const noPhase = P1(B, { athlete: { ...A(), phase: "conflicted" }, sources: [E1()] });
      return { ok: minor.abstain === "INELIGIBLE_D11" && noRT.abstain === "NO_EFFECTIVE_RT_PLAN" && susp.abstain === "NO_EFFECTIVE_RT_PLAN" && noPhase.abstain === "PHASE_UNRESOLVED" && [minor, noRT, susp, noPhase].every((r) => r.branch === "P3" && r.operative_g === undefined), detail: JP([minor.abstain, noRT.abstain, susp.abstain, noPhase.abstain]) }; },
    mutants: [hm("unresolved-phase-defaults-to-deficit", { requirePhase: false }), hm("no-RT-plan-still-computes", { requireRT: false })] },
  { id: "D13-currency-measurement-180-days-estimate-90-days-future-effective-and-stale-abstain-with-copy", cite: "appendix D13 P1 LEAN-SOURCE CURRENCY (v1.7.38 lines 2170–2177)", expect: "GREEN",
    run: (B) => { const at = (src, date) => P1(B, { athlete: A(), sources: [src], evaluation_date: date }); const e89 = at(E1({ effective_date: "2026-06-07" }), "2026-09-04"), e90 = at(E1({ effective_date: "2026-06-06" }), "2026-09-04"); const m179 = at(D({ effective_date: "2026-03-09" }), "2026-09-04"), m180 = at(D({ effective_date: "2026-03-08" }), "2026-09-04"); const fut = at(E1({ effective_date: "2026-09-05" }), "2026-09-04");
      return { ok: e89.branch === "P1" && e89.operative_g === 147 && e90.abstain === "LEAN_SOURCE_STALE" && /Refresh your body-composition source/.test(e90.copy) && m179.operative_g !== undefined && m180.abstain === "LEAN_SOURCE_STALE" && fut.abstain === "LEAN_SOURCE_FUTURE_EFFECTIVE", detail: JP({ e89: e89.operative_g, e90: e90.abstain, m179: m179.operative_g, m180: m180.abstain, fut: fut.abstain }) }; },
    mutants: [hm("estimate-gets-the-180-day-window", { currency: { measurement: 180, estimate: 180 } }), { name: "future-source-current", make: (ref) => ({ ...ref, policy: (cfg) => ref.policy({ ...cfg, sources: (cfg.sources || []).map((s) => ({ ...s, effective_date: s.effective_date > (cfg.evaluation_date || "2026-09-04") ? cfg.evaluation_date || "2026-09-04" : s.effective_date })) }) }) }] },
  { id: "D13-governing-source-measurement-over-estimate-most-recent-among-a-kind-lean-mass-in-kg-direct", cite: "appendix D13 GOVERNING SOURCE (v1.7.38 lines 2181–2184)", expect: "GREEN",
    run: (B) => { const r = P1(B, { athlete: A(), sources: [E1({ effective_date: "2026-09-01" }), D({ effective_date: "2026-08-20" })], evaluation_date: "2026-09-04" }); const r2 = P1(B, { athlete: A(), sources: [E1({ op_id: "E1", effective_date: "2026-08-01" }), E1({ op_id: "E2", seq: 12, effective_date: "2026-09-01", bf_low: 0.14, bf_high: 0.18, bf_point: 0.16 })], evaluation_date: "2026-09-04" });
      return { ok: r.source === "D1" && r.operative_g === Math.ceil(2.3 * 62.0) && r2.source === "E2" && r2.operative_g === Math.ceil(2.3 * 160 * 0.45359237 * 0.86), detail: JP({ r: [r.source, r.operative_g], r2: [r2.source, r2.operative_g] }) }; },
    mutants: [hm("estimate-can-outrank-a-measurement-by-date", { measurementOverEstimate: false })] },
  { id: "D13-tied-equivalent-sources-canonicalize-to-the-lowest-seq-representative-materially-different-ties-abstain-count-neutral", cite: "appendix D13 equivalence classes + BODY_COMPOSITION_SOURCE_CONFLICT copy (v1.7.38 lines 2184–2200; rig156 Q1: three classes)", expect: "GREEN",
    run: (B) => { const same = P1(B, { athlete: A(), sources: [E1({ op_id: "E9", seq: 30 }), E1({ op_id: "E2", seq: 11 })], evaluation_date: "2026-09-04" }); const diff = P1(B, { athlete: A(), sources: [E1({ op_id: "E1" }), E1({ op_id: "E2", seq: 11, bf_point: 0.15 }), E1({ op_id: "E3", seq: 12, provenance: "coach" })], evaluation_date: "2026-09-04" });
      return { ok: same.source === "E2" && canon(same.membership) === canon(["E2", "E9"]) && same.operative_g === 147 && diff.abstain === "BODY_COMPOSITION_SOURCE_CONFLICT" && diff.N === 3 && /disagree \(3 versions\)/.test(diff.copy), detail: JP({ same: [same.source, same.membership], diff: [diff.abstain, diff.N] }) }; },
    mutants: [hm("tie-broken-by-latest-op-instead-of-conflict", { tieToConflict: false })] },
  { id: "D13-unpaired-estimate-abstains-linked-weight-or-attested-mass-pairs-it-units-convert-at-full-precision", cite: "appendix D13 (an estimate paired with a weigh-in per state 10 A) + D14 gate 2 LEAN_SOURCE_UNPAIRED + A3 units", expect: "GREEN",
    run: (B) => { const un = P1(B, { athlete: A(), sources: [E1({ linked_weight: undefined, linked_weight_op_id: undefined })] }); const kgw = P1(B, { athlete: A(), sources: [E1({ linked_weight: kg(72.5748) })] }); const att = P1(B, { athlete: A(), sources: [E1({ linked_weight: undefined, linked_weight_op_id: undefined, attested_total_mass: lb(160.0) })] });
      return { ok: un.abstain === "LEAN_SOURCE_UNPAIRED" && kgw.operative_g === 147 && Math.abs(kgw.raw_minimum_g - 146.8913531008) < 1e-3 && att.operative_g === 147, detail: JP({ un: un.abstain, kg: kgw.raw_minimum_g, att: att.operative_g }) }; },
    mutants: [{ name: "unpaired-estimate-uses-any-recent-weight", make: (ref) => ({ ...ref, policy: (cfg) => ref.policy({ ...cfg, sources: (cfg.sources || []).map((s) => s.linked_weight || s.attested_total_mass || s.quantity === "lean_mass" ? s : { ...s, linked_weight: lb(160.0) }) }) }) }] },
  { id: "D13-re-attestation-is-a-NEW-estimate-op-with-its-own-date-an-old-measurement-is-never-redated", cite: "appendix D13 RE-ATTESTATION (v1.7.38 lines 2173–2176)", expect: "GREEN",
    run: (B) => { const stale = P1(B, { athlete: A(), sources: [D({ effective_date: "2026-01-01" })], evaluation_date: "2026-09-04" }); const re = P1(B, { athlete: A(), sources: [D({ effective_date: "2026-01-01" }), E1({ op_id: "E7", seq: 40, effective_date: "2026-09-02" })], evaluation_date: "2026-09-04" });
      return { ok: stale.abstain === "LEAN_SOURCE_STALE" && re.branch === "P1" && re.source === "E7" && re.operative_g === 147, detail: JP({ stale: stale.abstain, re: [re.source, re.operative_g] }) }; },
    mutants: [{ name: "re-attestation-redates-the-old-measurement", make: (ref) => ({ ...ref, policy: (cfg) => { const srcs = cfg.sources || []; const newest = srcs.reduce((m, s) => (s.effective_date > m ? s.effective_date : m), "0000"); return ref.policy({ ...cfg, sources: srcs.map((s) => s.kind === "measurement" ? { ...s, effective_date: newest } : s) }); } }) }] },
  { id: "D13-missing-central-estimate-anchors-the-point-at-the-midpoint-labelled-midpoint", cite: "appendix D13 TYPED FORMULAS lean_anchor_kg (v1.7.38 line 2224–2225)", expect: "GREEN",
    run: (B) => { const r = P1(B, { athlete: A(), sources: [E1({ bf_point: undefined })] }); return { ok: r.anchor_label === "midpoint" && r.display_point_g === Math.round(2.3 * (60.962814528 + 63.865805696) / 2) && r.operative_g === 147, detail: JP([r.anchor_label, r.display_point_g]) }; },
    mutants: [{ name: "missing-central-uses-the-high-endpoint-as-the-point", make: (ref) => ({ ...ref, policy: (cfg) => ref.policy({ ...cfg, sources: (cfg.sources || []).map((s) => s.bf_point == null && s.bf_low != null ? { ...s, bf_point: s.bf_low } : s) }) }) }] },
  { id: "D13-evidence-scope-MATCHED_BY_DECLARATION-vs-EXTRAPOLATED-never-IN_POPULATION", cite: "appendix D13 EVIDENCE SCOPE (v1.7.38 lines 2258–2264)", expect: "GREEN",
    run: (B) => { const m = P1(B, { athlete: A(), sources: [E1()] }); const nov = P1(B, { athlete: { ...A(), rt_months: 3 }, sources: [E1()] }); const fat = P1(B, { athlete: A(), sources: [E1({ bf_low: 0.20, bf_high: 0.26, bf_point: 0.23 })] }); const unk = P1(B, { athlete: { ...A(), d11: "UNESTABLISHED" }, sources: [E1()] });
      return { ok: m.evidence_scope === "MATCHED_BY_DECLARATION" && nov.evidence_scope === "EXTRAPOLATED" && fat.evidence_scope === "EXTRAPOLATED" && unk.evidence_scope === "EXTRAPOLATED" && ![m, nov, fat, unk].some((r) => r.evidence_scope === "IN_POPULATION"), detail: JP([m.evidence_scope, nov.evidence_scope, fat.evidence_scope, unk.evidence_scope]) }; },
    mutants: [{ name: "novice-labelled-matched", make: (ref) => ({ ...ref, policy: (cfg) => ref.policy({ ...cfg, athlete: { ...cfg.athlete, rt_months: 48 } }) }) }] },
  { id: "D13-P2-currency-follows-D7-7-missing-dates-abstain-a-future-weigh-in-abstains-with-date-copy", cite: "appendix D13 P2 CURRENCY (v1.7.38 lines 2205–2210)", expect: "GREEN",
    run: (B) => { const ok6 = P1(B, { athlete: { ...A(), phase: "maintenance", missing_dates: 6 } }); const no7 = P1(B, { athlete: { ...A(), phase: "maintenance", missing_dates: 7 } }); const fut = P1(B, { athlete: { ...A(), phase: "surplus", weigh_in: { weight: lb(160), effective_date: "2026-09-09" } }, evaluation_date: "2026-09-04" });
      return { ok: ok6.operative_g === 117 && no7.abstain === "WEIGH_IN_STALE" && /weigh in to refresh your protein minimum/.test(no7.copy) && fut.abstain === "WEIGH_IN_FUTURE_EFFECTIVE" && /dated in the future/.test(fut.copy), detail: JP([ok6.operative_g, no7.abstain, fut.abstain]) }; },
    mutants: [hm("P2-current-until-14-missing-dates", { p2D7: 14 })] },
  { id: "D13-no-intermediate-rounding-a-boundary-adjacent-lean-mass-changes-the-operative-minimum-under-tenth-gram-rounding", cite: "appendix D13 QUANTIZATION — NO intermediate rounding anywhere (v1.7.38 lines 2229–2236); witness 152.3 lb at 10 % → raw 142.99998 (147.0 → 143 vs 144)", expect: "GREEN",
    run: (B) => { const r = P1(B, { athlete: A(), sources: [E1({ bf_low: 0.10, bf_high: 0.14, bf_point: 0.12, linked_weight: lb(152.3) })] }); return { ok: r.operative_g === 143 && Math.abs(r.raw_minimum_g - 142.99998415857) < 1e-6, detail: JP([r.raw_minimum_g, r.operative_g]) }; },
    mutants: [hm("lean-rounded-to-a-gram-before-multiplying", { intermediateRounding: true })] },
  { id: "D13-action_constraint-carries-the-full-contract-kind-value-unit-policy-grain-uncertainty-rule", cite: "appendix D13 UNCERTAINTY RULE (v1.7.38 lines 2253–2257)", expect: "GREEN",
    run: (B) => { const r = P1(B, { athlete: A(), sources: [E1()] }); const c = r.action_constraint; return { ok: c && c.kind === "MINIMUM" && c.value === 147 && c.unit === "g/day" && c.policy === "earned.protein.public v1" && canon(c.constraint_grain) === canon({ value: 1, unit: "g/day", origin: 0 }) && /high lean endpoint/.test(c.uncertainty_rule), detail: JP(c) }; },
    mutants: [hm("bare-value-constraint", { fullContract: false })] },
  /* ---- D14 ---- */
  { id: "D14-rest-day-synthetic-A-1916-about-1872-range-1828-1916-exclusive-boundary-on-lean-HIGH", cite: "appendix D14 (k = 30 on lean_HIGH + training energy; EA ≤ 30 forbidden) — standing results rigs 154–157", expect: "GREEN",
    run: (B) => { const f = mk(B, { athlete: A(), sources: [E1()], today: { occurrences: [], zeroProof: "NO_EXERCISE_ATTESTATION" } }).floor(); const T = f.TODAY; return { ok: T.status === "FIGURE_OK" && T.headline === "ZERO_ATTESTED" && T.operative === 1916 && T.point === 1872 && canon(T.range) === "[1828,1916]" && T.operative > T.point, detail: JP(T) }; },
    mutants: [hm("floor-on-the-central-anchor", { floorOnLeanHigh: false }), hm("inclusive-boundary", { exclusiveBoundary: false, k: 30 * (1800 / 1915.974170) })] },
  { id: "D14-exclusive-boundary-raw-1800-is-operative-1801-and-a-50-kcal-plan-grid-gives-1850", cite: "appendix D14 BOUNDARY + QUANTIZATION (first representable PASSING endpoint)", expect: "GREEN",
    run: (B) => { const f = mk(B, { athlete: A(), sources: [D({ low: kg(58.0), high: kg(60.0) })], today: { occurrences: [], zeroProof: "NO_EXERCISE_ATTESTATION" }, plan: { grid: 50 } }).floor(); return { ok: Math.abs(f.TODAY.raw - 1800) < 1e-9 && f.TODAY.operative === 1801 && f.grid(1801) === 1850, detail: JP([f.TODAY.raw, f.TODAY.operative, f.grid(1801)]) }; },
    mutants: [hm("inclusive-boundary-1800-passes", { exclusiveBoundary: false })] },
  { id: "D14-nonzero-training-energy-adds-to-the-floor-on-a-training-day-and-a-class-bound-on-the-plan", cite: "appendix D14 k × lean_HIGH + training energy; §D14-F class bounds", expect: "GREEN",
    run: (B) => { const f = mk(B, { athlete: A(), sources: [E1()], today: { occurrences: [{ kind: "SESSION" }], producers: [{ id: "src-1", eee_kcal: 300 }] }, plan: { classes: [{ id: "lower", bound_kcal: 350 }, { id: "upper", bound_kcal: 250 }] } }).floor(); return { ok: f.TODAY.headline === "ONE_BOUND" && f.TODAY.operative === 1916 + 300 && f.PLAN_HORIZON.operative === 1916 + 350 && canon(f.PLAN_HORIZON.co_maximal) === canon(["lower"]), detail: JP({ T: f.TODAY.operative, P: f.PLAN_HORIZON.operative, co: f.PLAN_HORIZON.co_maximal }) }; },
    mutants: [{ name: "training-energy-dropped", make: (ref) => ({ ...ref, policy: (cfg) => ref.policy({ ...cfg, today: cfg.today && cfg.today.producers ? { ...cfg.today, producers: cfg.today.producers.map((p) => ({ ...p, eee_kcal: 0 })) } : cfg.today, plan: cfg.plan && cfg.plan.classes ? { ...cfg.plan, classes: cfg.plan.classes.map((c) => ({ ...c, bound_kcal: 0 })) } : cfg.plan }) }) }] },
  { id: "D14-apply-requires-3T-AND-3P-a-failed-scope-blocks-application-lists-every-failed-locus-and-never-the-other-scope's-display", cite: "appendix APPLICATION RULE (v1.7.38 lines 3623–3630) + producer precondition 2604–2611 + D14_POLICY_CHECK_RESULT precedence", expect: "GREEN",
    run: (B) => { const f = mk(B, { athlete: A(), sources: [E1()], today: { occurrences: [], zeroProof: "NO_EXERCISE_ATTESTATION" }, plan: { classes: [{ id: "lower", bound_kcal: null }, { id: "upper", bound_kcal: 250 }] }, proposal: { band: [2100, 2200] } }).floor(); const ok = mk(B, { athlete: A(), sources: [E1()], today: { occurrences: [], zeroProof: "NO_EXERCISE_ATTESTATION" }, plan: { classes: [{ id: "lower", bound_kcal: 350 }] }, proposal: { band: [2300, 2400] } }).floor(); const low = mk(B, { athlete: A(), sources: [E1()], today: { occurrences: [], zeroProof: "NO_EXERCISE_ATTESTATION" }, plan: { classes: [{ id: "lower", bound_kcal: 350 }] }, proposal: { band: [2100, 2200] } }).floor();
      return { ok: f.application === "BLOCKED" && f.D14_POLICY_CHECK_RESULT.headline === "BLOCKED_BY" && f.D14_POLICY_CHECK_RESULT.results[0].locus === "PLAN_HORIZON" && f.TODAY.displayed === true && f.TODAY.operative === 1916 && canon(f.PLAN_HORIZON.failures) === canon(["CLASS_BOUND_MISSING:lower"]) && ok.application === "ALLOWED" && ok.D14_POLICY_CHECK_RESULT.required_minimum === 2266 && canon(ok.D14_POLICY_CHECK_RESULT.governing_scopes) === canon(["PLAN_HORIZON"]) && low.application === "BLOCKED" && low.D14_POLICY_CHECK_RESULT.headline === "INTAKE_BELOW_FLOOR" && low.D14_POLICY_CHECK_RESULT.band_low === 2100, detail: JP({ blocked: f.D14_POLICY_CHECK_RESULT, ok: ok.D14_POLICY_CHECK_RESULT, low: low.D14_POLICY_CHECK_RESULT.headline }) }; },
    mutants: [hm("3T-alone-applies", { applyNeeds3T3P: false })] },
  { id: "D14-ZERO_ATTESTED-needs-no-positive-producer-and-displays-a-logged-training-day-without-a-producer-abstains-MISSING_EEE_ESTIMATE", cite: "appendix PRODUCER PRECONDITION (v1.7.38 lines 2604–2611)", expect: "GREEN",
    run: (B) => { const rest = mk(B, { athlete: A(), sources: [E1()], today: { occurrences: [], zeroProof: "NO_EXERCISE_ATTESTATION" } }).floor().TODAY; const train = mk(B, { athlete: A(), sources: [E1()], today: { occurrences: [{ kind: "SESSION" }], producers: [] } }).floor().TODAY; return { ok: rest.headline === "ZERO_ATTESTED" && rest.displayed === true && rest.operative === 1916 && rest.selected_eee === 0 && train.status === "MISSING_EEE_ESTIMATE" && train.displayed === false && train.operative === undefined, detail: JP({ rest, train }) }; },
    mutants: [hm("zero-proof-also-needs-a-producer", { zeroNeedsNoProducer: false })] },
  { id: "D14-shared-gate-failures-INELIGIBLE_D11-LEAN_SOURCE_NONE-STALE-FUTURE-UNPAIRED-CONFLICT-name-the-shared-locus", cite: "appendix D14 GATE ORDER (v1.7.38 lines 2279–2287)", expect: "GREEN",
    run: (B) => { const cases = [["INELIGIBLE_D11", { athlete: { ...A(), d11: "FAIL" }, sources: [E1()] }], ["LEAN_SOURCE_NONE", { athlete: A(), sources: [] }], ["LEAN_SOURCE_STALE", { athlete: A(), sources: [E1({ effective_date: "2026-01-01" })] }], ["LEAN_SOURCE_FUTURE_EFFECTIVE", { athlete: A(), sources: [E1({ effective_date: "2026-12-01" })] }], ["LEAN_SOURCE_UNPAIRED", { athlete: A(), sources: [E1({ linked_weight: undefined, linked_weight_op_id: undefined })] }], ["BODY_COMPOSITION_SOURCE_CONFLICT", { athlete: A(), sources: [E1(), E1({ op_id: "E2", seq: 11, bf_point: 0.15 })] }]]; const rs = cases.map(([code, cfg]) => [code, mk(B, cfg).floor().shared]); return { ok: rs.every(([c, s]) => c === s), detail: JP(rs) }; },
    mutants: [hm("stale-source-still-governs", { currency: { measurement: 100000, estimate: 100000 } })] },
  { id: "D14-failure-loci-TODAY-only-BOTH-sorted-and-reciprocal-governing-scopes-Today-governs-or-plan-governs", cite: "appendix D14_POLICY_CHECK_RESULT precedence (v1.7.38 lines 2310–2322): EVERY failed locus is listed, sorted by [locus, …]; governing_scopes = every scope whose operative minimum equals the maximum", expect: "GREEN",
    run: (B) => { const E = (o) => ({ op_id: "E1", seq: 10, kind: "estimate", quantity: "body_fat_fraction", bf_low: 0.12, bf_high: 0.16, bf_point: 0.14, provenance: "your estimate", effective_date: "2026-09-01", linked_weight: lb(160.0), linked_weight_op_id: "W1", ...(o || {}) });
      const todayOnly = mk(B, { athlete: A(), sources: [E()], today: { occurrences: [{ kind: "SESSION" }], producers: [] }, plan: { classes: [{ id: "lower", bound_kcal: 350 }] }, proposal: { band: [2400, 2500] } }).floor();
      const both = mk(B, { athlete: A(), sources: [E()], today: { occurrences: [{ kind: "SESSION" }], producers: [] }, plan: { classes: [{ id: "lower", bound_kcal: null }] }, proposal: { band: [2400, 2500] } }).floor();
      const todayGoverns = mk(B, { athlete: A(), sources: [E()], today: { occurrences: [{ kind: "SESSION" }], producers: [{ id: "s", eee_kcal: 600 }] }, plan: { classes: [{ id: "lower", bound_kcal: 350 }] }, proposal: { band: [2600, 2700] } }).floor();
      const planGoverns = mk(B, { athlete: A(), sources: [E()], today: { occurrences: [], zeroProof: "NO_EXERCISE_ATTESTATION" }, plan: { classes: [{ id: "lower", bound_kcal: 350 }] }, proposal: { band: [2300, 2400] } }).floor();
      const tie = mk(B, { athlete: A(), sources: [E()], today: { occurrences: [{ kind: "SESSION" }], producers: [{ id: "s", eee_kcal: 350 }] }, plan: { classes: [{ id: "lower", bound_kcal: 350 }] }, proposal: { band: [2300, 2400] } }).floor();
      const r = (x) => x.D14_POLICY_CHECK_RESULT; return { ok: r(todayOnly).headline === "BLOCKED_BY" && canon(r(todayOnly).results.map((x) => x.locus)) === canon(["TODAY"]) && todayOnly.PLAN_HORIZON.displayed === true && r(both).headline === "BLOCKED_BY" && canon(r(both).results.map((x) => x.locus)) === canon(["PLAN_HORIZON", "TODAY"]) && r(todayGoverns).headline === "PASSES" && canon(r(todayGoverns).governing_scopes) === canon(["TODAY"]) && r(todayGoverns).required_minimum === 2516 && r(planGoverns).headline === "PASSES" && canon(r(planGoverns).governing_scopes) === canon(["PLAN_HORIZON"]) && canon(r(tie).governing_scopes) === canon(["PLAN_HORIZON", "TODAY"]), detail: JP({ todayOnly: r(todayOnly), both: r(both), tg: r(todayGoverns), pg: r(planGoverns), tie: r(tie) }) }; },
    mutants: [hm("only-the-first-failed-locus-is-listed", { firstLocusOnly: true }), hm("3T-alone-applies", { applyNeeds3T3P: false })] },
];
const INVENTORY = laws.map((l) => l.id);
module.exports = { laws, INVENTORY };
