/* PROGRESSION LAWS (REBUILD) — PACK 3 findings carried into the rebuild as RED laws (Sol suite-pass-1), plus the
   two one-sided witnesses the OLD engine fails (rig185 executes them against fix4b; run.cjs reports that as an
   ENGINE-TRACK finding, not a suite inconsistency). Bundle: { progression(cfg, hooks) }. */
const { NotImplemented, JP, canon } = require("../lib/harness.cjs");
const mk = (B, cfg) => { if (!B || !B.progression) throw new NotImplemented("adapters/progression.cjs — the rebuild's progression-receipt binding (tranche T5)"); return B.progression(cfg || {}); };
const hm = (name, hooks) => ({ name, make: (ref) => ({ ...ref, progression: (cfg) => ref.progression(cfg, hooks) }) });
const LIFT = () => ({ id: "press", name: "PRESS", load: 250, inc: 5, renames: [{ prevN: "CHEST PRESS", at: "2026-08-20" }] });
const laws = [
  { id: "P1-same-day-set-count-maximum-is-end-of-day-plus-same-day-DECREASES-one-sided-plus-1-never-5-one-sided-minus-1-is-4", cite: "PACK 3 M3 (FIX-4 §3 'setsAtTime = same-day maximum') — Sol suite-pass-1 executed counterexamples: +1 current 4 → 5 (required 4); −1 current 3 → 3 (required 4)", expect: "GREEN",
    run: (B) => { const p = mk(B); const d = "2026-09-01"; const plus = p.setsAtTime(4, [[d, 1]], d), minus = p.setsAtTime(3, [[d, -1]], d), balanced = p.setsAtTime(4, [[d, 1], [d, -1]], d), multi = p.setsAtTime(4, [[d, 1], [d, -1], [d, -1]], d), later = p.setsAtTime(4, [["2026-09-05", 1]], d), laterDec = p.setsAtTime(3, [["2026-09-05", -1]], d);
      return { ok: plus === 4 && minus === 4 && balanced === 5 && multi === 6 && later === 3 && laterDec === 4, detail: JP({ plus, minus, balanced, multi, later, laterDec }) }; },
    mutants: [hm("fix4b-formula-end-of-day-plus-increases", { sameDayRule: "end-of-day-plus-increases" })] },
  { id: "P1-former-name-joint-mint-device-A-under-the-former-name-device-B-under-the-current-name-merged-history-earns-the-same-single-earn-and-debut-as-serial", cite: "PACK 3 M7 / FIX-4b — Sol suite-pass-1: _mintJointEarn recognizes provisional signatures through the current name only (rig185 executes it on fix4b: 0 EARNED under the former name, 1 under the current)", expect: "GREEN",
    run: (B) => { const p = mk(B); const lift = LIFT(); const serial = [{ d: "2026-08-18", t: "PRESS 250 × 10·10·10 — TOP OF WINDOW, PROVISIONAL" }, { d: "2026-08-25", t: "PRESS 250 × 10·10·10 — TOP OF WINDOW, PROVISIONAL" }]; const merged = [{ d: "2026-08-18", t: "CHEST PRESS 250 × 10·10·10 — TOP OF WINDOW, PROVISIONAL" }, { d: "2026-08-25", t: "PRESS 250 × 10·10·10 — TOP OF WINDOW, PROVISIONAL" }];
      const a = p.mintJointEarn(lift, serial), b = p.mintJointEarn(lift, merged); return { ok: !!a && !!b && a.id === b.id && a.debut === b.debut && a.d === "2026-08-25", detail: JP({ serial: a, merged: b }) }; },
    mutants: [hm("current-name-only-scan", { nameScan: "current" })] },
  { id: "P2-earn-receipt-identity-is-earn-lift-load-date-never-the-display-text-a-re-earn-of-the-same-load-on-another-date-is-distinct", cite: "PACK 3 §7 PARKED offline duplicate-EARN (rebuild rule: earn fact identity earn:<ex>:<load>:<date>)", expect: "GREEN",
    run: (B) => { const p = mk(B); const lift = LIFT(); const e1 = p.mintJointEarn(lift, [{ d: "2026-08-18", t: "PRESS 250 × 10·10·10 — TOP OF WINDOW, PROVISIONAL" }, { d: "2026-08-25", t: "PRESS 250 × 10·10·10 — TOP OF WINDOW, PROVISIONAL" }]); const e2 = p.mintJointEarn(lift, [{ d: "2026-09-10", t: "PRESS 250 × 10·10·10 — TOP OF WINDOW, PROVISIONAL" }, { d: "2026-09-17", t: "PRESS 250 × 10·10·10 — TOP OF WINDOW, PROVISIONAL" }]);
      return { ok: e1.id === "earn:press:250:2026-08-25" && e2.id === "earn:press:250:2026-09-17" && e1.t === e2.t && e1.id !== e2.id, detail: JP([e1.id, e2.id]) }; },
    mutants: [hm("identity-is-the-sentence", { earnIdentity: "sentence" })] },
  { id: "P3-existing-queue-records-are-never-rewritten-same-graduation-canonicalizes-to-one-id", cite: "PACK 3 M2 / M6 (existing queue items never rewritten; one ACTIVE debut per (lift, load))", expect: "GREEN",
    run: (B) => { const p = mk(B); let q = []; q = p.queueAppend(q, { id: "debut:press:255:2026-08-25", kind: "debut", exId: "press", newW: 255, d: "2026-08-25", done: false, state: "ESTABLISH" }); const before = canon(q); q = p.queueAppend(q, { id: "debut:press:255:2026-08-25", kind: "debut", exId: "press", newW: 255, d: "2026-08-25", done: false, state: "REWRITTEN", gate: "x" }); return { ok: canon(q) === before && q.length === 1, detail: JP(q) }; },
    mutants: [hm("append-rewrites-the-existing-record", { rewriteQueue: true })] },
  { id: "P4-reconcileDebutQueue-selects-the-EARLIEST-graduation-losers-remain-as-done-SUPERSEDED-DONE-history-byte-preserved", cite: "PACK 3 M6 (one ACTIVE debut per (lift, load), earliest, DONE untouched, SUPERSEDED not deleted)", expect: "GREEN",
    run: (B) => { const p = mk(B); const done = { id: "debut:press:250:2026-08-01", kind: "debut", exId: "press", newW: 250, d: "2026-08-01", done: true, state: "DONE", gate: "Debuted 8,8" }; const q = [done, { id: "debut:press:255:2026-08-30", kind: "debut", exId: "press", newW: 255, d: "2026-08-30", done: false }, { id: "debut:press:255:2026-08-25", kind: "debut", exId: "press", newW: 255, d: "2026-08-25", done: false }]; const r = p.reconcileDebuts(q);
      const active = r.filter((x) => x.kind === "debut" && x.newW === 255 && !x.done); const loser = r.find((x) => x.id === "debut:press:255:2026-08-30"); return { ok: active.length === 1 && active[0].id === "debut:press:255:2026-08-25" && loser && loser.done === true && loser.state === "SUPERSEDED" && loser.supersededBy === "debut:press:255:2026-08-25" && canon(r.find((x) => x.id === done.id)) === canon(done) && r.length === 3, detail: JP(r) }; },
    mutants: [hm("latest-wins", { reconcile: "latest" }), hm("loser-deleted", { loserState: "DELETE" })] },
  { id: "P5-server-authoritative-merge-makes-peer-queue-order-canonical-both-merge-orders-agree", cite: "PACK 3 §6 queue-order divergence in _unionKeyed (REBUILD item; the pack's 'settles next sync' claim was false — its own output read 'order agrees: false')", expect: "GREEN",
    run: (B) => { const p = mk(B); const a = [{ id: "q1", d: "2026-08-01" }, { id: "q3", d: "2026-08-03" }], b = [{ id: "q2", d: "2026-08-02" }, { id: "q3", d: "2026-08-03" }]; const ab = p.mergeQueues(a, b), ba = p.mergeQueues(b, a); return { ok: canon(ab) === canon(ba) && ab.length === 3, detail: JP({ ab: ab.map((x) => x.id), ba: ba.map((x) => x.id) }) }; },
    mutants: [hm("arrival-order-kept", { orderCanonical: false })] },
  { id: "P6-every-debut-writer-classic-two-rung-one-sighting-carries-the-per-set-vector-newWSets", cite: "PACK 3 FIX-4 §4 (Sol hunt 2, P1): the PROPOSED debut writers carry newWSets too — two-rung [65,65,60] and one-sighting [60,60,55] from wSets [55,55,50] at load 55", expect: "GREEN",
    run: (B) => { const p = mk(B); const lift = { id: "press", name: "PRESS", load: 55, inc: 5, wSets: [55, 55, 50] }; const c = p.writers.classic(lift, "2026-08-20"), t = p.writers.twoRung(lift, "2026-08-20"), o = p.writers.oneSighting(lift, "2026-08-20"); return { ok: canon(c.newWSets) === "[60,60,55]" && c.newW === 60 && canon(t.newWSets) === "[65,65,60]" && t.newW === 65 && t.state === "PROPOSED" && canon(o.newWSets) === "[60,60,55]" && o.state === "PROPOSED" && /ONE SIGHTING/.test(o.t), detail: JP([c, t, o]) }; },
    mutants: [hm("proposed-writers-carry-no-vector", { writersCarryVector: false })] },
  { id: "P7-taking-a-higher-proposed-debut-supersedes-every-LOWER-standing-graduation-for-that-lift", cite: "PACK 3 FIX-4 §4 takeProposedDebut: a lower standing graduation goes (done, SUPERSEDED); running the 60 after taking the 65 would prescribe below the load already bought", expect: "GREEN",
    run: (B) => { const p = mk(B); const lift = { id: "press", name: "PRESS", load: 55, inc: 5, wSets: [55, 55, 50] }; const q = [p.writers.classic(lift, "2026-08-20"), p.writers.twoRung(lift, "2026-08-20"), { id: "debut:curl:65:2026-08-20", kind: "debut", exId: "curl", newW: 65, done: false, state: "ESTABLISH" }]; const taken = p.takeProposedDebut(q, q[1].id); const active = taken.filter((x) => x.exId === "press" && x.kind === "debut" && !x.done); const sup = taken.find((x) => x.newW === 60 && x.exId === "press");
      return { ok: active.length === 1 && active[0].newW === 65 && active[0].state === "DEBUT" && /DEBUT \(two-rung, your call\)/.test(active[0].t) && sup.done === true && sup.state === "SUPERSEDED" && taken.find((x) => x.exId === "curl").done === false, detail: JP(taken) }; },
    mutants: [hm("taking-leaves-the-lower-debut-standing", { takeSupersedesLower: false })] },
  { id: "P8-completing-the-selected-debut-adopts-the-per-set-vector-the-lift-lives-at-the-new-load-with-its-line", cite: "PACK 3 FIX-4 §4: completing the taken debut adopts the vector — the lift lives at 65 with 65·65·60, not a load behind", expect: "GREEN",
    run: (B) => { const p = mk(B); const lift = { id: "press", name: "PRESS", load: 55, inc: 5, wSets: [55, 55, 50] }; const q = p.takeProposedDebut([p.writers.classic(lift, "2026-08-20"), p.writers.twoRung(lift, "2026-08-20")], `debut:press:65:2026-08-20:2r`); const done = p.completeDebut(lift, q, `debut:press:65:2026-08-20:2r`); return { ok: done.lift.load === 65 && canon(done.lift.wSets) === "[65,65,60]" && done.queue.find((x) => x.newW === 65).state === "DONE", detail: JP(done) }; },
    mutants: [hm("completion-keeps-the-old-vector", { completionAdoptsVector: false })] },
];
const INVENTORY = laws.map((l) => l.id);
module.exports = { laws, INVENTORY };
