'use strict';
// Import-free synthetic direct-engine claims; expected repair results are the
// accepted brief, never candidate-generated repair controls.
const A='2030-02-03',B='2030-02-04',ID='synthetic-a',OTHER='synthetic-b',CASES=[];
function copy(v,seen=new Map()){if(v===null||typeof v!=='object')return v;if(seen.has(v))return seen.get(v);const o=Array.isArray(v)?[]:Object.create(Object.getPrototypeOf(v));seen.set(v,o);for(const k of Reflect.ownKeys(v)){const d=Object.getOwnPropertyDescriptor(v,k);if('value'in d)d.value=copy(d.value,seen);Object.defineProperty(o,k,d);}return o;}
function shape(v,seen=new Map()){if(v===null||typeof v!=='object')return typeof v==='undefined'?['undefined']:typeof v==='function'?['function',String(v)]:[typeof v,v];if(seen.has(v))return['ref',seen.get(v)];seen.set(v,seen.size);return[Array.isArray(v)?'array':'object',Reflect.ownKeys(v).map(k=>{const d=Object.getOwnPropertyDescriptor(v,k);return[String(k),d.enumerable,d.configurable,'value'in d?['data',d.writable,shape(d.value,seen)]:['accessor',String(d.get),String(d.set)]];})];}
const exact=(a,b)=>JSON.stringify(shape(a))===JSON.stringify(shape(b));
const entry=(id=ID)=>({id,w:100,reps:[10,9,8],rirSets:[2,1,0]});
function state(){return{v:60,trend:170,reads:[{d:A,w:170}],sleep:{nights:[],needed:3},dailyLogs:{},sessionLog:{[A]:{entries:[entry()]}},exercises:[],queue:[],feed:[],adjustments:[],suggestionLog:[],learned:{tdee:[],anchors:[]},waist:[],photos:[],targets:{},model:{lean:140,drip:0,anchorISO:'2026-01-01'},plan:{}};}
const reason=(kind,...tuple)=>kind+' '+JSON.stringify(tuple.length===1&&kind!=='entryidentity'&&kind!=='skippedidentity'?tuple[0]:tuple);
const slot=i=>reason('setidentity',A,ID,i),lostEntry=reason('entryidentity',A,ID),lostSkipped=reason('skippedidentity',A,ID),lostSession=reason('sessionidentity',A);
function add(defect,id,claims,fn,frozenRed=false){CASES.push(Object.freeze({defect,id,claims:Object.freeze(claims),frozenRed,execute:fn}));}
function guardCase(id,mutate,lost=[],frozenRed=false){add('D33',id,['guard','inputs','no-effects'],c=>{const p=state(),altered=mutate(p,c),n=altered===undefined?copy(p):altered,before=shape([p,n]);c.reset();const g=c.T.dataLossGuard(p,n);c.check('guard',exact(g,{safe:lost.length===0,lost}));c.check('inputs',exact(shape([p,n]),before));c.check('no-effects',c.effects()===0);},frozenRed);}
guardCase('IG33-READ-REPLACE',p=>{const n=copy(p);n.reads[0].d=B;return n;},[reason('readidentity',A)],true);
guardCase('IG33-SET-SHRINK',p=>{const n=copy(p);n.sessionLog[A].entries[0].reps.pop();return n;},[slot(2)],true);
guardCase('IG33-ENTRY-LOST',p=>{const n=copy(p);n.sessionLog[A].entries=[];return n;},[lostEntry],true);
guardCase('IG33-UNCHANGED',p=>copy(p));
guardCase('IG33-ADD',p=>{const n=copy(p);n.reads.push({d:B,w:171});n.sessionLog[A].entries.push(entry(OTHER));n.sessionLog[A].entries[0].reps.push(7);return n;});
guardCase('IG33-FOLD',p=>{p.reads.push({d:A,w:171,note:'duplicate day'});const n=copy(p);n.reads.pop();return n;});
guardCase('IG33-COMPENSATION-LIFT',p=>{const n=copy(p);n.sessionLog[A].entries[0].reps.pop();n.sessionLog[A].entries.push(entry(OTHER));return n;},[slot(2)],true);
guardCase('IG33-COMPENSATION-DAY',p=>{const n=copy(p);n.sessionLog[A].entries=[];n.sessionLog[B]={entries:[entry()]};return n;},[lostEntry],true);
for(const value of ['HOLE','NULL','UNDEFINED','ZERO','STRING']){
  guardCase('IG33-OCCUPIED-'+value,p=>{p.sessionLog[A].entries[0].reps=[10,9];if(value==='HOLE')p.sessionLog[A].entries[0].reps.length=3;else p.sessionLog[A].entries[0].reps.push({NULL:null,UNDEFINED:undefined,ZERO:0,STRING:'0'}[value]);const n=copy(p);n.sessionLog[A].entries[0].reps.length=2;return n;},['ZERO','STRING'].includes(value)?[slot(2)]:[],['ZERO','STRING'].includes(value));
  if(['HOLE','NULL','UNDEFINED'].includes(value))guardCase('IG33-PADDING-'+value,p=>{const n=copy(p),r=n.sessionLog[A].entries[0].reps;if(value==='HOLE')delete r[2];else r[2]=value==='NULL'?null:undefined;return n;},[slot(2)],true);
}
guardCase('IG33-EMPTY-ENTRY',p=>{p.sessionLog[A].entries[0].reps=[];const n=copy(p);n.sessionLog[A].entries=[];return n;},[lostEntry],true);
guardCase('IG33-SAME-SLOTS-VALUES',p=>{const n=copy(p);n.sessionLog[A].entries[0].reps=[1,2,3];return n;});
for(const variant of ['REMOVE','MOVE','BARE-RESTORE','MALFORMED-UNSKIP','UNRELATED-SKIP'])guardCase('IG33-SKIPPED-'+variant,(p,c)=>{p.sessionLog[A].entries=[entry(OTHER)];p.sessionLog[A].skipped=[{id:ID}];const n=copy(p);delete n.sessionLog[A].skipped;if(variant==='MOVE')n.sessionLog[B]={entries:[],skipped:[{id:ID}]};if(variant==='BARE-RESTORE')n.sessionLog[A].entries.push(entry());if(variant==='MALFORMED-UNSKIP'){c.T._fileCorr(n.sessionLog[A],'unskip-malformed','unskip',ID,'2030-02-03T12:00:00Z',{reps:[10,9]});c.T._replayCorrections(n.sessionLog[A]);}if(variant==='UNRELATED-SKIP')c.T._fileCorr(n.sessionLog[A],'skip-other','skip',OTHER,'2030-02-03T12:00:00Z');return n;},[lostSkipped],true);
function file(c,n,kind='strike',to=[{id:ID,reps:[10,9],rirSets:[2,1]}],id=ID,op='synthetic-correction',at='2030-02-03T12:00:00Z'){c.T._fileCorr(n.sessionLog[A],op,kind,id,at,to);return op;}
function strike(p,c){const n=copy(p),op=file(c,n);n.feed.push({d:A,op,t:'SYNTHETIC strike receipt',how:'exact bytes retained'});c.T._replayCorrections(n.sessionLog[A]);return n;}
guardCase('IG33-STRIKE-POSITIVE',(p,c)=>strike(p,c));
guardCase('IG33-STRIKE-MULTILIFT-NO-TOP-ID',(p,c)=>{p.sessionLog[A].entries.push(entry(OTHER));const n=copy(p);file(c,n,'strike',[{id:ID,reps:[10,9],rirSets:[2,1]},{id:OTHER,reps:[10]}],null);n.feed.push({d:A,op:'synthetic-correction',t:'SYNTHETIC multi-lift strike'});c.T._replayCorrections(n.sessionLog[A]);return n;});
guardCase('IG33-STRIKE-OLD-EVIDENCE',(p,c)=>{const n=strike(p,c);p.sessionLog[A].corrLog=copy(n.sessionLog[A].corrLog);p.feed=copy(n.feed);return n;});
guardCase('IG33-STRIKE-THEN-LOAD-AMEND',(p,c)=>{const n=strike(p,c);file(c,n,'amend',[{id:ID,w:105}],ID,'load-amend','2030-02-03T13:00:00Z');c.T._replayCorrections(n.sessionLog[A]);return n;});
guardCase('IG33-LOAD-AMEND-POSITIVE',(p,c)=>{const n=copy(p);file(c,n,'amend',[{id:ID,w:105}]);c.T._replayCorrections(n.sessionLog[A]);return n;});
for(const variant of ['MISSING','SCALAR','WRONG-ID','MISSING-REPS','INVALID-AT','EMPTY-OP','UNKNOWN-KIND','NO-RECEIPT','WRONG-RECEIPT','PAYLOAD-MISMATCH','RIR-MISMATCH','AMEND-SHRINK','LOAD-AMEND-SHRINK','SUPERSEDED','CONTRADICTORY-OP'])guardCase('IG33-CORRECTION-'+variant,(p,c)=>{
  const n=copy(p);n.sessionLog[A].entries[0].reps=[10,9];n.sessionLog[A].entries[0].rirSets=[2,1];
  if(variant==='MISSING')return n;
  const to=variant==='SCALAR'?1:variant==='WRONG-ID'?[{id:OTHER,reps:[10,9]}]:variant==='MISSING-REPS'?[{id:ID,w:95}]:variant==='PAYLOAD-MISMATCH'?[{id:ID,reps:[7,6]}]:variant==='RIR-MISMATCH'?[{id:ID,reps:[10,9],rirSets:[0,0]}]:variant==='LOAD-AMEND-SHRINK'?[{id:ID,w:95}]:[{id:ID,reps:[10,9],rirSets:[2,1]}];
  const kind=variant.includes('AMEND')?'amend':variant==='UNKNOWN-KIND'?'mystery':'strike';
  file(c,n,kind,to);
  if(variant==='INVALID-AT')n.sessionLog[A].corrLog[0].at='not-an-instant';
  if(variant==='EMPTY-OP')n.sessionLog[A].corrLog[0].op='';
  if(variant==='UNKNOWN-KIND')n.sessionLog[A].corrLog=[{op:'synthetic-correction',kind:'mystery',id:ID,at:'2030-02-03T12:00:00Z',to}];
  if(variant!=='NO-RECEIPT')n.feed.push({d:A,op:variant==='WRONG-RECEIPT'?'different-op':'synthetic-correction',t:'SYNTHETIC strike receipt'});
  if(variant==='SUPERSEDED')file(c,n,'strike',[{id:ID,reps:[7,6,5]}],ID,'later-strike','2030-02-03T13:00:00Z');
  if(variant==='CONTRADICTORY-OP')n.sessionLog[A].corrLog.push({...n.sessionLog[A].corrLog[0],kind:'skip',id:OTHER});
  return n;
},[slot(2)],true);
guardCase('IG33-UNRELATED-REAL-STRIKE',(p,c)=>{p.sessionLog[A].entries.push(entry(OTHER));const n=copy(p);file(c,n,'strike',[{id:OTHER,reps:[10,9]}],OTHER);n.feed.push({d:A,op:'synthetic-correction',t:'SYNTHETIC'});c.T._replayCorrections(n.sessionLog[A]);n.sessionLog[A].entries=n.sessionLog[A].entries.filter(x=>x.id!==ID);return n;},[lostEntry],true);
guardCase('IG33-UNSKIP-SHORTER',(p,c)=>{const n=copy(p);file(c,n,'unskip',{...entry(),reps:[10,9],rirSets:[2,1]});c.T._replayCorrections(n.sessionLog[A]);n.feed.push({d:A,t:'SYNTHETIC op-less unskip'});return n;});
guardCase('IG33-SKIP-UNSKIP-FINAL',(p,c)=>{const n=copy(p);file(c,n,'skip',undefined);file(c,n,'unskip',{...entry(),reps:[10,9]},ID,'final-unskip','2030-02-03T13:00:00Z');c.T._replayCorrections(n.sessionLog[A]);return n;});
guardCase('IG33-UNSKIP-SKIP-FINAL',(p,c)=>{const n=copy(p);file(c,n,'unskip',entry());file(c,n,'skip',undefined,ID,'final-skip','2030-02-03T13:00:00Z');c.T._replayCorrections(n.sessionLog[A]);return n;});
for(const variant of ['AMEND-NONARRAY','UNSKIP-NONARRAY','STRIKE-SCALAR-NOOP','DUPLICATE-KIND','DUPLICATE-ID','NONJSON'])guardCase('IG33-MIXED-'+variant,(p,c)=>{const n=strike(p,c);if(variant==='AMEND-NONARRAY')file(c,n,'amend',[{id:ID,reps:1}],ID,'later','2030-02-03T13:00:00Z');if(variant==='UNSKIP-NONARRAY')file(c,n,'unskip',{id:ID,reps:1},ID,'later','2030-02-03T13:00:00Z');if(variant==='STRIKE-SCALAR-NOOP')file(c,n,'strike',1,ID,'later','2030-02-03T13:00:00Z');if(variant==='DUPLICATE-KIND')n.sessionLog[A].corrLog.push({...n.sessionLog[A].corrLog[0],kind:'amend'});if(variant==='DUPLICATE-ID')n.sessionLog[A].corrLog.push({...n.sessionLog[A].corrLog[0],id:OTHER});if(variant==='NONJSON')n.sessionLog[A].corrLog[0].extra=undefined;return n;},variant==='STRIKE-SCALAR-NOOP'?[]:[slot(2)],variant!=='STRIKE-SCALAR-NOOP');
guardCase('IG33-SKIP-UNRELATED-LOSS',(p,c)=>{p.sessionLog[A].entries.push(entry(OTHER));const n=copy(p);file(c,n,'skip',undefined);c.T._replayCorrections(n.sessionLog[A]);n.sessionLog[A].entries=[];return n;},[reason('entryidentity',A,OTHER)],true);
add('D33','IG33-OPAQUE-ENTRIES-GETTER',['guard','getter','inputs'],c=>{let calls=0;const p=state();Object.defineProperty(p.sessionLog[A],'entries',{enumerable:true,configurable:true,get(){calls++;throw Error('OPAQUE_ENTRIES_GETTER');}});const n=copy(p);Object.defineProperty(n.sessionLog[A],'entries',{enumerable:true,configurable:true,writable:true,value:[undefined]});const before=shape([p,n]);const g=c.T.dataLossGuard(p,n);c.check('guard',exact(g,{safe:false,lost:[lostSession]}));c.check('getter',calls===0);c.check('inputs',exact(shape([p,n]),before));c.record('opaque.getter',{calls});},true);
guardCase('IG33-AMBIGUOUS-NULL-PROTO-EDIT',p=>{const body=Object.create(null);body.constructor=Object;body.flag='old';p.sessionLog[A].entries=[{reps:body}];const n=copy(p);n.sessionLog[A].entries[0].reps.flag='new';return n;},[lostSession],true);
for(const variant of ['SKIP','UNSKIP','REPEATED'])add('D33','IG33-LIVE-'+variant,['guard','placement','receipt','inputs'],c=>{const h=c.hosts(),p=state();p.sessionLog[A].entries.push(entry(OTHER));p.exercises=[{id:ID,n:'Synthetic A',w:100,std:[10,9]},{id:OTHER,n:'Synthetic B',w:100,std:[10,9]}];let n;if(variant==='SKIP')n=h.liveSkip(p,ID,A);else{const skipped=h.liveSkip(p,ID,A);n=h.liveUnskip(skipped,ID,A,'10,9');if(variant==='REPEATED'){const skippedAgain=h.liveSkip(n,ID,A);n=h.liveUnskip(skippedAgain,ID,A,'10,9');}}const before=shape([p,n]),g=c.T.dataLossGuard(p,n);c.check('guard',exact(g,{safe:true,lost:[]}));c.check('placement',variant==='SKIP'?!n.sessionLog[A].entries.some(e=>e.id===ID)&&n.sessionLog[A].skipped.some(e=>e.id===ID):exact(n.sessionLog[A].entries.find(e=>e.id===ID).reps,[10,9])&&!(n.sessionLog[A].skipped||[]).some(e=>e.id===ID));c.check('receipt',n.feed.length===(variant==='SKIP'?1:variant==='UNSKIP'?2:4)&&n.feed.every(f=>!Object.prototype.hasOwnProperty.call(f,'op')));c.check('inputs',exact(shape([p,n]),before));});
for(const variant of ['IDLESS','DUPLICATE','NONARRAY','SKIPPED-IDLESS','SKIPPED-DUPLICATE'])for(const action of ['KEEP-ADD','REMOVE','EDIT'])guardCase('IG33-AMBIGUOUS-'+variant+'-'+action,p=>{
  const r=p.sessionLog[A];if(variant==='IDLESS')r.entries=[{reps:[10,9],note:'same body'}];if(variant==='DUPLICATE')r.entries=[entry(),entry()];if(variant==='NONARRAY')r.entries=[{id:ID,reps:'10,9'}];if(variant==='SKIPPED-IDLESS')r.skipped=[{note:'skipped body'}];if(variant==='SKIPPED-DUPLICATE')r.skipped=[{id:OTHER},{id:OTHER}];
  const n=copy(p),b=variant.startsWith('SKIPPED')?n.sessionLog[A].skipped:n.sessionLog[A].entries;if(action==='REMOVE')b.pop();else if(action==='EDIT')b[0].extra='changed';else n.sessionLog[A].entries.push(entry('synthetic-added'));return n;
},action==='KEEP-ADD'?[]:[lostSession],action!=='KEEP-ADD');
guardCase('IG33-AMBIGUOUS-KEY-ORDER',p=>{p.sessionLog[A].entries=[{reps:[10,9],note:'same'}];const n=copy(p);n.sessionLog[A].entries=[{note:'same',reps:[10,9]}];return n;});
guardCase('IG33-REASON-ORDER',p=>{p.feed=[{d:A,op:'permanent',t:'synthetic'}];p.sessionLog[A].entries.push(entry(OTHER),{reps:[1]});p.sessionLog[A].skipped=[{id:OTHER}];const n=copy(p);n.feed=[];n.reads[0].d=B;n.sessionLog[A].entries=[{...entry(),reps:[10,9]}];delete n.sessionLog[A].skipped;return n;},['feedop permanent',reason('readidentity',A),reason('entryidentity',A,OTHER),slot(2),reason('skippedidentity',A,OTHER),lostSession],true);
guardCase('IG33-SLOT-NUMERIC-ORDER',p=>{p.sessionLog[A].entries[0].reps=Array(12).fill(1);const n=copy(p);delete n.sessionLog[A].entries[0].reps[2];delete n.sessionLog[A].entries[0].reps[10];return n;},[slot(2),slot(10)],true);
guardCase('IG33-FEED-PERMANENT-DEDUP',p=>{p.feed=[{d:A,op:'permanent',t:'synthetic one'},{d:A,op:'permanent',t:'synthetic two'}];const n=copy(p);n.feed.pop();return n;});
guardCase('IG33-FEED-PERMANENT-MISSING',p=>{p.feed=[{d:A,op:'permanent',t:'synthetic'}];const n=copy(p);n.feed=[];return n;},['feedop permanent']);
guardCase('IG33-FEED-DERIVED',p=>{p.feed=[{d:A,op:'carve:synthetic',t:'synthetic derived'}];const n=copy(p);n.feed=[];return n;});
for(const variant of ['NO-READ','CLEAN','SEALED','OFFWINDOW'])guardCase('IG33-FEED-MISSED-'+variant,p=>{p.reads=[];p.feed=[{d:A,t:'MORNING READ MISSED synthetic'}];const n=copy(p);n.feed=[];if(variant!=='NO-READ')n.reads=[{d:A,w:170,...variant==='SEALED'?{sealed:true}:variant==='OFFWINDOW'?{offWindow:true}:{}}];return n;},['NO-READ','OFFWINDOW'].includes(variant)?['missedday '+A]:[]);
function actualStarter(T){return T.migrate(null);}
add('D34','IG34-REAL-SEED',['raw','settled','repeat','unchanged','no-effects'],c=>{const s=actualStarter(c.T);c.check('raw',c.T.isPristineSeed(c.T.SEED)===true);const before=shape(s);c.reset();c.check('settled',c.T.isPristineSeed(s)===true);c.check('unchanged',exact(shape(s),before));c.check('no-effects',c.effects()===0);c.T._settleExit(s);c.check('repeat',c.T.isPristineSeed(s)===true);});
add('D34','IG34-READ-PT',['pristine','unchanged','no-effects'],c=>{const s=actualStarter(c.T);s.reads[0].pt='synthetic changed point';const before=shape(s);c.reset();c.check('pristine',c.T.isPristineSeed(s)===false);c.check('unchanged',exact(shape(s),before));c.check('no-effects',c.effects()===0);},true);
function pristineCase(id,change,wanted=false,frozenRed=!wanted){add('D34',id,['pristine','unchanged','no-effects'],c=>{if(id.startsWith('IG34-SESSION-'))c.T.SEED.sessionLog={[A]:{entries:[entry()],skipped:[{id:OTHER}],note:'synthetic session'}};const s=actualStarter(c.T);change(s,c);const before=shape(s);c.reset();c.check('pristine',c.T.isPristineSeed(s)===wanted);c.check('unchanged',exact(shape(s),before));c.check('no-effects',c.effects()===0);},frozenRed);}
for(const field of ['w','d','note','sealed','offWindow','reclass','pt'])pristineCase('IG34-READ-'+field.toUpperCase()+'-CONTENT',s=>{s.reads[0][field]='synthetic altered '+field;});
pristineCase('IG34-READ-NULL',s=>{s.reads[0].w=null;});
pristineCase('IG34-READ-TYPE',s=>{s.reads[0].w=String(s.reads[0].w);});
pristineCase('IG34-READ-EXTRA',s=>{s.reads[0].syntheticExtra=true;});
pristineCase('IG34-READ-MISSING-PROPERTY',s=>{delete s.reads[0].w;});
for(const field of ['d','h','note','quality'])pristineCase('IG34-NIGHT-'+field.toUpperCase(),s=>{s.sleep.nights[0][field]='synthetic altered '+field;});
for(const field of ['cal','pro','steps','note'])pristineCase('IG34-DAILY-'+field.toUpperCase(),s=>{s.dailyLogs[Object.keys(s.dailyLogs)[0]][field]='synthetic altered '+field;});
for(const field of ['w','reps','rir','rirSets'])pristineCase('IG34-SESSION-ENTRY-'+field.toUpperCase(),s=>{const r=s.sessionLog[Object.keys(s.sessionLog)[0]];r.entries[0][field]=field==='reps'||field==='rirSets'?[99,98]:null;});
for(const field of ['skipped','corr','corrLog','dropped','note'])pristineCase('IG34-SESSION-'+field.toUpperCase(),s=>{s.sessionLog[Object.keys(s.sessionLog)[0]][field]=field==='corr'?{at:'2030-02-03T12:00:00Z',rev:999}:field==='note'?'synthetic extra':[{synthetic:'changed'}];});
pristineCase('IG34-READ-REORDER',s=>{[s.reads[0],s.reads[1]]=[s.reads[1],s.reads[0]];});
pristineCase('IG34-READ-MULTIPLICITY',s=>{s.reads[0]=copy(s.reads[1]);});
pristineCase('IG34-NIGHT-REORDER',s=>{[s.sleep.nights[0],s.sleep.nights[1]]=[s.sleep.nights[1],s.sleep.nights[0]];});
function reverseKeys(v){if(Array.isArray(v))return v.map(reverseKeys);if(v&&typeof v==='object'){const n={};for(const k of Object.keys(v).reverse())n[k]=reverseKeys(v[k]);return n;}return v;}
pristineCase('IG34-OBJECT-KEY-ORDER',s=>{s.reads=s.reads.map(reverseKeys);s.sleep.nights=s.sleep.nights.map(reverseKeys);s.dailyLogs=reverseKeys(s.dailyLogs);s.sessionLog=reverseKeys(s.sessionLog);},true,false);
pristineCase('IG34-EXCLUDED-FAMILIES',s=>{s.trend=999;s.weekly=[];s.exercises=[];s.feed=[{d:A,t:'synthetic'}];s.waist=[{d:A,w:1}];s.photos=[{d:A,ref:'synthetic'}];s.targets={synthetic:true};s.decisions=[{synthetic:true}];s.queue=[{synthetic:true}];},true,false);
pristineCase('IG34-ADDED-READ',s=>{s.reads.push({d:'2031-01-01',w:170});},false,false);
for(const variant of ['UNDEFINED','FUNCTION','INFINITY','CYCLE','GETTER'])pristineCase('IG34-NONJSON-'+variant,s=>{if(variant==='GETTER')Object.defineProperty(s.reads[0],'hidden',{enumerable:true,get(){throw Error('IG34_GETTER_MUST_NOT_RUN');}});else s.reads[0].extra=variant==='UNDEFINED'?undefined:variant==='FUNCTION'?function synthetic(){}:variant==='INFINITY'?Infinity:s.reads[0];});
add('D34','IG34-SYNTHETIC-SEED',['raw','settled','repeat'],c=>{const seed=c.T.SEED;seed.reads=[{d:A,w:170,pt:'synthetic'}];seed.sleep.nights=[{d:A,h:8}];seed.dailyLogs={[A]:{cal:2400,pro:160}};seed.sessionLog={};c.check('raw',c.T.isPristineSeed(copy(seed))===true);const s=c.T.migrate(null);c.check('settled',c.T.isPristineSeed(s)===true);c.T._settleExit(s);c.check('repeat',c.T.isPristineSeed(s)===true);});
for(const variant of ['FRESH','EDITED','EXISTING','CLEAR-PRISTINE','CLEAR-EDITED'])add('D34','IG34-MARKER-'+variant,['marker','offer','state'],c=>{const h=c.hosts(),s=actualStarter(c.T);if(['EDITED','EXISTING','CLEAR-EDITED'].includes(variant))s.reads[0].pt='synthetic changed point';const raw=variant==='FRESH'?null:JSON.stringify(s),b=h.bootMarker({raw,marker:variant==='EXISTING'?'1':null});if(variant.startsWith('CLEAR'))h.clearMarker(b.store);const marked=b.store.data.get('pl-restore-offer')==='1',wanted=variant==='FRESH'||variant==='EXISTING';c.check('marker',marked===wanted);c.check('offer',h.offerMarker(b.s,b.store)===(wanted||variant==='CLEAR-PRISTINE'));c.check('state',variant==='FRESH'?c.T.isPristineSeed(b.s)===true:b.s.reads[0].pt===s.reads[0].pt);c.record('marker.final',{calls:b.store.calls,marked,state:b.s});},variant==='EDITED'||variant==='CLEAR-EDITED');
for(const variant of ['NULL','MISSING','STRING','ALIASES','CYCLE','HEAL-GETTER','UNKNOWN-GETTER'])add('D35','IG35-FUTURE-'+variant,['return-identity','descriptors','getter','no-effects'],c=>{let reads=0;const p={v:variant==='STRING'?'61':61};if(variant!=='MISSING'){p.sleep=null;p.reads=null;p.dailyLogs=null;p.sessionLog=null;}if(variant==='ALIASES'){p.x={z:1};p.y=p.x;}if(variant==='CYCLE')p.self=p;if(variant==='HEAL-GETTER')Object.defineProperty(p,'sleep',{enumerable:true,configurable:true,get(){reads++;throw Error('IG35_FORBIDDEN_FIELD_READ');}});if(variant==='UNKNOWN-GETTER')Object.defineProperty(p,'unknown',{enumerable:true,configurable:true,get(){reads++;throw Error('IG35_UNKNOWN_FIELD_READ');}});const before=shape(p);c.reset();let result,err;try{result=c.T.migrate(p);}catch(e){err={name:e.name,message:e.message};}c.record('future.result',{result,error:err,input:p,getterCalls:reads});c.check('return-identity',!err&&result===p);c.check('descriptors',exact(shape(p),before));c.check('getter',reads===0);c.check('no-effects',c.effects()===0);},true);
function syntheticMigration(T,v){const s=copy(T.SEED);s.v=v;s.reads=[{d:A,w:170,morning:true,note:'synthetic'}];s.sleep={nights:[{d:A,h:8}],needed:3};s.dailyLogs={[A]:{cal:2400,pro:160,steps:6000}};s.sessionLog={};s.events=[];s.feed=[];s.adjustments=[];s.suggestionLog=[];s.corrLog={};s.learned={tdee:[],anchors:[]};s.waist=[];s.photos=[];for(const e of s.exercises){delete e.last;delete e.lastMeta;e.topAt=null;e.topRun=0;}return s;}
function legacyPair(T){const rich=syntheticMigration(T,60);rich.sessionLog[A]={entries:[entry(),entry(OTHER)],at:1896350400000,note:'synthetic legacy'};const sparse=copy(rich);sparse.sessionLog[A].entries=[entry(OTHER)];sparse.sessionLog[A].corr={at:'2030-02-03T13:00:00.000Z',rev:1};return{rich,sparse};}
for(const direction of ['FORWARD','REVERSE'])add('D33','IG33-LEGACY-CORR-'+direction,['winner','rich-guard','sparse-guard','retry','receipts'],c=>{const{rich,sparse}=legacyPair(c.T),remoteBefore=copy(direction==='FORWARD'?rich:sparse),localBefore=copy(direction==='FORWARD'?sparse:rich),remote=copy(remoteBefore),local=copy(localBefore),rm=c.T.migrate(remote),merged=c.T.mergeState(local,rm),final=c.T.migrate(merged),receiptBefore=shape(final.feed),r=c.T.dataLossGuard(rich,final),s=c.T.dataLossGuard(sparse,final);c.check('winner',!final.sessionLog[A].entries.some(e=>e.id===ID)&&final.sessionLog[A].entries.some(e=>e.id===OTHER));c.check('rich-guard',exact(r,{safe:false,lost:[lostEntry]}));c.check('sparse-guard',exact(s,{safe:true,lost:[]}));const again=c.T.migrate(c.T.mergeState(copy(localBefore),c.T.migrate(copy(remoteBefore))));c.check('retry',exact(c.T.dataLossGuard(rich,again),{safe:false,lost:[lostEntry]}));c.check('receipts',exact(shape(final.feed),receiptBefore));c.record('legacy.complete',{remoteBefore,localBefore,remote,local,rm,merged,final,again});},true);
for(const direction of ['REMOTE-RICH','LOCAL-RICH'])add('D33','IG33-GHSYNC-'+direction,['host-outcome','inputs','repeat'],c=>{const h=c.hosts(),{rich,sparse}=legacyPair(c.T),local=direction==='REMOTE-RICH'?sparse:rich,remote=direction==='REMOTE-RICH'?rich:sparse,localBefore=copy(local),remoteBefore=copy(remote),first=h.ghSyncBuild(local,remote),second=h.ghSyncBuild(copy(localBefore),copy(remoteBefore));c.check('host-outcome',direction==='REMOTE-RICH'?first===null:first!==null&&typeof first.content==='string');c.check('inputs',exact(local,localBefore));c.check('repeat',exact(first,second));c.record('ghsync.complete',{localBefore,remoteBefore,local,remote,first,second});},direction==='REMOTE-RICH');
for(const force of [false,true])add('D33','IG33-SAVE-'+(force?'FORCE':'GUARDED'),['durable','banner','inputs'],c=>{const h=c.hosts(),{rich,sparse}=legacyPair(c.T),next=c.T.migrate(c.T.mergeState(copy(rich),c.T.migrate(copy(sparse)))),before=shape([rich,next]),result=h.saveGuard(rich,next,force?{force:true}:{});c.check('durable',exact(result.durable,force?next:rich));c.check('banner',exact(result.offline,force?[]:['guard:'+lostEntry]));c.check('inputs',exact(shape([rich,next]),before));},!force);
for(const direction of ['REMOTE-RICH','LOCAL-RICH'])add('D33','IG33-RESTORE-UNGUARDED-'+direction,['unguarded-result','receipt','rich-guard'],async c=>{const h=c.hosts(),{rich,sparse}=legacyPair(c.T),local=direction==='REMOTE-RICH'?sparse:rich,remote=direction==='REMOTE-RICH'?rich:sparse,localBefore=copy(local),remoteBefore=copy(remote),restored=await h.restoreFromCloud(local,remote);c.check('unguarded-result',!!restored&&!restored.sessionLog[A].entries.some(e=>e.id===ID));c.check('receipt',restored.feed.some(f=>f.t==='LEDGER RESTORED FROM THE CLOUD'));c.check('rich-guard',exact(c.T.dataLossGuard(rich,restored),{safe:false,lost:[lostEntry]}));c.record('restore.preimages',{localBefore,remoteBefore,local,remote,restored});},true);
for(const v of [null,1,2,...Array.from({length:58},(_,i)=>i+3)])add('D35','IG35-SUPPORTED-'+(v===null?'NULL':v),['version','first-alias','repeat-alias','first-call','repeat-call'],c=>{const old=v===null?null:syntheticMigration(c.T,v);if(v===1)old.queue=[{id:'hack3',done:true}];c.reset();const first=c.T.migrate(old),snapshot=copy(first),oldSnapshot=copy(old);c.check('version',first.v===60);c.check('first-alias',(first===old)===(v===60));c.check('first-call',first!==null&&Array.isArray(first.reads)&&first.sleep&&Array.isArray(first.sleep.nights));const second=c.T.migrate(first);c.check('repeat-alias',second===first);c.check('repeat-call',second.v===60&&Array.isArray(second.feed));c.record('supported.complete',{old,first,second,firstSnapshot:snapshot,oldAfterFirst:oldSnapshot,firstIsOld:first===old,secondIsFirst:second===first});});
add('D35','IG35-SUPPORTED-V1-CLOCK',['stamp','effects'],c=>{const old=syntheticMigration(c.T,1);old.queue=[{id:'hack3',done:true}];c.reset();const out=c.T.migrate(old);c.check('stamp',out.exercises.find(e=>e.id==='hack').setsAt===c.iso);c.check('effects',c.effects()>0);c.record('supported.clock',{old,out});});
function context(target,test){let effects=0,sequence=0,randomSequence=0;const day=target.day||'2026-09-03',ms=new Date(...day.split('-').map((n,i)=>+n-(i===1?1:0)),12).getTime(),iso=new Date(ms).toISOString(),clock={today(){effects++;return day;},nowMs(){effects++;return ms;},nowISO(){effects++;return iso;},hour(){effects++;return 12;},dow(){effects++;return new Date(ms).getDay();},tz:'America/New_York'},ids={fresh(prefix=''){effects++;const r=((++randomSequence*104729)%1048576)/1048576;return prefix+ms.toString(36)+(sequence++).toString(36)+r.toString(36).slice(2,6);}},drafts={get length(){effects++;return 0;},key(){effects++;return null;},getItem(){effects++;return null;},setItem(){effects++;},removeItem(){effects++;}};const raw=target.engine({clock,ids,drafts}),T=raw.__test||raw,assertions=[],record=(name,value)=>target.record&&target.record(test.id+'.'+name,value);return{T,clock,day,iso,record,reset(){effects=0;},effects(){return effects;},check(name,ok){assertions.push({id:test.id+':'+name,ok:ok===true});},assertions,hosts(){if(!target.createHosts)throw Error('HOST-FACTORY-MISSING');return target.createHosts(T);}};}
const definitions=[['D33','V4-guard-record-identities-and-sets',['counts-only','missing-entry-slot','accept-any-correction','ignore-strike-receipt-payload','deny-all']],['D34','V4-pristine-compares-record-content',['coarse-fingerprint','never-pristine','raw-key-order','whole-state-comparison']],['D35','V4-unknown-schema-return-untouched',['heal-before-return','return-all-unchanged']]];
const laws=definitions.map(([defect,id,mutants])=>Object.freeze({id,defect,cite:'BRIEF-IMPORT-GUARDS.md §§1–3',expect:'GREEN',implementation:'PRESENT',requiredCases:CASES.filter(x=>x.defect===defect).map(x=>x.id),requiredMutants:mutants,async run(target){const tests=CASES.filter(x=>x.defect===defect&&(!target.caseId||target.caseId===x.id));if(!tests.length)throw Error('CASE-NOT-FOUND');const assertions=[];for(const test of tests){const c=context(target,test);await test.execute(c);const expected=test.claims.map(x=>test.id+':'+x);if(!exact(c.assertions.map(x=>x.id).sort(),expected.slice().sort()))throw Error('ASSERTION-INVENTORY:'+test.id);assertions.push(...c.assertions);}return{ok:assertions.every(x=>x.ok),assertions};},mutant:[]}));
module.exports={laws,INVENTORY:laws.map(x=>x.id),CASES:CASES.map(({execute,...x})=>x),ASSERTION_INVENTORY:CASES.flatMap(x=>x.claims.map(k=>({caseId:x.id,defect:x.defect,id:x.id+':'+k}))),FIXTURE:{A,B,ID,OTHER}};
