/* reference/client.cjs — THE REFERENCE CLIENT (in-memory model of the shell + local engine seams; NOT the product).
   Proves every §B law satisfiable; each law's targeted mutant is a one-hook delta (hooks below). The product's client
   adapter (adapters/client.cjs, tranche T2) must pass the same laws. Sheet v1.7.38 §B states 1–20, durability and
   copy laws, D7 ladder, PRESENCE LAW, A1 client-side commitment. Synthetic fixtures only. */
const O = require("../lib/ops.cjs");
const { canonicalEncode, hmac, AUTH_KEY } = O;
const DAY = 86400000;
const addDays = (d, n) => new Date(Date.parse(d + "T12:00:00Z") + n * DAY).toISOString().slice(0, 10);
function create(opts = {}, hooks = {}) {
  const H = Object.assign({ atomicDurability: true, fourLabels: true, layersSeparate: true, dependencyAware: true, derivedOnlyFromFrontier: true, responseAltersNoPlan: true,
    d7: { staleFrom: 3, reentryFrom: 7 }, drainOnStoredDisposition: true, verifyDisposition: true, retrySameOpId: true, backoff: [0, 1000, 2000, 4000], coldStartSkeleton: true,
    firstUseNoPlan: true, leanFromOneMinusBf: true, loggingNeverPlans: true, presenceLaw: true, partitionComplete: true, precedence: true, atomicRejectedLedger: true, frontierContiguous: true,
    state6HidesProposals: true, state7SuppressesOnly: true, issuanceFirst: true, conflictSuspend: true, machinePrecedence: true, commitmentExcludesSelf: true, nullDistinct: true, revokedRefuses: true, leaseRefuses: true, canonical: {}, hiddenPlanLeak: false, instanceFromContent: true, fallbackFromProvenance: true, candidateEdge: true, generationAdvances: true, collisionCanonical: true, gatesAfterCollision: true, state11LogsOn: true, state13NoGhost: true, state18Integrity: true, conflictCopyExact: true }, hooks);
  const K = opts.identityKey || O.K_IDENTITY; const COPTS = Object.assign({}, O.CANON.defaults, H.canonical || {}); const tz = opts.tz || "-04:00"; let today = opts.today || "2026-09-04"; const dev = opts.device_id || "dev-A";
  const S = { ops: [], outbox: [], sent: [], dispositions: {}, rejected: [], receipts: [], W: 0, authorityW: (opts.lastSync && opts.lastSync.W) || 0, seq: 0, layer1: { plan: Object.assign({}, (opts.lastSync && opts.lastSync.plan) || {}), reads: [], edits: {} }, answers: [], fields: {}, sessions: [], resolved: null, now: 0, nextRetryAt: {}, attempts: {}, applied: {}, issued: {}, suspended: {} };
  const last = opts.lastSync || {}; const reads = (opts.reads || [opts.today || "2026-09-04"]).slice();   /* an athlete with no reads at all is first use, never re-entry */
  const lease = opts.lease || O.lease(dev); const clockNow = opts.now || "2026-09-04T00:00:00Z";
  const online = { v: opts.online !== false }; let acceptButDoNotReduce = false;
  const governing = () => {
    if (opts.restoreRequired) return 18; if (opts.revoked) return 17; if (H.leaseRefuses && clockNow > lease.not_after) return 20; if (opts.storage === "refuse-writes") return 3;
    if (H.machinePrecedence === false && opts.contractObsolete) return 7;   /* MUTANT order: contract currency over session ambiguity */
    if (S.sessions.length && !S.resolved && ambiguity().component) return 14; if (opts.contractObsolete) return 7; if (S.outbox.length || S.authorityW > S.W) return online.v ? (S.outbox.length ? 2 : 6) : 1; return 0; };
  const writeState = () => { if (opts.restoreRequired) return 18; if (opts.revoked && H.revokedRefuses) return 17; if (H.leaseRefuses && clockNow > lease.not_after) return 20; if (opts.storage === "refuse-writes") return 3; return 0; };
  function commit(kind, cls, payload, extra = {}) {
    const field = extra.field || kind; S.fields[field] = payload;
    const ws = H.precedence ? writeState() : (opts.storage === "refuse-writes" ? 3 : (opts.revoked && H.revokedRefuses ? 17 : (H.leaseRefuses && clockNow > lease.not_after ? 20 : 0)));
    if (ws === 3) return { acknowledged: false, state: 3, copy: "Nothing was recorded — this phone couldn't save it (storage full or denied). Try again." };
    if (ws === 17) return { acknowledged: false, state: 17, copy: "Sign in to keep saving." };
    if (ws === 20) return { acknowledged: false, state: 20, copy: "Connect once to keep saving — Earned can't promise this phone's entries will be accepted after " + lease.not_after.slice(0, 10) + " without checking in." };
    if (ws === 18) return { acknowledged: false, state: 18, copy: "Restore required." };
    const seq = S.seq + 1; const op = O.build({ op_id: extra.op_id || ("op-" + dev + "-" + seq), device_id: dev, device_seq: seq, pred: S.ops.length ? S.ops[S.ops.length - 1].op_id : null, kind, class: cls, payload, target: extra.target, plan: extra.plan, lease_id: lease.lease_id, effective: extra.effective || { local_date: today, local_time: "07:05", utc_offset: tz } }, K);
    op.canonical_content_commitment = O.commitmentOf(op, K, COPTS);
    if (!H.commitmentExcludesSelf) op.canonical_content_commitment = hmac(K, "earned/op/v1" + canonicalEncode({ ...op, authority_signature: undefined }));
    /* ONE durable local transaction: the operation AND its outbox entry, or neither */
    if (opts.storage === "crash-after-op-before-outbox") { if (H.atomicDurability) return { acknowledged: false, state: 3, copy: "Nothing was recorded — this phone couldn't save it. Try again." }; S.ops.push(op); S.seq = seq; return { acknowledged: true, state: 1, copy: "Saved", op_id: op.op_id }; }
    S.ops.push(op); S.outbox.push({ op_id: op.op_id, op }); S.seq = seq; S.nextRetryAt[op.op_id] = 0; S.attempts[op.op_id] = 0;
    return { acknowledged: true, state: online.v ? 2 : 1, copy: "Saved on this phone · not yet synced", op_id: op.op_id };
  }
  const missingDates = () => { const dates = reads.concat(S.layer1.reads.map((r) => r.date)); let n = 0; for (let d = today; n < 60; d = addDays(d, -1)) { if (dates.includes(d)) break; n++; } return n; };
  function layer2() {
    const missing = missingDates(); const board = missing < H.d7.staleFrom ? "NO_WEIGH_IN_TODAY" : missing < H.d7.reentryFrom ? "STALE" : "RE_ENTRY";
    const l2 = { label: last.asOf ? "as of " + last.asOf : null, trend: last.trend == null ? null : last.trend, rate: last.rate == null ? null : last.rate, maintenance: last.maintenance == null ? null : last.maintenance, instruction: last.instruction || null, outputs: (last.outputs || []).slice(), proposals: (last.proposals || []).slice(), actionLoci: (last.actionLoci || []).slice(), paceCurrent: true, board, missingDates: missing, copy: board === "NO_WEIGH_IN_TODAY" ? (missing ? "No weigh-in today." : "") : board === "STALE" ? "Keep for now" : "Re-entry — weigh in to bring Today back" };
    if (board === "STALE") l2.paceCurrent = false;
    if (board === "RE_ENTRY") { l2.trend = null; l2.rate = null; l2.maintenance = null; l2.proposals = []; l2.instruction = null; }
    if (H.derivedOnlyFromFrontier) { const touched = new Set(Object.keys(S.layer1.edits)); if (H.dependencyAware) { l2.outputs = l2.outputs.filter((o) => !(o.deps || []).some((d) => touched.has(d))); l2.proposals = l2.proposals.filter((p) => !(p.deps || []).some((d) => touched.has(d))); l2.actionLoci = l2.actionLoci.filter((a) => !(a.deps || []).some((d) => touched.has(d))); if (l2.instruction && (last.instructionDeps || []).some((d) => touched.has(d))) l2.instruction = null; } else if (touched.size) { l2.outputs = []; l2.proposals = []; l2.actionLoci = []; l2.instruction = null; } }
    else { if (S.layer1.reads.length) l2.trend = S.layer1.reads[S.layer1.reads.length - 1].lb; }
    if (opts.contractObsolete) { if (H.state7SuppressesOnly) { l2.instruction = null; l2.proposals = []; l2.actionLoci = []; l2.outputs = []; l2.copy = "Update Earned to keep Today current."; } }
    if (online.v && (S.outbox.length || S.authorityW > S.W) && H.state6HidesProposals) { l2.proposals = []; l2.syncLine = "Sync to update Today."; }
    if (H.issuanceFirst) l2.proposals = l2.proposals.filter((p) => !p.unissued || (S.issued[p.id] && S.issued[p.id].accepted));
    return l2;
  }
  function face() {
    if (opts.coldStart && H.coldStartSkeleton) return { paint: "SKELETON", state: 9, layer1: { plan: S.layer1.plan, planProvenance: last.planProvenance || null, label: "last synced " + (last.time || last.asOf || "") }, layer2: { trend: null, rate: null, maintenance: null, instruction: null, outputs: [], proposals: [] }, today: "" };
    const st = governing(); const l2 = layer2();
    const emptyNoPlan = opts.emptyAccount && !S.applied.initial && H.firstUseNoPlan;
    const f = { paint: "TRUTHFUL", state: st, layer1: { plan: H.layersSeparate ? Object.assign({}, S.layer1.plan) : Object.assign({}, last.plan || {}, S.layer1.plan), planProvenance: last.planProvenance || null, label: S.outbox.length ? "Saved on this phone · not yet synced" : "", reads: S.layer1.reads.slice(), notYetSyncedCount: (opts.revoked && H.revokedRefuses) ? undefined : S.outbox.length }, layer2: l2, answers: S.answers.slice(), rejectedCount: S.rejected.length, rejectedLine: S.rejected.length ? S.rejected.length + " rejected entr" + (S.rejected.length === 1 ? "y" : "ies") + " on this phone" : null,
      today: emptyNoPlan ? "first use, no accepted plan" : (l2.instruction || (last.plan && last.plan.steps ? "Keep " + last.plan.steps.toLocaleString("en-US") + " steps" : "")), resolution: opts.revoked ? "This phone was removed from your account — sign in to re-enrol it" : opts.restoreRequired ? "Restore required — sign in" : null,
      acceptedPlan: last.plan ? { ...last.plan, provenance: last.planProvenance || null, version: last.planVersion || null } : null, history: S.history || [] };
    if (!H.firstUseNoPlan && opts.emptyAccount) f.today = "Keep 8,000 steps";
    if (S.suspended.p1) { f.layer1.plan = Object.assign({}, S.suspended.fallback); f.history = [{ txn: "t1", copy: "Applied at W1 · conflict-suspended at W2" }]; }
    return f;
  }
  function faceLabel(op_id) { const d = S.dispositions[op_id]; if (S.outbox.some((o) => o.op_id === op_id) && !S.sent.some((s) => s.op_id === op_id)) return "Saved on this phone · not yet synced"; if (!d || (!H.fourLabels ? false : (S.outbox.length || S.authorityW > S.W))) return H.fourLabels ? "Changes sent · receiving updates" : "Synced"; if (d && d.status === "ACCEPTED") { if (S.applied[op_id] && S.applied[op_id].effective && S.applied[op_id].committed && S.applied[op_id].received) return "Applied " + (S.applied[op_id].at || "just now"); return "Synced " + (d.decided_at || ""); } return "Rejected"; }
  function ambiguity() { if (!S.sessions.length) return { component: null }; const sorted = S.sessions.slice().sort((a, b) => a.start < b.start ? -1 : 1); const c = sorted.map((s) => s.start); if (S.resolved) return { component: c, decision: S.resolved, progressionBearing: true, generation: 1 }; return { component: c, decision: null, kind: "PARTITION", generation: 1, progressionBearing: false, candidates: c }; }
  const api = {
    weighIn: ({ date, lb }) => { const r = commit("fact", "reading", { lb: { value: lb, unit: "lb" }, source: "athlete" }, { field: "weighIn", effective: { local_date: date, local_time: "07:05", utc_offset: tz } }); if (r.acknowledged) S.layer1.reads.push({ date, lb, op_id: r.op_id }); S.fields.weighIn = lb; return r; },
    logSet: (p) => commit("session-set", "session", { load: { value: p.load, unit: "lb" }, reps: { value: p.reps, unit: "rep" } }, { field: "logSet" }),
    decision: (p) => commit("proposal-response", "plan", { answer: p.answer }, { field: "decision" }),
    correction: (target, fields) => commit("correction", "reading", { replacement_fields: fields }, { field: "correction", target }),
    tombstone: (target, reason) => commit("tombstone", "reading", { reason }, { field: "tombstone", target }),
    undoRequest: (target) => commit("undo-request", "plan", { target: { value: 1, unit: "txn" } }, { field: "undoRequest", target: undefined }),
    finishSession: () => commit("session-close", "session", { closed: { value: 1, unit: "flag" } }, { field: "finishSession" }),
    planEdit: ({ domain, value }) => { const r = commit("plan-mutation", "plan", null, { field: "planEdit", plan: { domain, members: [{ field: domain, value, unit: domain === "steps" ? "step/day" : "g/day", provenance: "athlete_edited" }] } }); if (r.acknowledged) { S.layer1.plan[domain] = value; S.layer1.edits[domain] = r.op_id; } return r; },
    respond: (proposalId, answer) => { const r = commit("proposal-response", "plan", { answer: { value: answer === "YES" ? 1 : 0, unit: "choice" } }, { field: "respond" }); if (r.acknowledged) { S.answers.push({ proposal: proposalId, answer, label: "Answer saved on this phone · takes effect after sync", op_id: r.op_id }); if (!H.responseAltersNoPlan && last.proposal && last.proposal.id === proposalId && answer === "YES") Object.assign(S.layer1.plan, last.proposal.apply); } return r; },
    face, faceLabel, plan: () => (opts.emptyAccount && !S.applied.initial ? (H.hiddenPlanLeak && opts.hiddenAcceptedPlan ? Object.assign({}, opts.hiddenAcceptedPlan) : null) : Object.assign({}, S.layer1.plan)), stateOf: governing,
    goOnline: (o = {}) => { online.v = true; acceptButDoNotReduce = !!o.acceptButDoNotReduce; }, goOffline: () => { online.v = false; },
    tick: (ms) => { S.now += ms; }, syncOnce: () => { if (!online.v || (opts.signInRequired && H.state11LogsOn)) return []; const sentNow = []; for (const e of S.outbox) { if (H.retrySameOpId ? S.now >= (S.nextRetryAt[e.op_id] || 0) : true) { const item = { op_id: H.retrySameOpId ? e.op_id : e.op_id + "#" + (S.attempts[e.op_id] + 1), at: S.now }; S.sent.push(item); sentNow.push(item); S.attempts[e.op_id]++; S.nextRetryAt[e.op_id] = S.now + (H.backoff[Math.min(S.attempts[e.op_id], H.backoff.length - 1)]); if (acceptButDoNotReduce) { S.dispositions[e.op_id] = { status: "ACCEPTED", op_id: e.op_id, decided_at: "2026-09-04T00:00:00Z" }; S.authorityW = Math.max(S.authorityW, S.W + 1); } } } if (acceptButDoNotReduce) { S.outbox = S.outbox.filter((e) => !S.dispositions[e.op_id]); } return sentNow; },
    outbox: () => S.outbox.map((e) => ({ op_id: e.op_id })), sentLog: () => S.sent.slice(),
    deliverDisposition: (d) => { const e = S.outbox.find((x) => x.op_id === d.op_id); const expected = e && e.op.canonical_content_commitment; const valid = !H.verifyDisposition || (d.authority_signature === hmac(AUTH_KEY, "earned/disposition/v1" + canonicalEncode({ ...d, authority_signature: undefined })) && !!e && d.canonical_content_commitment === expected);
      if (!valid) return { stored: false, reason: !e ? "unknown op_id" : "signature or commitment mismatch" }; if (d.status === "WAITING") { S.dispositions[d.op_id] = d; return { stored: true, drained: false }; }
      if (d.status === "ACCEPTED") { S.dispositions[d.op_id] = d; if (H.drainOnStoredDisposition) S.outbox = S.outbox.filter((x) => x.op_id !== d.op_id); return { stored: true, drained: true }; }
      /* REJECTED | REJECTED_DEPENDENCY: ONE atomic local transaction — disposition + rejected-ledger entry + outbox removal */
      if (opts.storage === "crash-in-rejected-ledger" && H.atomicRejectedLedger) return { stored: false, blocked: true, reason: "truth paint BLOCKED behind idempotent recovery" }; S.dispositions[d.op_id] = d; S.rejected.push({ op_id: d.op_id, commitment: expected, reason: d.rejection_code }); S.outbox = S.outbox.filter((x) => x.op_id !== d.op_id); if (!H.atomicRejectedLedger && opts.storage === "crash-in-rejected-ledger") S.rejected.pop(); return { stored: true, drained: true, rejected: true }; },
    deliverReceipts: (list) => { for (const r of list) if (!S.receipts.some((x) => x.seq === r.seq)) S.receipts.push(r); S.authorityW = Math.max(S.authorityW, ...S.receipts.map((r) => r.seq)); let w = S.W; const have = new Set(S.receipts.map((r) => r.seq)); if (H.frontierContiguous) { while (have.has(w + 1)) w++; } else w = Math.max(w, ...S.receipts.map((r) => r.seq)); S.W = w; return S.W; },
    frontier: () => S.W, reduceThroughW: () => { S.W = Math.max(S.W, S.authorityW); acceptButDoNotReduce = false; for (const id of Object.keys(S.dispositions)) if (S.dispositions[id].status === "ACCEPTED") { const op = S.ops.find((o) => o.op_id === id); if (op && op.kind === "plan-mutation" && S.applied[id]) S.applied[id].received = true; } return S.W; },
    authorityPlanTransaction: (op_id, r) => { S.applied[op_id] = Object.assign(S.applied[op_id] || {}, { committed: !!r.committed, effective: !!r.effective, at: r.at || "just now" }); },
    authorityDeliverDisposition: (op_id, d) => api.deliverDisposition(d),
    envelope: (op_id) => { const op = S.ops.find((o) => o.op_id === op_id); return op ? JSON.parse(JSON.stringify(op)) : null; },
    leanFromEstimate: ({ weightLb, bfLow, bfHigh, bfPoint }) => H.leanFromOneMinusBf ? { low: weightLb * (1 - bfHigh), high: weightLb * (1 - bfLow), point: bfPoint == null ? undefined : weightLb * (1 - bfPoint), label: bfPoint == null ? "midpoint" : "point" } : { low: weightLb * bfLow, high: weightLb * bfHigh, point: weightLb * bfPoint },
    logSession: ({ date, sets }) => { const r = commit("session-set", "session", { sets: { value: sets.length, unit: "set" } }, { field: "logSession" }); if (!H.loggingNeverPlans) { S.applied.initial = true; S.layer1.plan = { press: { load: sets[0].load, sets: sets.length } }; } S.sessionFacts = (S.sessionFacts || []).concat([{ date, sets }]); return r; },
    proposals: () => (opts.emptyAccount && S.sessionFacts && !S.applied.initial) ? [{ kind: "INITIAL_PLAN", choices: [{ id: "from-session", label: "Start from today's session", selected: false }, { id: "no-plan", label: "No accepted training plan yet", selected: false }] }] : layer2().proposals,
    acceptInitialPlan: (choiceId) => { S.applied.initial = true; S.layer1.plan = { source: choiceId }; last.planProvenance = "consented"; },
    dayFacts: (date) => { const logged = (opts.loggedIntake || []).find((x) => x.date === date); if (logged) return { intake: logged.kcal, intakeState: "ATHLETE_LOGGED", op_id: logged.op_id }; if (!H.presenceLaw) return { intake: (last.plan && last.plan.calories) || 2200, intakeState: "ASSUMED" }; return { intakeState: "ABSENT" }; },
    maintenanceInputs: () => { const days = opts.maintenanceDays || ["2026-09-01", "2026-09-02", "2026-09-03"]; return days.map((d) => { const f = api.dayFacts(d); return f.intakeState === "ATHLETE_LOGGED" ? { date: d, intake: f.intake, source: "ATHLETE_LOGGED", op_id: f.op_id } : (H.presenceLaw ? { date: d, source: "ABSENT" } : { date: d, intake: 2200, source: "DERIVED" }); }); },
    sessionsFromDevices: (list) => { S.sessions = list.map((s) => ({ ...s })); }, ambiguity,
    resolveAmbiguity: (decision) => { if (!H.partitionComplete) { S.resolved = { kind: "PARTITION", blocks: decision.blocks.slice(0, 1), basis: decision.basis, generation: decision.generation }; return S.resolved; } const all = S.sessions.map((s) => s.start).sort(); const covered = [].concat(...decision.blocks).sort(); if (canonicalEncode(all) !== canonicalEncode(covered) || !decision.basis || decision.generation !== 1) return { refused: true, reason: "not a complete partition of the component" }; S.resolved = { kind: "PARTITION", blocks: decision.blocks.map((b) => b.slice().sort()).sort(), basis: decision.basis, generation: decision.generation }; return S.resolved; },
    fieldValue: (name) => S.fields[name],
    issue: (proposal, accepted, instance) => { S.issued[proposal.id] = { accepted, instance }; }, issuedInstance: (id) => S.issued[id] && S.issued[id].instance,
    conflictSuspend: (txn, fallback) => { if (H.conflictSuspend) { S.suspended.p1 = txn; S.suspended.fallback = fallback; } else { S.layer1.plan = {}; S.history = [{ txn, copy: "Undone" }]; } },
    rejectedLedger: () => S.rejected.slice(), fixRejected: (op_id, payload) => { const r = api.weighIn(payload); return { newOp: r.op_id, isCorrectionOfRejected: false, differentOpId: r.op_id !== op_id }; },
    retryEligible: (op_id) => S.now >= (S.nextRetryAt[op_id] || 0), commitmentOf: (op) => O.commitmentOf(op, K, COPTS),
    /* state 17 LIVE transition: the standing is lost while durable unsynced entries exist */
    revoke: () => { opts.revoked = true; S.revokedAt = { outbox: S.outbox.length }; return { state: 17, retained: S.outbox.length, promiseSync: false, copy: "This phone was removed from your account — sign in to re-enrol it" }; },
    outboxRetained: () => S.outbox.length,
    /* state 11: authentication expired on a still-enrolled device — logging continues, sync pauses */
    signInRequired: () => { opts.signInRequired = true; }, syncStatus: () => (opts.signInRequired ? { paused: true, line: "Sign in to sync" } : { paused: !online.v, line: online.v ? "" : "" }),
    /* state 12/18: storage loss → integrity check → restore flow */
    storageLost: (o = {}) => { S.lost = { ledgerSurvived: !!o.ledgerSurvived, evicted: o.evicted || S.outbox.length }; opts.restoreRequired = true; S.ops = []; if (!o.ledgerSurvived) S.outbox = []; },
    restoreFlow: () => { if (!opts.restoreRequired) return { step: "NONE" }; const decl = S.lost && S.lost.ledgerSurvived ? { unsyncedLostCount: S.lost.evicted, copy: S.lost.evicted + " unsynced entr" + (S.lost.evicted === 1 ? "y was" : "ies were") + " lost on this phone" } : { unsyncedLostCount: null, copy: "Earned can't tell whether unsynced entries were lost on this phone" }; return { step: "RESTORE_REQUIRED", paintsAthleteData: false, presentedAsFirstUse: !H.state18Integrity, sequence: ["restore required", "sign in", "restoring", "restored | failed <reason>"], ...decl }; },
    /* state 13: background kill — the face is rebuilt from durable operations only */
    resumeAfterKill: (o = {}) => { const sets = S.ops.filter((x) => x.kind === "session-set"); const last = sets[sets.length - 1]; const line = last ? "Last saved: Set " + sets.length + " of " + (last.payload && last.payload.lift ? last.payload.lift.value || last.payload.lift : "Press") + "." : "No sets saved yet."; const draft = o.durableDraftMarker ? "An unfinished Set " + (sets.length + 1) + " entry was not saved." : (H.state13NoGhost ? null : "An unfinished Set " + (sets.length + 1) + " entry was not saved."); return { line, draftLine: draft, ghost: false }; },
    /* state 10: no accepted plan may exist before consent */
    acceptedPlanTransactions: () => (H.hiddenPlanLeak && opts.hiddenAcceptedPlan && !S.applied.initial) ? [{ hidden: true, plan: opts.hiddenAcceptedPlan }] : (S.applied.initial ? [{ plan: S.layer1.plan, provenance: last.planProvenance || "consented" }] : []),
    /* state 8: the client derives the issuance INSTANCE from the stored offer content, never from a local counter */
    deriveInstance: (offer) => H.instanceFromContent ? "inst-" + O.hmac("instance", O.canonicalEncode({ f: offer.proposal_family_id, g: offer.evidence_generation, o: offer.offer_digest })).slice(0, 12) : "inst-" + (++S.instCounter || (S.instCounter = 1)),
    /* state 5: fallback derived from complete-group plan provenance */
    planHistory: (txns) => { S.planHistory = txns.map((t) => ({ ...t })); },
    fallbackBefore: (txnId) => { const hist = S.planHistory || []; const idx = hist.findIndex((t) => t.txn_id === txnId); if (idx < 0) return null; if (!H.fallbackFromProvenance) return { plan: {}, source: "no accepted plan" }; const suspended = new Set([txnId]); const proj = {}; for (let i = 0; i < hist.length; i++) { const t = hist[i]; if (i === idx) continue; for (const m of t.members) { const introducedBySuspended = m.provenance === "inherited" && (t.parents || []).some((p) => suspended.has(p)) && hist[idx].members.some((x) => x.field === m.field); if (introducedBySuspended) continue; proj[m.field] = m.value; } } return { plan: proj, source: "effective complete projection immediately before " + txnId, excluded: hist.filter((t, i) => i !== idx && (t.parents || []).includes(txnId)).flatMap((t) => t.members.filter((m) => m.provenance === "inherited").map((m) => m.field)) }; },
    /* state 14 deeper: candidate edges, generations, per-block basis, collisions, gates */
    candidateComponent: (starts) => { const sorted = starts.slice().sort((a, b) => (a.start < b.start ? -1 : 1)); const adj = (x, y) => { if (!H.candidateEdge) return true; const slotOk = (x.slot && y.slot && x.slot === y.slot) || (x.slot === "AD_HOC" && y.slot === "AD_HOC"); const d1 = Date.parse(x.date), d2 = Date.parse(y.date); const days = Math.abs(d1 - d2) / 86400000; const skew = days === 1 && ((x.time >= "23:00" && y.time <= "01:00") || (y.time >= "23:00" && x.time <= "01:00")); return slotOk && (days === 0 || skew); }; const comps = []; for (const s of sorted) { let placed = null; for (const c of comps) if (c.some((m) => adj(m, s))) { placed = c; break; } if (placed) placed.push(s); else comps.push([s]); } return comps.map((c) => ({ members: c.map((m) => m.start).sort(), generation: 1 })); },
    advanceGeneration: (component, change) => ({ members: component.members.slice(), generation: H.generationAdvances ? component.generation + 1 : component.generation, supersedesPending: H.generationAdvances, change }),
    resolveSameWorkout: (o) => { const starts = o.starts; const bases = new Set(starts.map((s) => JSON.stringify(s.basis))); const governing = bases.size === 1 ? starts[0].basis : (o.selectedBasis || null); if (bases.size > 1 && !o.selectedBasis) return { needsBasis: true, choices: [...bases].map((b) => JSON.parse(b)), planMutated: false }; return { governingBasis: governing, planMutated: false, interpretsSession: true }; },
    resolveCollisions: (o) => { const classes = o.duplicateClasses || []; const distinct = o.distinctAttempts || []; const canonical = classes.map((cls) => cls.slice().sort()[0]); const slots = distinct.map((d, i) => ({ set: d, slot: 100 + i })); const unresolved = (o.pending || 0) > 0; const bearing = !unresolved && (H.gatesAfterCollision ? (o.gates ? Object.values(o.gates).every(Boolean) : true) : true); return { canonical: H.collisionCanonical ? canonical : classes.flat(), slots, progressionBearing: bearing, deleted: 0, rewritten: 0, history: bearing ? "Sets from two devices were combined." : null }; },
    conflictFace: (c) => { const N = c.alternatives.length + 1; const dev = (d) => (d === "phone" ? "this phone" : d === "ipad" ? "your iPad" : d); if (!H.conflictCopyExact) return { copy: `Version from ${dev(c.usingDevice)} arrived first. Using it.`, actions: [] }; return { copy: `Earned found ${N} current versions of ${c.lift}'s plan. It is using ${c.using} for now. ${N - 1} alternative${N - 1 === 1 ? " is" : "s are"} in History.`, actions: N === 2 ? [`Use ${c.alternatives[0]} instead`] : [`Review ${N - 1} alternatives`] }; },
    _S: S,
  };
  return api;
}
module.exports = { create };
