'use strict';
// Pure browser-safe verification. No signer, storage callbacks, nonce mutation,
// implicit time proof or positive permission marker is exported here.
const C=require('./codec.cjs'),P=require('./project.cjs');
const {createPublicVerifier,decodeSignature}=require('../public-client.cjs');
const denied=(code='INVALID_R1_PROOF')=>C.fail(code);
const check=(ok,code)=>{if(!ok)denied(code);};
const own=x=>C.parse(C.encode(x));
const maxOuter=Math.ceil(C.LIMITS.payload*4/3)+4096;
const utc=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(Date.parse(s)).toISOString()===(s.includes('.')?s:s.replace('Z','.000Z'));
function createR1Verifier({keys,subtle}={}){
  const publicVerifier=createPublicVerifier({keys,subtle});
  function context(expected){check(C.object(expected));const e=own(expected);check(C.digestValue(e.nonce)&&C.digestValue(e.basisDigest)&&C.safe(e.sessionEpoch),'EXPECTED_CONTEXT_REQUIRED');return e;}
  async function signed(record,domain,fields){C.exact(record,[...fields,'authority_signature'],{ordered:true});check(record.profile===domain&&decodeSignature(record.authority_signature)?.kid===record.key_epoch,'SIGNATURE_EPOCH');check(await publicVerifier.verifyRecord(record,domain),'SIGNATURE_INVALID');}
  function repeatedScope(record,e){check(record.nonce===e.nonce,'NONCE_MISMATCH');check(C.digestValue(record.scope_digest)&&record.scope_digest===e.scopeDigest,'SCOPE_MISMATCH');}
  async function lease(l){check(C.object(l)&&C.nonempty(l.athlete_id)&&C.nonempty(l.device_id)&&C.nonempty(l.lease_id)&&C.safe(l.schema_version,1)&&Array.isArray(l.range)&&l.range.length===2&&l.range.every(n=>C.safe(n,1))&&l.range[1]>=l.range[0]&&utc(l.not_before)&&utc(l.not_after)&&Date.parse(l.not_before)<=Date.parse(l.not_after),'LEASE_INVALID');check(await publicVerifier.verifyLease(l),'LEASE_SIGNATURE');}
  function standing(s){C.exact(s,C.FIELDS.standing,{ordered:true});check(C.safe(s.account_epoch,1)&&['ACTIVE','CLOSED'].includes(s.account_state)&&C.nonempty(s.actor_device_id)&&typeof s.actor_revoked==='boolean'&&C.safe(s.creation_epoch,1)&&C.nonempty(s.current_lease_id),'STANDING_INVALID');}
  async function originalRecord(record){C.exact(record,['operation_row','history_rows','log_row'],{ordered:true});const r=P.readRow(record.operation_row);check(record.operation_row.collection==='operations'&&C.object(r.op)&&r.op.op_id===record.operation_row.row_id&&C.object(r.disposition)&&C.safe(r.historyCount,1)&&Array.isArray(record.history_rows)&&record.history_rows.length===r.historyCount,'RETAINED_INTEGRITY');const o=r.op;check(r.commitment===o.canonical_content_commitment,'RETAINED_INTEGRITY');
    for(let i=0;i<record.history_rows.length;i++){const dto=record.history_rows[i],d=P.readRow(dto);check(dto.collection==='history'&&dto.row_id===JSON.stringify([o.op_id,i+1])&&d.op_id===o.op_id&&d.device_id===o.device_id&&d.device_seq===o.device_seq&&d.canonical_content_commitment===r.commitment&&P.STATUSES.has(d.status),'RETAINED_INTEGRITY');check(await publicVerifier.verifyDisposition(d),'DISPOSITION_SIGNATURE');if(i<r.historyCount-1)check(d.status==='WAITING','RETAINED_INTEGRITY');else check(C.fullEqual(d,r.disposition),'RETAINED_INTEGRITY');}
    if(r.disposition.status==='ACCEPTED'){check(record.log_row&&record.log_row.collection==='log','RETAINED_INTEGRITY');const l=P.readRow(record.log_row);check(C.safe(l.seq,1)&&String(l.seq)===record.log_row.row_id&&l.seq===r.disposition.athlete_log_seq&&l.accepted_at===r.disposition.accepted_at&&C.fullEqual(l.op,o),'RETAINED_INTEGRITY');}else check(record.log_row===null,'RETAINED_INTEGRITY');return r;
  }
  async function manifest(raw,e){const m=C.parse(raw,C.LIMITS.request);await signed(m,C.DOMAINS.manifest,C.FIELDS.manifest);repeatedScope(m,e);check(C.digestValue(e.contextId)&&m.context_id===e.contextId&&C.digestValue(e.requestDigest)&&m.request_digest===e.requestDigest,'REQUEST_MISMATCH');check(C.digestValue(m.snapshot_id)&&C.digestValue(m.payload_digest)&&C.digestValue(m.coverage_digest)&&C.safe(m.payload_bytes,1)&&m.payload_bytes<=C.LIMITS.payload&&m.page_bytes===C.LIMITS.page&&m.page_count===Math.ceil(m.payload_bytes/C.LIMITS.page)&&m.page_count<=C.LIMITS.pages,'MANIFEST_SHAPE');return m;}
  async function page(raw,manifestRaw,e){const m=await manifest(manifestRaw,e),p=C.parse(raw,C.LIMITS.request);await signed(p,C.DOMAINS.page,C.FIELDS.page);check(p.manifest_digest===C.hash('manifest',manifestRaw)&&C.safe(p.index)&&p.index<m.page_count&&p.offset===p.index*C.LIMITS.page&&p.bytes===Math.min(C.LIMITS.page,m.payload_bytes-p.offset),'PAGE_BINDING');const data=C.decode64(p.data_b64,C.LIMITS.page);check(data.length===p.bytes&&C.hash('page',data)===p.page_digest,'PAGE_DIGEST');return p;}
  const safe=fn=>async(...args)=>{try{return {verified:true,value:await fn(...args)};}catch(e){return {verified:false,code:e.code||'INVALID_R1_PROOF'};}};
  return Object.freeze({
    verifyManifest:safe(async(input,expected)=>{const raw=C.bytes(input),e=context(expected);return manifest(raw,e);}),
    verifyPage:safe(async(input,manifestInput,expected)=>{const raw=C.bytes(input),mr=C.bytes(manifestInput),e=context(expected);return page(raw,mr,e);}),
    verifyResult:safe(async(input,expected)=>{const raw=C.bytes(input),e=context(expected),r=C.parse(raw,maxOuter);check([C.DOMAINS.enrollment,C.DOMAINS.renewal,C.DOMAINS.replay].includes(e.profile),'RESULT_PROFILE');await signed(r,e.profile,C.FIELDS.result);check(r.nonce===e.nonce&&C.digestValue(e.intentDigest)&&r.intent_digest===e.intentDigest,'RESULT_CORRESPONDENCE');const data=C.decode64(r.data_b64,C.LIMITS.payload);check(C.safe(r.payload_bytes,1)&&data.length===r.payload_bytes&&C.hash('result',data)===r.payload_digest,'RESULT_DIGEST');const p=C.parse(data);let derivedScope=e.scopeDigest;
      if(e.profile===C.DOMAINS.enrollment||e.profile===C.DOMAINS.renewal){C.exact(p,['issuance','current_standing'],{ordered:true});const x=p.issuance;C.exact(x,['lease','lease_bytes_b64','issuer_profile','issue_ordinal','issuance_intent_digest','account_epoch','creation_epoch'],{ordered:true});check(x.issuer_profile===C.PROFILE&&C.safe(x.issue_ordinal,1)&&C.safe(x.creation_epoch,1)&&C.safe(x.account_epoch,1)&&x.issuance_intent_digest===e.intentDigest,'ISSUANCE_INVALID');const l=C.parse(C.decode64(x.lease_bytes_b64,C.LIMITS.request));check(C.fullEqual(l,x.lease),'LEASE_BYTES');await lease(l);standing(p.current_standing);check(p.current_standing.actor_device_id===l.device_id&&p.current_standing.account_epoch>=x.account_epoch&&p.current_standing.creation_epoch>=x.creation_epoch,'ISSUANCE_STANDING');if(p.current_standing.creation_epoch===x.creation_epoch)check(p.current_standing.current_lease_id===l.lease_id,'ISSUANCE_STANDING');if(e.athleteId!==undefined)check(l.athlete_id===e.athleteId,'SCOPE_MISMATCH');if(e.actorDeviceId!==undefined)check(l.device_id===e.actorDeviceId,'SCOPE_MISMATCH');if(e.profile===C.DOMAINS.enrollment){check(x.issue_ordinal===1&&x.creation_epoch===1,'ENROLLMENT_NOT_FIRST');derivedScope=C.scopeDigest({issuer:e.issuer,subject:e.subject,origin:e.origin,athleteId:l.athlete_id,actorDeviceId:l.device_id});}else check(C.nonempty(e.athleteId)&&C.nonempty(e.actorDeviceId),'EXPECTED_SCOPE_REQUIRED');}
      else{C.exact(p,['original_envelope_digest','outcome','disposition_bytes_b64','authority_record','current_standing'],{ordered:true});check(C.digestValue(e.originalEnvelopeDigest)&&p.original_envelope_digest===e.originalEnvelopeDigest&&p.original_envelope_digest===e.intentDigest,'REPLAY_CORRESPONDENCE');standing(p.current_standing);check(p.current_standing.actor_device_id===e.actorDeviceId,'SCOPE_MISMATCH');check(C.object(e.originalOperation)&&e.originalOperation.athlete_id===e.athleteId,'EXPECTED_OPERATION_REQUIRED');const d=C.parse(C.decode64(p.disposition_bytes_b64,C.LIMITS.request));check(await publicVerifier.verifyDisposition(d),'DISPOSITION_SIGNATURE');const requestedRaw=C.decode64(e.originalEnvelopeB64,C.LIMITS.request),o=C.parse(requestedRaw);check(C.hash('operation',requestedRaw)===e.originalEnvelopeDigest&&C.fullEqual(o,e.originalOperation),'EXPECTED_OPERATION_BYTES');check(d.op_id===o.op_id&&d.canonical_content_commitment===o.canonical_content_commitment,'REPLAY_DISPOSITION');
        if(p.outcome==='DISPOSITION'){check(p.authority_record===null&&P.STATUSES.has(d.status)&&d.device_id===o.device_id&&d.device_seq===o.device_seq,'REPLAY_OUTCOME');}
        else{check(p.outcome==='ENVELOPE_MISMATCH','REPLAY_OUTCOME');const rr=await originalRecord(p.authority_record);check(C.fullEqual(rr.disposition,d)&&rr.op.athlete_id===e.athleteId&&rr.op.op_id===o.op_id&&rr.commitment===o.canonical_content_commitment&&!C.fullEqual(rr.op,o),'REPLAY_MISMATCH');}
      }
      check(C.digestValue(derivedScope)&&r.scope_digest===derivedScope,'SCOPE_MISMATCH');return {envelope:r,payload:p,payloadBytes:new Uint8Array(data)};
    }),
    assemble:safe(async(manifestInput,pageInputs,requestInput,expected)=>{const mr=C.bytes(manifestInput),requestRaw=C.bytes(requestInput),e=context(expected);const inputs=pageInputs instanceof Map?[...pageInputs.values()]:Array.isArray(pageInputs)?pageInputs:null;check(inputs&&inputs.length<=C.LIMITS.pages*3,'PAGE_INVENTORY');const copies=inputs.map(C.bytes),req=C.decodeRequest(requestRaw);check(e.requestDigest===C.hash('request',requestRaw)&&req.nonce===e.nonce&&req.context_id===e.contextId&&req.mode===e.mode,'REQUEST_MISMATCH');const m=await manifest(mr,e),seen=new Map();
      for(const raw of copies){const p=await page(raw,mr,e),old=seen.get(p.index);if(old){for(const k of ['profile','manifest_digest','index','offset','bytes','page_digest','data_b64'])check(old[k]===p[k],'CONFLICTING_PAGE');}else seen.set(p.index,p);}
      check(seen.size===m.page_count,'MISSING_PAGE');const joined=new Uint8Array(m.payload_bytes);for(let i=0;i<m.page_count;i++){const p=seen.get(i);check(p,'MISSING_PAGE');joined.set(C.decode64(p.data_b64,C.LIMITS.page),p.offset);}check(C.hash('payload',joined)===m.payload_digest,'PAYLOAD_DIGEST');
      const expectedScope={athlete_id:e.athleteId,actor_device_id:e.actorDeviceId,mode:e.mode,scope_digest:e.scopeDigest};const ps=P.payloadState(joined,expectedScope),fresh=P.project({rawRows:ps.rawRows,athleteId:e.athleteId,actorDeviceId:e.actorDeviceId,request:req,scopeDigest:e.scopeDigest});check(C.sameBytes(fresh.payloadBytes,joined)&&fresh.coverageDigest===m.coverage_digest,'RETAINED_PROJECTION');
      for(const entry of ps.state.maps.get('issuedLeases').values())await lease(entry.value.lease);for(const entry of ps.state.maps.get('history').values())check(await publicVerifier.verifyDisposition(entry.value),'DISPOSITION_SIGNATURE');
      return {payload:ps.payload,payloadBytes:new Uint8Array(joined)};
    }),
  });
}
module.exports={createR1Verifier};
