import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
const sha=(b,kind='sha256',encoding='hex')=>createHash(kind).update(b).digest(encoding),base='3bfed63febef002b8540d6ff3c56e19d08368711';
if(execFileSync('git',['write-tree'],{encoding:'utf8'}).trim()!==execFileSync('git',['rev-parse',`${base}^{tree}`],{encoding:'utf8'}).trim())throw Error('Incomplete index');
for(const [file,bytes,hash] of [['rebuild/conform/engines/build-engines.mjs',3791,'19f7520f329151eaf8b113e6cde4019113fbc0774e06709d0eeaab4f50bc09fb'],['package.json',654,'a201428565aae9426d47a2f42c027cce9d9aaae46775f91029e271d0eb10195c'],['package-lock.json',35020,'b745ab5e0c982ef61db59fc0b7df5deb0f540af9e0e59a015a11443171210608']]){const b=execFileSync('git',['show',`${base}:${file}`]);if(b.length!==bytes||sha(b)!==hash)throw Error('Input identity '+file);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,b);execFileSync('git',['update-index','--no-skip-worktree','--',file]);}
const bar=execFileSync('git',['show','8e988045a586d599d316a53c5c893ccf324d2a00:rebuild/lanes/astra/FROZEN-BUILD-SETUP-GO.md']);if(sha(bar)!=='1854aec90807c5f0f0ff85b99423084442a342f47cbd55646ab2d1c969ea4fde')throw Error('Bar identity');
const exe=fs.readFileSync('.tmp/frozen-build-setup/runtime/node.exe'),runtimeHash=sha(exe);if(runtimeHash!=='0d0f5e39f9f3d9587bc19f73eab3c2c9c4903fd02d6dbf9c853dd81b3d95fad4'||!fs.readFileSync('.tmp/frozen-build-setup/runtime/SHASUMS256.txt','utf8').includes(runtimeHash+'  win-x64/node.exe'))throw Error('Runtime identity');
const lock=JSON.parse(fs.readFileSync('package-lock.json')),packages=[];
for(const name of ['esbuild','@esbuild/win32-x64']){const pin=lock.packages['node_modules/'+name];if(pin.version!=='0.28.1')throw Error('Unexpected version');const response=await fetch(pin.resolved);if(!response.ok)throw Error('Download status');const b=Buffer.from(await response.arrayBuffer());if('sha512-'+sha(b,'sha512','base64')!==pin.integrity)throw Error('Integrity');const tarball=path.resolve('.tmp/frozen-build-setup/'+name.split('/').at(-1)+'.tgz');fs.writeFileSync(tarball,b);const dest=path.resolve('node_modules',name);fs.mkdirSync(dest,{recursive:true});execFileSync('tar',['-xzf',tarball,'--strip-components=1','-C',dest]);const manifest=JSON.parse(fs.readFileSync(path.join(dest,'package.json')));if(manifest.version!==pin.version||manifest.name!==name)throw Error('Installed identity');packages.push({name,version:pin.version,integrity:pin.integrity,tarballSha256:sha(b)});}
const files=['node_modules/esbuild/lib/main.js','node_modules/esbuild/package.json','node_modules/@esbuild/win32-x64/esbuild.exe','node_modules/@esbuild/win32-x64/package.json'].map(file=>({file,bytes:fs.statSync(file).size,sha256:sha(fs.readFileSync(file))}));fs.writeFileSync('.tmp/frozen-build-setup/dependency-inventory.json',JSON.stringify({node:process.version,runtimeHash,packages,files,scriptsExecuted:false},null,2)+'\n');console.log({node:process.version,packages,files});
