'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{createHash,webcrypto}=require('node:crypto');
const C=require('../reconciliation/codec.cjs'),P=require('../reconciliation/project.cjs'),{createR1Verifier}=require('../reconciliation/verify.cjs'),K=require('../crypto.cjs');
const b64=n=>C.encode64(new Uint8Array(32).fill(n)),copy=x=>JSON.parse(JSON.stringify(x));
function fixture({status='ACCEPTED',padding=0,note='Caf\u00e9'}={}){
  const key=K.generateSigningKey('old'),newKey=K.generateSigningKey('new'),athleteId='athlete-a',actorDeviceId='device-b',rows=[],devices={};
  const push=(collection,row_id,value,pretty=false)=>rows.push({athlete:athleteId,collection,row_id,value:JSON.stringify(value,null,pretty?1:undefined)});
  for(const device of ['device-a','device-b']){const l=K.signLease({athlete_id:athleteId,device_id:device,lease_id:'lease-'+device,range:[1,1048576],not_before:'2026-09-06T00:00:00.000Z',not_after:'2026-10-06T00:00:00.000Z',schema_version:1},key),intent=C.hash('intent',C.bytes(device));devices[device]={lease:l};
    push('deviceIssuance',device,{device_id:device,creation_epoch:1,current_lease_id:l.lease_id,issue_ordinal:1});
    push('issuedLeases',JSON.stringify([device,l.lease_id]),{lease:l,lease_bytes_b64:C.encode64(C.encode(l)),issuer_profile:C.PROFILE,issue_ordinal:1,issuance_intent_digest:intent,account_epoch:1,creation_epoch:1});
    push('enrollmentIntents','intent-'+device,{stable_request_digest:intent,device_id:device,lease_id:l.lease_id});
    push('standingEvents','enrol-'+device,{kind:'DEVICE_ENROLLED',athlete_id:athleteId,device_id:device,account_epoch:1,creation_epoch:1,evidence:{lease_id:l.lease_id}});
  }
  push('accountRegistry','state',{profile:C.PROFILE,account_epoch:1,state:'ACTIVE',history_origin:'PROFILE_GENESIS'});
  push('standingEvents','genesis',{kind:'PROFILE_GENESIS',athlete_id:athleteId,device_id:null,account_epoch:1,creation_epoch:null,evidence:{history_origin:'PROFILE_GENESIS'}});
  const op={op_id:'op-a',athlete_id:athleteId,device_id:'device-a',device_seq:1,device_predecessor_op_id:null,causal_parents:[],kind:'fact',class:'reading',effective:{local_date:'2026-09-06',local_time:'12:00',utc_offset:'-04:00'},schema_version:1,lease_id:'lease-device-a',payload:{lb:{value:100,unit:'lb'},note}};op.canonical_content_commitment=K.commitmentOf(op,'synthetic-identity');
  const d=K.signDisposition({op_id:op.op_id,canonical_content_commitment:op.canonical_content_commitment,device_id:op.device_id,device_seq:1,status,decided_at:'2026-09-06T16:00:00.000Z',...(status==='ACCEPTED'?{athlete_log_seq:1,accepted_at:'2026-09-06T16:00:00.000Z'}:status.startsWith('REJECTED')?{rejection_code:status==='REJECTED'?'LEASE_UNKNOWN':'REJECTED_DEPENDENCY'}:{})},key);
  push('metadata','state',{seq:status==='ACCEPTED'?1:0,devices,initialPlan:padding?{synthetic:'x'.repeat(padding)}:{}});
  push('operations',op.op_id,{op,commitment:op.canonical_content_commitment,disposition:d,historyCount:1},true);push('history',JSON.stringify([op.op_id,1]),d);push('slots',JSON.stringify([op.device_id,1]),{op_id:op.op_id});push('ownership',op.op_id,{present:true});
  if(status==='ACCEPTED'){push('log','1',{seq:1,op,accepted_at:d.accepted_at});push('lastAccepted',op.device_id,{seq:1});}
  const claims=[{claim_id:'query-a',envelope_b64:C.encode64(C.encode(op))}],request={version:'earned/reconcile-request-1m/v1',mode:'ACCOUNT_RECOVERY',nonce:b64(1),context_id:b64(2),claims,requested_lease_ids:[{source_device_id:op.device_id,lease_id:op.lease_id}]};
  const scope={issuer:'https://issuer.invalid',subject:'synthetic-subject',origin:'https://app.invalid',athleteId,actorDeviceId},scopeDigest=C.scopeDigest(scope),requestBytes=C.encode(request),expected={athleteId,actorDeviceId,mode:request.mode,scopeDigest,nonce:request.nonce,contextId:request.context_id,requestDigest:C.hash('request',requestBytes),basisDigest:b64(3),sessionEpoch:1};
  return {key,newKey,rows,op,d,request,requestBytes,scope,scopeDigest,expected,athleteId,actorDeviceId,push};
}
function packet(f,projected=P.project({rawRows:f.rows,athleteId:f.athleteId,actorDeviceId:f.actorDeviceId,request:f.request,scopeDigest:f.scopeDigest})){const u=C.makeManifest({keyEpoch:f.key.kid,scopeDigest:f.scopeDigest,requestBytes:f.requestBytes,snapshotId:b64(4),payloadBytes:projected.payloadBytes,coverage:projected.payload.coverage}),m={...u,authority_signature:K.signatureOver(u,f.key,C.DOMAINS.manifest)},mr=C.encode(m),pages=Array.from({length:m.page_count},(_,index)=>{const p=C.makePage({keyEpoch:f.key.kid,manifestBytes:mr,payloadBytes:projected.payloadBytes,index});return C.encode({...p,authority_signature:K.signatureOver(p,f.key,C.DOMAINS.page)});});return {projected,m,mr,pages};}
const verifier=f=>createR1Verifier({keys:[K.publicKeyOf(f.key),K.publicKeyOf(f.newKey)],subtle:webcrypto.subtle});
test('tagged SHA256 matches independent Node primitive; byte/code-point domains differ',()=>{for(const s of ['','abc','Caf\u00e9','Cafe\u0301','0','-0','1e-22']){const raw=C.bytes(s),expected=createHash('sha256').update(C.TAGS.operation+'\0').update(raw).digest('base64url');assert.equal(C.hash('operation',raw),expected);}assert.notEqual(C.hash('operation',C.bytes('Caf\u00e9')),C.hash('operation',C.bytes('Cafe\u0301')));assert.notEqual(C.hash('operation','abc'),C.hash('payload','abc'));});
for(const s of ['{"a":1,"a":2}','{"a":1,"\\u0061":2}','[1,]','{"a":1,}','01','true false','{"x":NaN}','"\u0001"'])test('strict JSON refuses '+JSON.stringify(s),()=>assert.throws(()=>C.parse(s)));
test('JSON keys preserve order and __proto__ stays data; operation decimals are not control integers',()=>{const p=C.parse('{"z":1,"__proto__":{"x":2},"a":1e-22}');assert.deepEqual(Object.keys(p),['z','__proto__','a']);assert.equal(Object.getPrototypeOf(p),Object.prototype);assert.equal(p.a,1e-22);assert.equal({}.x,undefined);});
test('UTF8 and base64url reject malformed/lossy encodings',()=>{assert.throws(()=>C.parse(new Uint8Array([0xff])));for(const s of ['YQ==','YR','A','a+b/'])assert.throws(()=>C.decode64(s));assert.deepEqual([...C.decode64('YQ')],[97]);});
test('request duplicates, unknown controls and foreign source fail',()=>{const f=fixture();const dup=copy(f.request);dup.claims.push(copy(dup.claims[0]));assert.throws(()=>C.validateRequest(dup));assert.throws(()=>C.validateRouteRequest('/enrol/create',{intent_id:'x',schema_version:1,nonce:b64(1),athlete_id:'foreign'}));const op={...f.op,athlete_id:'foreign'};f.request.claims[0].envelope_b64=C.encode64(C.encode(op));assert.throws(()=>P.project({rawRows:f.rows,...f.scope,request:f.request,scopeDigest:f.scopeDigest}),e=>e.code==='SCOPE_FORBIDDEN');});
test('projection preserves exact persisted JSON bytes and includes requested historical lease',()=>{const f=fixture(),p=packet(f).projected.payload,r=p.retained_rows.find(r=>r.collection==='operations');assert.equal(C.text(C.decode64(r.value_b64)),f.rows.find(r=>r.collection==='operations').value);assert.equal(p.claims[0].outcome,'KNOWN_TERMINAL');assert.equal(p.leases.lookups[0].issued_row.collection,'issuedLeases');});
for(const collection of ['metadata','history','ownership','slots','log','lastAccepted','issuedLeases','deviceIssuance','enrollmentIntents','standingEvents'])test('missing '+collection+' cannot produce complete proof',()=>{const f=fixture();f.rows=f.rows.filter(r=>r.collection!==collection);assert.throws(()=>packet(f));});
test('legacy observed history is not complete; unknown collection fails closed',()=>{for(const mutation of [f=>{const r=f.rows.find(r=>r.collection==='accountRegistry');const v=JSON.parse(r.value);v.history_origin='OBSERVED_CURRENT';r.value=JSON.stringify(v);},f=>f.push('future-secret','x',{secret:'synthetic'})]){const f=fixture();mutation(f);assert.throws(()=>packet(f));}});
test('same canonical commitment but distinct full envelope remains mismatch in every retained state',()=>{for(const status of ['ACCEPTED','WAITING','REJECTED','REJECTED_DEPENDENCY']){const f=fixture({status}),alias=copy(f.op);alias.payload.note='Cafe\u0301';assert.equal(K.commitmentOf(alias,'synthetic-identity'),f.op.canonical_content_commitment);f.request.claims[0].envelope_b64=C.encode64(C.encode(alias));const p=P.project({rawRows:f.rows,...f.scope,request:f.request,scopeDigest:f.scopeDigest});assert.equal(p.payload.claims[0].outcome,'ENVELOPE_MISMATCH');assert.equal(p.payload.claims[0].envelope_match,false);assert.equal(p.payload.claims[0].history_rows.length,1);}});
test('full-inventory local matcher is synchronous, unverified and rejects duplicate/foreign input',()=>{const f=fixture(),p=packet(f).projected;const s=p.payload.scope,r=P.matchRetainedClaims(p.payloadBytes,f.request.claims,s);assert.equal(r.ok,true);assert.equal(r.then,undefined);assert.equal(r.verified,undefined);assert.equal(P.matchRetainedClaims(p.payloadBytes,[...f.request.claims,...f.request.claims],s).ok,false);assert.equal(P.matchRetainedClaims(p.payloadBytes,f.request.claims,{...s,athlete_id:'foreign'}).ok,false);});
test('complete signed multi-page proof is accepted without sinks',async()=>{const f=fixture({padding:40000}),p=packet(f),v=verifier(f);assert(p.pages.length>1);assert.equal((await v.verifyManifest(p.mr,f.expected)).verified,true);assert.equal((await v.verifyPage(p.pages[0],p.mr,f.expected)).value.index,0);const a=await v.assemble(p.mr,p.pages.slice().reverse(),f.requestBytes,f.expected);assert.equal(a.verified,true,JSON.stringify(a));assert(C.sameBytes(a.value.payloadBytes,p.projected.payloadBytes));});
test('missing page, nonce/basis omissions and substituted request refuse',async()=>{const f=fixture({padding:40000}),p=packet(f),v=verifier(f);assert.equal((await v.assemble(p.mr,p.pages.slice(1),f.requestBytes,f.expected)).verified,false);assert.equal((await v.verifyManifest(p.mr,{...f.expected,nonce:b64(9)})).verified,false);assert.equal((await v.verifyManifest(p.mr,{...f.expected,basisDigest:undefined})).verified,false);assert.equal((await v.assemble(p.mr,p.pages,C.encode({...f.request,claims:[]}),f.expected)).verified,false);});
test('valid duplicate pages signed again or with another pinned epoch assemble once',async()=>{const f=fixture(),p=packet(f),q=C.parse(p.pages[0]);q.key_epoch=f.newKey.kid;delete q.authority_signature;q.authority_signature=K.signatureOver(q,f.newKey,C.DOMAINS.page);assert.equal((await verifier(f).assemble(p.mr,[...p.pages,C.encode(q)],f.requestBytes,f.expected)).verified,true);});
test('new valid signature cannot conceal changed page bytes or omitted retained fact',async()=>{const f=fixture(),p=packet(f),q=C.parse(p.pages[0]);q.data_b64=C.encode64(C.bytes('different'));q.bytes=9;q.page_digest=C.hash('page','different');delete q.authority_signature;q.authority_signature=K.signatureOver(q,f.key,C.DOMAINS.page);assert.equal((await verifier(f).assemble(p.mr,[C.encode(q)],f.requestBytes,f.expected)).verified,false);const payload=copy(p.projected.payload);payload.retained_rows=payload.retained_rows.filter(r=>r.collection!=='ownership');const forged=packet(f,{payload,payloadBytes:C.encode(payload)});assert.equal((await verifier(f).assemble(forged.mr,forged.pages,f.requestBytes,f.expected)).verified,false);});
test('signature key epoch, domain, unknown keys and private verification keys refuse',async()=>{const f=fixture(),p=packet(f),m={...p.m,key_epoch:f.newKey.kid};assert.equal((await verifier(f).verifyManifest(C.encode(m),f.expected)).verified,false);m.authority_signature=K.signatureOver(m,f.newKey,'earned/reconciliation-manifest/v1');assert.equal((await verifier(f).verifyManifest(C.encode(m),f.expected)).verified,false);assert.throws(()=>createR1Verifier({keys:[f.key],subtle:webcrypto.subtle}));});
test('verifier owns byte copies before asynchronous crypto yields',async()=>{const f=fixture(),p=packet(f),raw=new Uint8Array(p.mr),promise=verifier(f).verifyManifest(raw,f.expected);raw.fill(0);assert.equal((await promise).verified,true);});
test('enrollment derives authenticated scope and validates embedded lease/current historical pointer distinction',async()=>{const f=fixture(),x=JSON.parse(f.rows.find(r=>r.collection==='issuedLeases'&&r.row_id.includes('device-b')).value),payload={issuance:x,current_standing:{account_epoch:1,account_state:'ACTIVE',actor_device_id:'device-b',actor_revoked:false,creation_epoch:2,current_lease_id:'newer-lease'}},u=C.makeResult({keyEpoch:f.key.kid,profile:C.DOMAINS.enrollment,scopeDigest:f.scopeDigest,nonce:b64(1),intentDigest:x.issuance_intent_digest,payload}),signed={...u,authority_signature:K.signatureOver(u,f.key,C.DOMAINS.enrollment)},e={...f.expected,...f.scope,profile:C.DOMAINS.enrollment,intentDigest:x.issuance_intent_digest};assert.equal((await verifier(f).verifyResult(C.encode(signed),e)).verified,true);assert.equal((await verifier(f).verifyResult(C.encode(signed),{...e,subject:'other'})).verified,false);});
test('browser bundle imports no Node crypto/private signing boundary',async()=>{const esbuild=require('esbuild');const result=await esbuild.build({entryPoints:[require.resolve('../reconciliation/verify.cjs')],bundle:true,platform:'browser',format:'esm',write:false,metafile:true,logLevel:'silent'});const imports=Object.keys(result.metafile.inputs);assert(!imports.some(p=>p.endsWith('/w5/crypto.cjs')));assert(!result.outputFiles[0].text.includes('require("node:'));});
test('tracked independent byte vectors and closed contract remain executable',()=>{const f=require('../fixtures/reconciliation-v1.json'),contract=require('../reconciliation/contract-v2.json');for(const v of f.vectors){assert.equal(Buffer.from(C.bytes(v.text)).toString('hex'),v.utf8Hex);assert.equal(C.encode64(C.bytes(v.text)),v.base64url);assert.equal(C.hash('operation',C.bytes(v.text)),v.operationDigest);}assert.deepEqual(contract.fields,C.FIELDS);assert.deepEqual(contract.collections,P.COLLECTIONS);assert.deepEqual(contract.limits,C.LIMITS);});
test('known commitment with edited same-account source/sequence cannot masquerade as terminal replay',()=>{const f=fixture();for(const mutation of [{device_seq:2},{device_id:'device-b',lease_id:'lease-device-b'}]){const op={...f.op,...mutation},req=copy(f.request);req.claims[0].envelope_b64=C.encode64(C.encode(op));const p=P.project({rawRows:f.rows,...f.scope,request:req,scopeDigest:f.scopeDigest});assert.equal(p.payload.claims[0].outcome,'ENVELOPE_MISMATCH');assert.equal(P.readRow(p.payload.claims[0].stored_operation_row).op.device_id,'device-a');}});
test('rejected contender outside incumbent slot history is retained and matched',()=>{const f=fixture(),op={...f.op,op_id:'contender'};op.canonical_content_commitment=K.commitmentOf(op,'synthetic-identity');const d=K.signDisposition({op_id:op.op_id,canonical_content_commitment:op.canonical_content_commitment,device_id:op.device_id,device_seq:op.device_seq,status:'REJECTED',rejection_code:'DEVICE_SEQ_REUSE',decided_at:'2026-09-06T16:00:00.000Z'},f.key);f.push('operations',op.op_id,{op,commitment:op.canonical_content_commitment,disposition:d,historyCount:1});f.push('history',JSON.stringify([op.op_id,1]),d);f.push('ownership',op.op_id,{present:true});f.request.claims.push({claim_id:'contender-claim',envelope_b64:C.encode64(C.encode(op))});const p=packet(f).projected.payload;assert.equal(p.claims[1].outcome,'KNOWN_TERMINAL');assert.equal(P.readRow(p.claims[1].slot_incumbent).op_id,'op-a');assert.equal(P.readRow(p.claims[1].history_rows[0]).rejection_code,'DEVICE_SEQ_REUSE');});
test('number alias and signed zero compare full parsed values without canonical rounding',()=>{assert.equal(C.fullEqual({x:1e-22},{x:0}),false);assert.equal(C.fullEqual({x:-0},{x:0}),false);assert.equal(C.fullEqual({a:1,b:2},{b:2,a:1}),true);assert.equal(C.fullEqual([1,2],[2,1]),false);});
test('old envelope nesting is not silently restricted to an invented control depth',()=>{const raw='['.repeat(300)+'0'+']'.repeat(300);assert.equal(Array.isArray(C.parse(raw)),true);});
module.exports={fixture,packet};
