import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),dir='.tmp/frozen-author-reconciliation';
const custody=JSON.parse(fs.readFileSync(dir+'/archive-verification.json')),manifest=JSON.parse(fs.readFileSync('.tmp/FROZEN-BUILD-SETUP-REVIEW-INPUTS.json'));
const final=JSON.parse(fs.readFileSync(dir+'/archive/final-inventory.json'));for(const x of final){const target=x.file.startsWith('.tmp/frozen-build-setup/')?dir+'/archive/'+path.basename(x.file):x.file;const b=fs.readFileSync(target);if(b.length!==x.bytes||sha(b)!==x.sha256)throw Error('Author final inventory mismatch');}
const authorDeps=JSON.parse(fs.readFileSync(dir+'/archive/dependency-inventory.json')),ownDeps=JSON.parse(fs.readFileSync('.tmp/d2-frozen-dependency-inventory.json'));
if(authorDeps.runtimeHash!==ownDeps.nodeSHA256)throw Error('Runtime disagreement');for(const e of authorDeps.packages){const d=ownDeps.installed.find(x=>x.name===e.name);if(!d||d.version!==e.version||d.integrity!==e.integrity||d.archiveSHA256!==e.tarballSha256)throw Error('Package disagreement');}for(const x of authorDeps.files){const b=fs.readFileSync(x.file);if(b.length!==x.bytes||sha(b)!==x.sha256)throw Error('Loader/service file disagreement');}
function tap(name){const s=fs.readFileSync(dir+'/archive/'+name,'utf8'),x={file:name,sha256:sha(Buffer.from(s))};for(const k of ['tests','pass','fail','cancelled','skipped','todo'])x[k]=Number(s.match(new RegExp('^# '+k+' (\\d+)$','m'))?.[1]);x.assertionFailures=(s.match(/^  code: 'ERR_ASSERTION'$/gm)||[]).length;x.failures=s.split(/(?=^# Subtest:)/m).filter(b=>/^not ok /m.test(b)).map(b=>({name:b.match(/^# Subtest: (.+)$/m)?.[1]||'entry failed before cases',hasENOENT:b.includes('ENOENT'),hasEEXIST:b.includes('EEXIST'),hasModuleResolution:b.includes('Could not resolve')||b.includes('Cannot find module')}));return x;}
const stages=['first-public.tap','public-after-fixture-path.tap','public-after-race-fix.tap','final-public.tap'].map(tap);
const failures=fs.readFileSync(dir+'/archive/public-after-fixture-path.tap','utf8');if(!failures.includes('EEXIST')||!failures.includes('Windows-safe')||!failures.includes('concurrent'))throw Error('Expected distinct author intermediate failures absent');
const reversals=JSON.parse(fs.readFileSync(dir+'/archive/reversals.json')).map(r=>{const failed=tap('reversal-'+r.name+'.tap'),restored=tap('restored-'+r.name+'.tap');if(r.before!==manifest.files[0].sha256||r.before!==r.restored||failed.fail!==1||failed.assertionFailures!==1||restored.pass!==1||restored.fail!==0)throw Error('Unproved author reversal');return {...r,failed,restored,reexecutedByD2:false};});
const actualR1=JSON.parse(fs.readFileSync('.tmp/d2-frozen-first-evidence.json')).r1;
const evidence={candidate:manifest.candidate,source:manifest.testedSource,firstIndependentVerdict:'561d3b2779decaaa7f5b8e8bca21f1cbdd9a08ad',firstVerdictSentBeforeAuthorRead:true,readAt:new Date().toISOString(),report:JSON.parse(fs.readFileSync(dir+'/first-read.json')).inputs[0],archive:custody.archive,copiedFiles:17,copiedBytes:custody.copiedBytes,archiveChangedPaths:19,authorFinalInputAndRuntimeMatches:true,authorStages:stages,authorReversals:reversals,authorReplaySourcesRead:['reversals.mjs','setup.mjs'],authorSourceExecuted:false,reviewerR1:actualR1,verdict:'REJECT',openFindings:['R1 builder module hardlink bypass remains'],scopeReconciliation:['Original historical builder defects were PM source findings, not executed real-history failures.','E wrong-owner helper path and non-ASCII fs.cpSync fixture paths are setup failures; EEXIST scratch-parent concurrency is a repaired product failure.','E claims hard-linked files refuse; D2 F2 proves this omits actual builder module.','E same-ref overlap and D2 different-ref overlap preserve invocation identity, not permanent standard-slot leases or pair-wide transactions.','Both sides preserve original options by text where React is not executed.','No actual history/private/frozen/native/FULL/CI/engine/census/platform scope expansion.'],D2ExecutionsRemain:{public:11,publicPass:11,independent:5,independentPass:4,independentFail:1,reversalKills:3},candidateChangedDuringReconciliation:false};
fs.writeFileSync(dir+'/reconciliation-evidence.json',JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({archiveCopies:17,authorStages:stages.map(x=>({file:x.file,tests:x.tests,pass:x.pass,fail:x.fail})),authorReversals:reversals.length,verdict:'REJECT',R1:'retained',runtimeAndInputIdentity:'match'}));
