import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildToday, DIST, ROOT } from '../build.mjs';
import { buildBrowser } from '../../../w6/build-browser.mjs';
import { CSP } from '../serve.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
const { chromium }=createRequire(new URL('../../../w6/package.json',import.meta.url))('playwright-core');
const executablePath=process.env.W7_BROWSER_BIN;
assert.ok(executablePath,'Set W7_BROWSER_BIN to the existing browser; no installation is performed.');
await buildToday();
const probe=path.join(ROOT,'.tmp/first-use-probe.js');
await buildBrowser({entryPoints:[path.join(here,'browser-probe.mjs')],outfile:probe});
const files={'/':['index.html','text/html'],'/styles.css':['styles.css','text/css'],'/app.js':['app.js','text/javascript']};
const server=http.createServer(async(req,res)=>{
  const match=files[req.url];
  if(!match&&req.url!=='/probe.js'){res.writeHead(404);res.end();return;}
  res.writeHead(200,{'Content-Type':match?.[1]||'text/javascript','Content-Security-Policy':CSP});
  res.end(await fs.readFile(match?path.join(DIST,match[0]):probe));
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath,headless:true});
const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(url)&&!r.url().startsWith('data:'))errors.push('off-origin request');});
const snapshots=path.join(ROOT,'.tmp/first-use-screenshots');await fs.mkdir(snapshots,{recursive:true});
const read=async()=>{await page.addScriptTag({url:url+'/probe.js',type:'module'});await page.waitForFunction(()=>typeof inspectFirstUse==='function');return page.evaluate(()=>inspectFirstUse());};
try {
  await page.goto(url);await page.getByRole('heading',{name:'Make it yours.'}).waitFor();
  assert.ok(await page.locator('#phone').evaluate(root=>root.scrollWidth<=root.clientWidth));
  assert.ok(await page.locator('.setup').evaluate(root=>[...root.querySelectorAll('input,select')].every(x=>parseFloat(getComputedStyle(x).fontSize)>=16)));
  await page.screenshot({path:path.join(snapshots,'01-fresh.png'),fullPage:true});
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  assert.equal(await page.locator(':focus').getAttribute('name'),'athlete_label');
  await page.getByLabel('Your name',{exact:true}).fill('Synthetic first-use athlete');
  const from=await page.getByLabel('Routine starts').inputValue();
  const day=new Date(from+'T12:00:00').getDay();
  const lower=(day+2)%7;
  for(let i=0;i<7;i++)await page.locator('[name="day-'+i+'"]').selectOption(i===day?'U':i===lower?'L':'REST');
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByRole('button',{name:'Add an exercise',exact:true}).click();
  await page.getByLabel('Sets per session',{exact:true}).fill('7');
  await page.getByRole('button',{name:'Cancel exercise',exact:true}).click();
  assert.equal(await page.getByRole('heading',{name:'Chest press',exact:true}).count(),0);
  for(const [choice,sets] of [['press','1'],['hack','2']]){
    await page.getByRole('button',{name:'Add an exercise',exact:true}).click();
    await page.getByLabel('Exercise',{exact:true}).selectOption(choice);
    await page.getByLabel('Sets per session',{exact:true}).fill(sets);
    await page.getByLabel('Rep ceiling',{exact:true}).fill('10');
    await page.getByLabel('Load increase (lb)',{exact:true}).fill('2.5');
    await page.getByLabel('Available loads (lb)',{exact:true}).fill('20, 22.5, 25, 30, 40');
    await page.getByLabel('This is my bilateral exercise.',{exact:false}).check();
    await page.getByRole('button',{name:'Add exercise',exact:true}).click();
  }
  await page.getByLabel('These entries include my complete current routine',{exact:false}).check();
  await page.getByRole('button',{name:'Review routine',exact:true}).click();
  await page.getByRole('heading',{name:'Ready to save?'}).waitFor();
  await page.screenshot({path:path.join(snapshots,'02-review.png'),fullPage:true});
  await page.getByRole('button',{name:'Back to exercises',exact:true}).click();
  await page.getByRole('button',{name:'Edit Chest press',exact:true}).click();
  assert.equal(await page.getByLabel('Sets per session',{exact:true}).inputValue(),'1');
  assert.equal(await page.getByLabel('Available loads (lb)',{exact:true}).inputValue(),'20, 22.5, 25, 30, 40');
  await page.getByRole('button',{name:'Cancel exercise',exact:true}).click();
  await page.getByLabel('These entries include my complete current routine',{exact:false}).check();
  await page.getByRole('button',{name:'Review routine',exact:true}).click();
  await page.getByRole('button',{name:'Save my routine',exact:true}).click();
  await page.locator('[data-slot="instruction"]').waitFor();
  assert.match(await page.locator('#today-status').textContent(),/routine is saved/);
  const before=await read();assert.equal(before.setup.athlete_label,'Synthetic first-use athlete');assert.deepEqual(before.initialLoads,[null,null]);assert.deepEqual(before.initialHistory,{});
  assert.deepEqual(before.setup.exercises.map(x=>[x.id,x.mg,x.day,x.sets,x.hi,x.inc,x.steps]),[
    ['press','chest','U',1,10,2.5,[20,22.5,25,30,40]],['hack','quads','L',2,10,2.5,[20,22.5,25,30,40]]]);
  await page.screenshot({path:path.join(snapshots,'03-today.png'),fullPage:true});
  await page.getByRole('button',{name:'Start UPPER',exact:true}).click();
  await page.getByRole('button',{name:'Log set 1',exact:true}).waitFor();
  await page.getByLabel('Actual weight in pounds',{exact:true}).fill('40');
  await page.getByLabel('Actual reps',{exact:true}).fill('10');
  await page.getByRole('button',{name:'0',exact:true}).click();
  await page.getByRole('button',{name:'Log set 1',exact:true}).click();
  await page.getByRole('button',{name:'Finish this workout',exact:true}).waitFor();
  await page.screenshot({path:path.join(snapshots,'04-first-set.png'),fullPage:true});
  await page.getByRole('button',{name:'Finish this workout',exact:true}).click();
  await page.locator('[data-slot="instruction"]').waitFor();
  const after=await page.evaluate(()=>inspectFirstUse());
  assert.deepEqual(Object.values(before.collections.ops),[],'setup alone starts no workout');
  const ops=Object.values(after.collections.ops);
  assert.deepEqual(ops.map(x=>x.kind),['session-start','session-set','session-close']);
  assert.equal(ops[1].lift_lineage_id,'press');assert.deepEqual(ops[1].payload.load,{value:40,unit:'lb'});
  assert.deepEqual(ops[1].payload.reps,{value:10,unit:'rep'});assert.equal(ops[2].payload.completion_kind,'normal');
  await page.reload();await page.locator('[data-slot="instruction"]').waitFor();
  const reopened=await read();assert.deepEqual(reopened.setup,before.setup);assert.equal(reopened.deviceId,before.deviceId);
  assert.deepEqual(reopened.collections,after.collections);
  await page.screenshot({path:path.join(snapshots,'05-reloaded.png'),fullPage:true});
  console.log('FIRST-USE BROWSER setup/review/enroll/first-set/close/reload PASS');
  assert.deepEqual(errors,[]);
} finally {await context.close();await browser.close();await new Promise(r=>server.close(r));}
