'use strict';
// Synthetic verdict objects test the closed CI boundary, not real engine sites.
// The actual protected second gate is run only by the pinned CLI after commit.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const C=require('../ci-second-gate.cjs'),A=require('../acceptance.cjs'),S=require('../source-proof.cjs'),L=require('../legacy-gates.cjs');
const root=path.resolve(__dirname,'../../../../..'),cli=path.join(root,'rebuild/conform/v4/postfix/ci-second-gate.cjs');
const copy=structuredClone,site='tools/engine-test.jsx:106:5',counts={reference:3072,candidate:3072,surface:4,legacy:6,fixedClockRuns:1};
const protectedOld='SYNTHETIC OLD CONTEXT — never a real protected value',protectedNew='SYNTHETIC NEW CONTEXT — never a real protected value';
function guard(text){if(text.includes(protectedOld)||text.includes(protectedNew))throw Error('SYNTHETIC-LEAK-DETECTED');}
function evidence(){return {id:'second-gate',mode:'frozen',status:'PASS',candidateKind:'rebuild/engine via second-gate-adapter.mjs',projection:{preimageOccurrences:1,bytesDelta:-9},expected106:{derivedFrom:'frozen fe516c1 src/app.jsx + one-expression projection, harness clock',frozenSatisfiesOriginalPredicate:true,projectedSatisfiesOriginalPredicate:false,statusUnchanged:true,nNeedExcludedBoundUnchanged:true,signPreserved:true,resolvedFlips:true},surface:{exactDelta:'PASS',pointerPathsChangedByProjection:['2026-08-06/stepEfficacy/resolved','2026-08-06/stepEfficacy/slopePer1k','2026-08-07/stepEfficacy/resolved','2026-08-07/stepEfficacy/slopePer1k']},negativeControl:{engine:'unprojected frozen',exitNonZero:true,failSites:[site],observedBeforeHarnessExit:106,expect106Calls:1,violations:[]},driver:{diskUntouched:true,edits:Array.from({length:7},()=>({occurrences:1}))},custody:{substitutions:1,expect106Calls:1,surfaceCalls:{reference:1,candidate:1},carriedSite:site,carriedSiteOccurrences:1},gate:{catalogTotal:3072,referenceObserved:3072,candidateObserved:3072,failSites:[],legacyMkPushable:['4818:PASS','4820:PASS','4821:PASS','4822:PASS','4825:PASS','4826:PASS'],randomCallsEqual:true,networkCalls:[6,6],violations:[[],[]],lines:['SECOND GATE reference surface: byte-identical to committed baseline (synthetic bytes)','SECOND GATE candidate: PASS; synthetic']},tail:'SYNTHETIC helper text is not public output'};}
test('only the exact published profile is a CLI option',()=>{assert.equal(C.args(['--profile','M2-STEP-EFFICACY']),C.PROFILE);for(const argv of [[],['--profile'],['--profile','M2-IMPORT-GUARDS'],['--profile','anything'],['--profile','M2-STEP-EFFICACY','--skip'],['--candidate','x'],['--profile','M2-STEP-EFFICACY','--profile','M2-STEP-EFFICACY']])assert.throws(()=>C.args(argv),{code:'CI-PROFILE'});});
test('cold missing/unknown CLI profiles fail with only a fixed public label',()=>{for(const argv of [[],['--profile','unknown'],['--profile','M2-STEP-EFFICACY','--native']]){const r=cp.spawnSync(process.execPath,[cli,...argv],{cwd:root,encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(r.status,1);assert.equal(r.stdout,'');assert.equal(r.stderr.trim(),'CI SECOND GATE FAIL');}});
test('synthetic valid evidence produces only fixed labels and validated counts',()=>{assert.deepEqual(C.validateEvidence(evidence()),counts);assert.deepEqual(C.finish({result:evidence(),error:null,captured:[]},guard),counts);assert.equal(C.publicLine(counts),'CI SECOND GATE PASS; 3072 reference / 3072 candidate assertions; 4 surface cells; 6 legacy sites; 1 fixed-clock run');});
for(const [name,mutate]of [
  ['prototype candidate',r=>r.candidateKind='SOURCE-ONLY PROTOTYPE'],['native domain',r=>r.mode='native'],['pending helper',r=>r.status='PENDING'],['missing original site',r=>r.gate.referenceObserved--],['duplicate candidate site',r=>r.gate.candidateObserved++],['missing multiplicity',r=>r.custody.carriedSiteOccurrences=0],['extra carried condition',r=>r.custody.substitutions=2],['106 predicate not flipped',r=>r.expected106.projectedSatisfiesOriginalPredicate=true],['original106 no longer true',r=>r.expected106.frozenSatisfiesOriginalPredicate=false],['unrelated106 field changed',r=>r.expected106.nNeedExcludedBoundUnchanged=false],['fifth surface cell',r=>r.surface.pointerPathsChangedByProjection.push('synthetic/fifth')],['surface order changed',r=>r.surface.pointerPathsChangedByProjection.reverse()],['negative control green',r=>r.negativeControl.exitNonZero=false],['negative wrong site',r=>r.negativeControl.failSites=['tools/engine-test.jsx:107:5']],['negative nonempty violations',r=>r.negativeControl.violations=['synthetic']],['driver changed',r=>r.driver.diskUntouched=false],['extra driver substitution',r=>r.driver.edits.push({occurrences:1})],['legacy4822 changed',r=>r.gate.legacyMkPushable[3]='4822:FAIL'],['random mismatch',r=>r.gate.randomCallsEqual=false],['network mismatch',r=>r.gate.networkCalls[0]++],['missing reference verdict',r=>r.gate.lines.shift()]
])test('closed CI evidence refuses '+name,()=>{const r=evidence();mutate(r);assert.throws(()=>C.validateEvidence(r));});
test('public formatter refuses values, fields or counts outside the closed result',()=>{for(const r of [{...counts,candidate:'3072'},{...counts,surface:5},{...counts,detail:protectedOld},{...counts,reference:NaN}])assert.throws(()=>C.publicLine(r));});
test('canary refuses old/new full protected strings in helper result or error',()=>{for(const text of [protectedOld,protectedNew]){const r=evidence();r.tail=text;assert.throws(()=>C.finish({result:r,error:null,captured:[]},guard),/SYNTHETIC-LEAK-DETECTED/);assert.throws(()=>C.finish({result:null,error:Error(text),captured:[]},guard),/SYNTHETIC-LEAK-DETECTED/);}});
test('canary catches a full protected string split across writes',()=>{assert.throws(()=>C.finish({result:evidence(),error:null,captured:[protectedOld.slice(0,12),protectedOld.slice(12)]},guard),/SYNTHETIC-LEAK-DETECTED/);});
test('unrecognized error detail and noncanaried scalar strings never enter public formatter',()=>{assert.throws(()=>C.finish({result:null,error:Error('arbitrary noncanaried text'),captured:[]},guard),{code:'CI-SECOND-GATE-FAILED'});const r=evidence();r.tail='"slopePer1k": "synthetic scalar"';assert.equal(C.publicLine(C.finish({result:r,error:null,captured:[r.tail]},guard)),C.publicLine(counts));});
test('accessor or missing guard cannot manufacture a safe result',()=>{const r=evidence();Object.defineProperty(r,'extra',{get(){throw Error('must not invoke');}});assert.throws(()=>C.finish({result:r,error:null,captured:[]},guard),{code:'CI-EVIDENCE-ACCESSOR'});assert.throws(()=>C.finish({result:evidence(),error:null,captured:[]},null),{code:'CI-CUSTODY-PENDING'});});
test('stdout/stderr are captured and restored even when a helper throws',()=>{const out=process.stdout.write,err=process.stderr.write;let captured;assert.throws(()=>C.quiet(lines=>{captured=lines;process.stdout.write('synthetic-out');process.stderr.write('synthetic-error');throw Error('synthetic');}),/synthetic/);assert.deepEqual(captured,['synthetic-out','synthetic-error']);assert.equal(process.stdout.write,out);assert.equal(process.stderr.write,err);});
test('swallowed oversized write still makes the quiet boundary fail closed',()=>{assert.throws(()=>C.quiet(()=>{try{process.stdout.write('x'.repeat(4*1024*1024+1));}catch(_){}return counts;}),{code:'CI-OUTPUT-LIMIT'});});
const parent=path.join(root,'.tmp/postfix/ci-second-gate-tests');fs.mkdirSync(parent,{recursive:true});const temp=fs.mkdtempSync(path.join(parent,'synthetic-'));
test.after(()=>{assert(path.resolve(temp).startsWith(path.resolve(parent)+path.sep));fs.rmSync(temp,{recursive:true,force:true});});
test('cold actual entry suppresses missing or throwing synthetic preflight dependencies',()=>{const dir=path.join(temp,'rebuild/conform/v4/postfix');fs.mkdirSync(dir,{recursive:true});const entry=path.join(dir,'ci-second-gate.cjs');fs.copyFileSync(cli,entry);const launch=()=>cp.spawnSync(process.execPath,[entry,'--profile',C.PROFILE],{cwd:temp,encoding:'utf8',windowsHide:true,timeout:30000});for(const body of [null,"process.stdout.write('SYNTHETIC PROTECTED PREFLIGHT');process.stderr.write('SYNTHETIC PROTECTED PREFLIGHT');throw Error('SYNTHETIC PROTECTED PREFLIGHT');"]){if(body!==null)fs.writeFileSync(path.join(dir,'acceptance.cjs'),body);const r=launch();assert.equal(r.status,1);assert.equal(r.stdout,'');assert.equal(r.stderr.trim(),'CI SECOND GATE FAIL');}});
test('missing or unpinned helper fails before candidate execution',()=>{assert.throws(()=>C.requirePinnedHelper(temp,{executionPins:{[C.HELPER]:C.HELPER_SHA}}));assert.throws(()=>C.requirePinnedHelper(root,{executionPins:{[C.HELPER]:'0'.repeat(64)}}),{code:'CI-CUSTODY-PIN'});const file=path.join(temp,C.HELPER);fs.mkdirSync(path.dirname(file),{recursive:true});fs.copyFileSync(path.join(root,C.HELPER),file);assert.throws(()=>C.requirePinnedHelper(temp,{executionPins:{[C.HELPER]:C.HELPER_SHA}}),{code:'CI-CUSTODY-PENDING'});fs.appendFileSync(file,'\n// synthetic tamper\n');assert.throws(()=>C.requirePinnedHelper(temp,{executionPins:{[C.HELPER]:C.HELPER_SHA,[C.CUSTODY]:'0'.repeat(64)}}),{code:'CI-CUSTODY-PIN'});});
test('restoring times1000 cannot satisfy the actual one-expression source gate',()=>{const p=A.parentArtifact(root),original=L.object(root,p.baseline.auditCommit,S.STEP_FILE).toString('utf8');assert(original.includes(S.STEP_BEFORE));assert.throws(()=>S.proposeStepEfficacyChange(original,original),{code:'UNAPPROVED-SOURCE-DELTA'});});
test('workflow changes exactly one command and retains both OS jobs',()=>{const original=L.object(root,'a777f64318dfb9b4766fa336d623196d07b5fc00','.github/workflows/rebuild.yml').toString('utf8'),actual=fs.readFileSync(path.join(root,'.github/workflows/rebuild.yml'),'utf8'),before='run: node rebuild/engine/test/second-gate.mjs --candidate',after='run: node rebuild/conform/v4/postfix/ci-second-gate.cjs --profile M2-SET-ONE-ERA';assert.equal(original.split(before).length,2);assert.equal(actual,original.replace(before,after));assert(actual.includes('os: [ubuntu-latest, windows-latest]'));assert(!actual.includes('|| true'));});
