'use strict';
// Cold CLI initialization only. Actual run.cjs and package-runner.cjs bytes are
// copied unchanged; synthetic dependency/carrier fixtures grant NO real approval
// and execute NO product/private gate. PACKAGE must retain REVIEW-PENDING exit2.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const R=require('../run.cjs'),base=path.resolve(__dirname,'../../../../..'),pfx='rebuild/conform/v4/postfix',source=path.join(base,pfx);
const parent=path.join(base,'.tmp/postfix/cli-tests');fs.mkdirSync(parent,{recursive:true});
const root=fs.mkdtempSync(path.join(parent,'synthetic-'));test.after(()=>{assert.ok(root.startsWith(parent+path.sep));fs.rmSync(root,{recursive:true,force:true});});
const directory=path.join(root,pfx),write=(p,b)=>{const file=path.join(root,p);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,b);};
const json=x=>JSON.stringify(x,null,2)+'\n',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const run=fs.readFileSync(path.join(source,'run.cjs'),'utf8');write(pfx+'/run.cjs',run);write(pfx+'/package-runner.cjs',fs.readFileSync(path.join(source,'package-runner.cjs')));
write(pfx+'/target.cjs',`const crypto=require('node:crypto');exports.sha=b=>crypto.createHash('sha256').update(b).digest('hex');exports.fail=code=>{const e=Error(code);e.code=code;throw e;};`);
write(pfx+'/strict-json.cjs',`exports.parseExact=b=>JSON.parse(b);`);
write(pfx+'/structural-delta.cjs',`exports.compareStructural=()=>{throw Error('SYNTHETIC-UNEXPECTED-COMPARE');};`);
write(pfx+'/source-proof.cjs',`exports.verifyProductSources=()=>({synthetic:true});`);
write(pfx+'/acceptance.cjs',`const fs=require('node:fs'),path=require('node:path');exports.FILE='synthetic-acceptance.json';exports.profile=()=>({id:'M2-IMPORT-GUARDS'});exports.artifactFile=()=>exports.FILE;exports.envelopeFile=()=> 'synthetic-envelope.json';exports.envelope=x=>x;exports.load=root=>({envelope:JSON.parse(fs.readFileSync(path.join(root,'synthetic-envelope.json'))),acceptance:JSON.parse(fs.readFileSync(path.join(root,'synthetic-acceptance.json'))),bytes:Buffer.from('synthetic only')});exports.fetchIntegration=()=>{};exports.ancestry=()=>{};exports.verifyReceipts=()=>false;exports.missing=()=>[];exports.keys=(o,n,c)=>{if(JSON.stringify(Object.keys(o).sort())!==JSON.stringify(n.sort()))throw Error(c);};`);
write(pfx+'/legacy-gates.cjs',`const fs=require('node:fs'),path=require('node:path');exports.git=(root,args)=>Buffer.from(args.includes('--show-toplevel')?path.resolve(root,'../..'):'synthetic-audit');exports.object=(root,commit,file)=>fs.readFileSync(path.join(root,file));exports.checkSources=()=>{};exports.publicReferences=()=>({main:'synthetic-main',old:'synthetic-old'});exports.historicalAudit=()=>('SYNTHETIC lifecycle fixture; not product evidence');`);
const ids=R.GATES.map(g=>g[0]==='witnesses-5'?'defect-witnesses-5':g[0]);
write(pfx+'/legacy-carriers.cjs',`const fs=require('node:fs'),path=require('node:path');exports.CARRIER_IDS=${JSON.stringify(ids)};exports.runCarrier=({id,mode,root})=>{if(!exports.CARRIER_IDS.includes(id)||!['frozen','native'].includes(mode))throw Error('SYNTHETIC-CARRIER-INPUT');fs.appendFileSync(path.join(root,'synthetic-visits.jsonl'),JSON.stringify({id,mode})+'\\n');return {tail:'SYNTHETIC CARRIER ONLY'};};`);
write(pfx+'/laws/import-guards.cjs',`exports.laws=[];exports.CASES=[];exports.ASSERTION_INVENTORY=[];exports.INVENTORY=[];`);
write(pfx+'/fixtures/import-guards-deltas.json',json([]));fs.mkdirSync(path.join(root,'rebuild/engine'),{recursive:true});
const files=fs.readdirSync(directory,{recursive:true,withFileTypes:true}).filter(x=>x.isFile()).map(x=>path.relative(root,path.join(x.parentPath,x.name)).split(path.sep).join('/')).sort();
const a={baseline:{auditCommit:'synthetic-audit',publicPins:{},buildSources:{}},executionPins:Object.fromEntries(files.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))])),caseModule:pfx+'/laws/import-guards.cjs',helperFiles:{},contracts:[],nonD:[],inventory:[],requiredIds:[],candidateEngine:{},matrix:[]};
write('synthetic-acceptance.json',json(a));write('synthetic-envelope.json',json({version:2,acceptanceSha256:'synthetic-only',candidateBase:'synthetic-only'}));
function launch(){return cp.spawnSync(process.execPath,[path.join(directory,'run.cjs'),'--manifest',path.join(root,'synthetic-envelope.json'),'--baseline',root,'--candidate',path.join(root,'rebuild/engine')],{cwd:root,env:{...process.env,NODE_OPTIONS:'',NODE_V8_COVERAGE:''},encoding:'utf8',windowsHide:true,timeout:10000,maxBuffer:1024*1024});}
test('cold actual v2 CLI initializes exports before real PACKAGE iterates every gate',()=>{const r=launch();assert.equal(r.status,2,r.stderr);assert.match(r.stdout,/REVIEW-PENDING: complete evidence collected/);assert.doesNotMatch(r.stdout,/\bPASS\b/);const visits=fs.readFileSync(path.join(root,'synthetic-visits.jsonl'),'utf8').trim().split('\n').map(JSON.parse);assert.deepEqual(visits,ids.flatMap(id=>['frozen','native'].map(mode=>({id,mode}))));assert.doesNotMatch(r.stderr,/circular dependency/);});
test('disposable old export order reproduces real CLI circular initialization failure',()=>{const line='module.exports={REQUIRED,NON_D,GATES,validate,preflight,packagePending,gateRun,parse,main};',old=run.replace(line+'\n','').trimEnd()+'\n'+line+'\n';write(pfx+'/run.cjs',old);a.executionPins[pfx+'/run.cjs']=sha(old);write('synthetic-acceptance.json',json(a));try{const r=launch();assert.equal(r.status,1);assert.match(r.stderr,/POSTFIX FAIL TypeError/);assert.match(r.stderr,/non-existent property 'GATES'.*circular dependency/);}finally{write(pfx+'/run.cjs',run);}});
