'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const H=require('../helpers/import-guards-expectations.cjs');
const {compareStructural}=require('../structural-delta.cjs');
const root=path.resolve(__dirname,'../../../../..'),candidate=path.join(root,'rebuild/engine');
const source=H.createFrozenSource({root});
const options={source,mode:'native',day:'2026-09-03'};
const trace=r=>({frames:r.frames,detail:r.detail});
function changeFirst(value,predicate,replacement){if(!value||typeof value!=='object')return false;for(const k of Object.keys(value)){if(predicate(value[k])){value[k]=replacement(value[k]);return true;}if(changeFirst(value[k],predicate,replacement))return true;}return false;}
test('candidate directory cannot be a frozen source',()=>assert.throws(()=>H.createFrozenSource({root:candidate}),/EXPECTED-FROZEN-REPO-ROOT/));
test('candidate file and forged source receipts are refused before import',async()=>{await assert.rejects(H.produce({...options,source:candidate,caseId:'IG33-READ-REPLACE',project:true}),/EXPECTED-EXPLICIT-INPUTS/);await assert.rejects(H.produce({...options,source:{root,bundle:path.join(candidate,'index.cjs')},caseId:'IG33-READ-REPLACE',project:true}),/EXPECTED-EXPLICIT-INPUTS/);assert.equal(require.cache[path.join(candidate,'index.cjs')],undefined);});
test('legacy bundle/candidate arguments cannot select another engine',async()=>{await assert.rejects(H.produce({...options,caseId:'IG33-READ-REPLACE',project:true,bundle:path.join(candidate,'index.cjs')}),/EXPECTED-EXPLICIT-INPUTS/);assert.throws(()=>H.createFrozenSource({root,candidate}),/EXPECTED-FROZEN-SOURCE-INPUT/);});
test('closed literal projection profiles cannot be rewritten',()=>{assert.ok(Object.isFrozen(H.PROFILES));const p=H.PROFILES['IG33-READ-REPLACE'];assert.ok(Object.isFrozen(p.values[0].lost));assert.throws(()=>p.values[0].lost.push('invented'),TypeError);assert.throws(()=>{H.PROFILES.invented={};},TypeError);});

test('existing marker preserves visible GREEN while both content predicates become false',async()=>{const caseId='IG34-MARKER-EXISTING',a=await H.produce({...options,caseId,project:false}),b=await H.produce({...options,caseId,project:true});assert.equal(a.status,'GREEN');assert.equal(b.status,'GREEN');assert.deepEqual(H.PROFILES[caseId].values,[false,false]);const d=H.exactCells(trace(a),trace(b),caseId).delta;assert.ok(d.cells.length>0);assert.equal(compareStructural(trace(a),trace(b),d),true);assert.throws(()=>compareStructural(trace(a),trace(b),{aliases:[],cells:[]}),/UNAPPROVED-DELTA/);assert.equal(require.cache[path.join(candidate,'index.cjs')],undefined);});
test('guard expectation is red on literal frozen and independently green',async()=>{const a=await H.produce({...options,caseId:'IG33-READ-REPLACE',project:false}),b=await H.produce({...options,caseId:'IG33-READ-REPLACE',project:true});assert.equal(a.status,'RED');assert.equal(b.status,'GREEN');const d=H.exactCells(trace(a),trace(b),'IG33-READ-REPLACE').delta;assert.equal(compareStructural(trace(a),trace(b),d),true);const altered=structuredClone(trace(b));assert.ok(changeFirst(altered,v=>Array.isArray(v)&&v[0]==='number'&&v[1]==='170',()=>['number','999']));assert.throws(()=>compareStructural(trace(a),altered,d),/UNAPPROVED-DELTA/);});
test('unlisted exact synthetic receipt changes fail closed',async()=>{const a=await H.produce({...options,caseId:'IG33-STRIKE-POSITIVE',project:false}),b=await H.produce({...options,caseId:'IG33-STRIKE-POSITIVE',project:true});const d=H.exactCells(trace(a),trace(b),'IG33-STRIKE-POSITIVE').delta;assert.equal(d.cells.length,0);const altered=structuredClone(trace(b));assert.ok(changeFirst(altered,v=>Array.isArray(v)&&v[0]==='string'&&v[1]==='SYNTHETIC strike receipt',()=>['string','SYNTHETIC altered receipt']));assert.throws(()=>compareStructural(trace(a),altered,d),/UNAPPROVED-DELTA/);});
test('future getter projection keeps original identity and never evaluates it',async()=>{const a=await H.produce({...options,caseId:'IG35-FUTURE-HEAL-GETTER',project:false}),b=await H.produce({...options,caseId:'IG35-FUTURE-HEAL-GETTER',project:true});assert.equal(a.status,'RED');assert.equal(b.status,'GREEN');assert.ok(b.assertions.every(x=>x.ok));assert.equal(compareStructural(trace(a),trace(b),H.exactCells(trace(a),trace(b),'IG35-FUTURE-HEAL-GETTER').delta),true);assert.equal(require.cache[path.join(candidate,'index.cjs')],undefined);});
test('ghSync exact frame correspondence retains identity and removes only four date calls',async()=>{const a=await H.produce({...options,caseId:'IG33-GHSYNC-REMOTE-RICH',project:false}),b=await H.produce({...options,caseId:'IG33-GHSYNC-REMOTE-RICH',project:true}),d=H.exactCells(trace(a),trace(b),'IG33-GHSYNC-REMOTE-RICH').delta;assert.equal(compareStructural(trace(a),trace(b),d),true);assert.deepEqual(d.cells.filter(c=>c.op==='remove'&&c.path.length===2).map(c=>c.before.name),['isoOf','todayStart','isoOf','todayStart']);assert.equal(new Set(d.aliases.map(p=>p[0])).size,d.aliases.length);assert.equal(new Set(d.aliases.map(p=>p[1])).size,d.aliases.length);assert.throws(()=>compareStructural(trace(a),trace(b),{...d,aliases:d.aliases.slice(1)}));assert.equal(require.cache[path.join(candidate,'index.cjs')],undefined);});
