'use strict';
// Synthetic protocol repositories. These tests authorize no real repair.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const {parseExact}=require('../strict-json.cjs'),T=require('../target.cjs'),A=require('../acceptance.cjs'),S=require('../structural-delta.cjs');
const throws=(fn,code)=>assert.throws(fn,e=>e.code===code),bytes=o=>Buffer.from(JSON.stringify(o,null,2)+'\n');
const artifact=JSON.parse(fs.readFileSync(path.join(__dirname,'../acceptance-import-guards.json'))),envelope=JSON.parse(fs.readFileSync(path.join(__dirname,'../manifest-import-guards.json')));
test('v2 actual proposed inventory keeps all45 approved, selected3, remaining42 pending and15 OPEN',()=>{A.validate(artifact);A.envelope(envelope);assert.equal(artifact.inventory.length,45);assert.equal(artifact.nonD.length,15);assert.equal(envelope.receipts.review.status,'PENDING');});
test('canonical exact bytes parse',()=>assert.deepEqual(parseExact(bytes({a:[1,true,null,'x']})),{a:[1,true,null,'x']}));
for(const [name,text,code]of [
  ['duplicate decoded key','{"a":1,"a":2}','JSON-DUPLICATE-KEY'],['escaped duplicate key','{"a":1,"\\u0061":2}','JSON-DUPLICATE-KEY'],['nested duplicate','{"x":[{"a":1,"a":2}]}','JSON-DUPLICATE-KEY'],
  ['trailing garbage','{}x','JSON-SYNTAX'],['trailing comma','{"x":1,}','JSON-SYNTAX'],['missing colon','{"x" 1}','JSON-SYNTAX'],['invalid escape','"\\q"','JSON-SYNTAX'],['invalid exponent','1e','JSON-SYNTAX'],
  ['noncanonical whitespace','{}','JSON-NONCANONICAL-BYTES'],['negative zero','-0\n','JSON-NONCANONICAL-BYTES'],['overflow','1e999\n','JSON-NONCANONICAL-BYTES'],['rounded large integer','9007199254740993\n','JSON-NONCANONICAL-BYTES'],['alternate escape','"\\u0061"\n','JSON-NONCANONICAL-BYTES']
])test('strict JSON refuses '+name,()=>throws(()=>parseExact(Buffer.from(text)),code));
test('strict JSON rejects invalid UTF8 rather than replacing it',()=>throws(()=>parseExact(Buffer.from([34,255,34,10])),'JSON-UTF8'));
test('strict JSON accepts dangerous names as inert parsed data, schema later restricts fields',()=>assert.equal(parseExact(Buffer.from('{\n  "__proto__": 1\n}\n')).__proto__,1));
for(const [name,change,code]of [
  ['extra envelope field',e=>e.requiredIds=[],'ENVELOPE-SCHEMA'],['wrong version',e=>e.version=3,'ENVELOPE-SCHEMA'],['wrong artifact path',e=>e.acceptanceFile='../artifact.json','ENVELOPE-SCHEMA'],['pending plus receipt',e=>e.receipts.review.receipt=e.receipts.owner,'REVIEW-STATUS-CONTRADICTION'],['accepted without receipt',e=>e.receipts.review.status='ACCEPTED','REVIEW-STATUS-CONTRADICTION'],['third review status',e=>e.receipts.review.status='ALMOST','REVIEW-STATUS-CONTRADICTION']
])test('operational envelope refuses '+name,()=>{const e=structuredClone(envelope);change(e);throws(()=>A.envelope(e),code);});
for(const [name,change,code]of [
  ['missing defect',a=>a.inventory.pop(),'D-INVENTORY'],['duplicate defect',a=>a.inventory[1]=a.inventory[0],'D-INVENTORY'],['empty selection',a=>a.selectedApprovedFixIds=[],'PACKAGE-INVENTORY'],['empty required IDs',a=>a.requiredIds=[],'PACKAGE-INVENTORY'],['undeclared extra nonD',a=>a.nonD.push({id:'invention'}),'NON-D-INVENTORY'],['false other defect repair',a=>a.inventory[0].implementation='PRESENT','DISPOSITION-IMPLEMENTATION'],['unruled approved direction',a=>a.inventory[0].disposition='UNRULED','DISPOSITION-IMPLEMENTATION'],['changed original law',a=>a.inventory[0].law.runSha256='0'.repeat(64),'RAW-LAW-PIN'],['missing case mode',a=>a.matrix.pop(),'GATE-OR-MODE-INVENTORY']
])test('acceptance rejects '+name,()=>{const a=structuredClone(artifact);change(a);throws(()=>A.validate(a),code);});
test('descriptor snapshot never invokes sleep or toStringTag getters',()=>{let calls=0;const x={v:61};const getter=()=>{calls++;throw Error('forbidden');};Object.defineProperty(x,'sleep',{get:getter,enumerable:true});Object.defineProperty(x,Symbol.toStringTag,{get:getter});const encode=T.graphEncoderV2(),a=encode(x),b=encode(x);assert.equal(calls,0);assert.deepEqual(a,b);assert.match(JSON.stringify(a),/accessor/);assert.match(JSON.stringify(a),/function/);});
test('old profile still identifies accessor as HARNESS_ERROR, not engine RED',()=>throws(()=>T.graphEncoder()(Object.defineProperty({},'x',{get(){throw Error('never');}})),'UNSUPPORTED-TRACE-ACCESSOR'));
test('profile2 distinguishes Error TypeError RangeError with identical messages',()=>{const hashes=[Error,TypeError,RangeError].map(C=>JSON.stringify(T.graphEncoderV2()(new C('same'))));assert.equal(new Set(hashes).size,3);});
test('profile2 distinguishes accessor identity and descriptor flags',()=>{const f=()=>1,g=()=>1,enc=T.graphEncoderV2(),a=Object.defineProperty({},'x',{get:f}),b=Object.defineProperty({},'x',{get:g,enumerable:true});assert.notDeepEqual(enc(a),enc(b));});
test('proxy is rejected before ANY trap runs',()=>{let calls=0;const x=new Proxy({},{getPrototypeOf(){calls++;return Object.prototype;},ownKeys(){calls++;return [];}});throws(()=>T.graphEncoderV2()(x),'UNSUPPORTED-TRACE-PROXY');assert.equal(calls,0);});
test('custom prototype cannot masquerade as plain object',()=>throws(()=>T.graphEncoderV2()(Object.create({})),'UNSUPPORTED-TRACE-PROTOTYPE'));
test('arbitrary Date subclasses cannot collapse distinct prototype behavior',()=>{class A extends Date{}class B extends Date{probe(){return 'extra';}}for(const value of [new A(0),new B(0)])throws(()=>T.graphEncoderV2()(value),'UNSUPPORTED-TRACE-PROTOTYPE');});
test('only frozen-boundary profile admits exact pinned clock Date class source',()=>{const {BOUNDARY_DATES}=require('../trace-v2.cjs'),source=[...BOUNDARY_DATES][0],C=new Function('RealDate','clock','return '+source)(Date,{nowMs:()=>0});const value=new C(0);throws(()=>T.graphEncoderV2()(value),'UNSUPPORTED-TRACE-PROTOTYPE');assert.equal(T.graphEncoderV2({boundaryDateProfile:true})(value)[2],'Date');C.prototype.extra=function(){};throws(()=>T.graphEncoderV2({boundaryDateProfile:true})(value),'UNSUPPORTED-TRACE-PROTOTYPE');});
test('profile2 captures a cycle and repeated identities',()=>{const x={};x.x=x;assert.match(JSON.stringify(T.graphEncoderV2()(x)),/\["ref",1\]/);});
test('structural add is exact and unknown extra field fails',()=>{const delta={aliases:[],cells:[{id:'add',op:'add',path:['x'],before:null,after:['undefined']}]};S.compareStructural({}, {x:['undefined']},delta);throws(()=>S.compareStructural({}, {x:['undefined'],unlisted:1},delta),'UNAPPROVED-DELTA');});
test('structural removal preserves exact absent state',()=>S.compareStructural({x:['null']},{},{aliases:[],cells:[{id:'remove',op:'remove',path:['x'],before:['null'],after:null}]}));
test('descriptor array removal is exact, including later descriptor order',()=>S.compareStructural({p:[['x',1],['y',2]]},{p:[['y',2]]},{aliases:[],cells:[{id:'descriptor',op:'remove',path:['p','0'],before:['x',1],after:null}]}));
test('structural overlap refuses',()=>throws(()=>S.compareStructural({x:{y:1}},{x:{y:2}},{aliases:[],cells:[{id:'a',op:'replace',path:['x'],before:{y:1},after:{y:2}},{id:'b',op:'replace',path:['x','y'],before:1,after:2}]}),'DELTA-OVERLAP'));
test('explicit alias bijection preserves identity, never value numbers',()=>{const x=['node',1,'Object','standard',[[['string','n'],'data',true,true,true,['number','1']]],null];assert.deepEqual(S.remapGraph(x,[[1,2]]),['node',2,'Object','standard',x[4],null]);});
test('alias collision or unused mapping refuses',()=>{throws(()=>S.remapGraph([['ref',1],['ref',2]],[[1,2]]),'ALIAS-MAPPING-UNUSED-OR-COLLISION');throws(()=>S.remapGraph(['null'],[[1,2]]),'ALIAS-MAPPING-UNUSED-OR-COLLISION');});
const parent=path.resolve(__dirname,'../../../../../.tmp/postfix/package-tests');fs.mkdirSync(parent,{recursive:true});const repo=fs.mkdtempSync(path.join(parent,'synthetic-'));
test.after(()=>{assert.ok(repo.startsWith(parent+path.sep));fs.rmSync(repo,{recursive:true,force:true});});
function git(args){return cp.execFileSync('git',args,{cwd:repo,encoding:'utf8',windowsHide:true,stdio:['ignore','pipe','pipe']}).trim();}
function write(file,value){const p=path.join(repo,file);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,value);}
function commit(message){git(['add','.']);git(['-c','user.name=Synthetic','-c','user.email=synthetic@example.invalid','commit','-qm',message]);return git(['rev-parse','HEAD']);}
git(['init','-q']);const originalLines=['owner','contract','theme'].map(k=>artifact.authorizations[k].line);write('rebuild/DECISIONS.md',originalLines.join('\n')+'\n');const anchor=commit('synthetic authorization mappings');
const payload=bytes({synthetic:true,noRealApproval:true});write(A.FILE,payload);const artifactCommit=commit('synthetic reviewed artifact');
git(['checkout','-q','--detach',anchor]);const acceptedLine='- synthetic · cowork · POSTFIX-ACCEPTANCE M2-IMPORT-GUARDS '+artifactCommit+' '+A.FILE+' '+T.sha(payload)+' ACCEPTED';write('rebuild/DECISIONS.md',originalLines.concat(acceptedLine).join('\n')+'\n');const receiptBase=commit('synthetic acceptance receipt');git(['update-ref','refs/remotes/origin/rebuild/t2-client-core',receiptBase]);git(['-c','user.name=Synthetic','-c','user.email=synthetic@example.invalid','merge','--no-ff','-qm','synthetic combined candidate',artifactCommit]);
const syntheticA={...artifact,codeBaseAnchor:anchor},syntheticE=structuredClone(envelope);syntheticE.candidateBase=receiptBase;syntheticE.acceptanceSha256=T.sha(payload);for(const k of ['owner','contract','theme'])syntheticE.receipts[k].commit=receiptBase;syntheticE.receipts.review={status:'ACCEPTED',receipt:{commit:receiptBase,path:'rebuild/DECISIONS.md',line:acceptedLine,lineSha256:T.sha(acceptedLine)}};
test('real synthetic artifact commit and exact ledger line produce noncircular acceptance',()=>{A.ancestry(repo,syntheticA,syntheticE);assert.equal(A.verifyReceipts(repo,syntheticA,syntheticE,payload),true);});
test('missing review stays pending, not a fabricated acceptance',()=>{const e=structuredClone(syntheticE);e.receipts.review={status:'PENDING',receipt:null};assert.equal(A.verifyReceipts(repo,syntheticA,e,payload),false);});
test('modified artifact bytes cannot reuse actual review',()=>throws(()=>A.verifyReceipts(repo,syntheticA,syntheticE,bytes({different:true})),'REVIEW-ARTIFACT-GIT-PIN'));
test('unpublished receipt base is rejected despite a valid local commit',()=>{const e=structuredClone(syntheticE);e.candidateBase=git(['rev-parse','HEAD']);throws(()=>A.ancestry(repo,syntheticA,e),'CANDIDATE-BASE-STALE');});
test('post-integration rerun no longer depends on moving merge-base equality',()=>{git(['update-ref','refs/remotes/origin/rebuild/t2-client-core',git(['rev-parse','HEAD'])]);A.ancestry(repo,syntheticA,syntheticE);});
for(const verdict of ['NOT ACCEPTED','REVISE','REJECT','ACCEPTED extra'])test('new dedicated receipt refuses '+verdict,()=>{
  const line=acceptedLine.replace(/ACCEPTED$/,verdict),oldHead=git(['rev-parse','HEAD']);write('rebuild/DECISIONS.md',originalLines.concat(line).join('\n')+'\n');const base=commit('synthetic bad verdict '+verdict),e=structuredClone(syntheticE);e.candidateBase=base;for(const k of ['owner','contract','theme'])e.receipts[k].commit=base;e.receipts.review.receipt={commit:base,path:'rebuild/DECISIONS.md',line,lineSha256:T.sha(line)};throws(()=>A.verifyReceipts(repo,syntheticA,e,payload),'REVIEW-EXACT-VERDICT');git(['checkout','-q','--detach',oldHead]);
});
test('bounded fetch refreshes actual remote integration ref; failed fetch is BLOCKED',()=>{
  const head=git(['rev-parse','HEAD']),bare=path.join(repo,'local-remote.git');git(['update-ref','refs/heads/rebuild/t2-client-core',head]);
  cp.execFileSync('git',['clone','--bare',repo,bare],{stdio:['ignore','pipe','pipe'],windowsHide:true});git(['remote','add','origin',bare]);git(['update-ref','refs/remotes/origin/rebuild/t2-client-core',anchor]);
  assert.equal(A.fetchIntegration(repo),head);git(['remote','set-url','origin',path.join(repo,'missing-remote')]);throws(()=>A.fetchIntegration(repo),'INTEGRATION-FETCH-BLOCKED');git(['remote','set-url','origin',bare]);
});

const shiftedBefore={frames:[['keep',0],['clock',1],['keep',2]]},shiftedAfter={frames:[['keep',0],['keep',3]]};
const shiftedDelta={aliases:[],cells:[{id:'retained-value',op:'replace',path:['frames','2','1'],afterPath:['frames','1','1'],before:2,after:3},{id:'removed-clock',op:'remove',path:['frames','1'],before:['clock',1],after:null}]};
test('exact retained-frame scalar correspondence preserves full trace after earlier frame removal',()=>S.compareStructural(shiftedBefore,shiftedAfter,shiftedDelta));
test('wrong retained-frame correspondence cannot bless an unexpected relocation',()=>{const d=structuredClone(shiftedDelta);d.cells[0].afterPath=['frames','0','1'];throws(()=>S.compareStructural(shiftedBefore,shiftedAfter,d),'DELTA-PREDICATE');});
test('frame correspondence cannot relocate an entire observation or alter a leaf path',()=>{const d=structuredClone(shiftedDelta);d.cells[0].afterPath=['frames','1','0'];throws(()=>S.compareStructural(shiftedBefore,shiftedAfter,d),'DELTA-FRAME-CORRESPONDENCE');const whole={aliases:[],cells:[{id:'whole',op:'replace',path:['frames','2'],afterPath:['frames','1'],before:['keep',2],after:['keep',3]}]};throws(()=>S.compareStructural(shiftedBefore,shiftedAfter,whole),'DELTA-FRAME-CORRESPONDENCE');});
test('frame correspondence retains original path overlap refusal',()=>{const d=structuredClone(shiftedDelta);d.cells.push({id:'overlap',op:'remove',path:['frames','2'],before:['keep',3],after:null});throws(()=>S.compareStructural(shiftedBefore,shiftedAfter,d),'DELTA-OVERLAP');});
test('two retained leaves cannot collide on one destination',()=>{const d={aliases:[],cells:[{id:'one',op:'replace',path:['frames','0','1'],afterPath:['frames','1','1'],before:0,after:3},{id:'two',op:'replace',path:['frames','2','1'],afterPath:['frames','1','1'],before:2,after:3}]};throws(()=>S.compareStructural(shiftedBefore,shiftedAfter,d),'DELTA-DESTINATION-OVERLAP');});
for(const [name,change,code]of [
 ['missing raw expectations',a=>delete a.inventory[0].rawExpectations,'D-SCHEMA'],
 ['default original GREEN',a=>a.inventory[0].rawExpectations[0].originalStatus='GREEN','RAW-EXPECTATION-OUTCOME'],
 ['selected candidate RED',a=>a.inventory.find(r=>r.defect==='D33').rawExpectations[0].candidateStatus='RED','RAW-EXPECTATION-OUTCOME'],
 ['D27 nondefault candidate RED',a=>a.inventory.find(r=>r.defect==='D27').rawExpectations.find(c=>c.day==='2026-09-07').candidateStatus='RED','RAW-EXPECTATION-OUTCOME'],
 ['D44 nondefault fake status',a=>a.inventory.find(r=>r.defect==='D44').rawExpectations.find(c=>c.day==='2026-09-07').candidateStatus='RED','RAW-EXPECTATION-OUTCOME'],
 ['unselected output delta',a=>a.inventory[0].outputDeltas=[a.inventory.find(r=>r.defect==='D33').outputDeltas[0]],'UNSELECTED-IMPLEMENTATION']
])test('raw matrix refuses '+name,()=>{const a=structuredClone(artifact);change(a);throws(()=>A.validate(a),code);});

test('retained-frame typed tail removal has exact preimage and full postimage',()=>{const b={frames:[['clock'],['return',['node',7,{body:'synthetic'}]]]},a={frames:[['return',['null']]]};const d={aliases:[],cells:[{id:'tag',op:'replace',path:['frames','1','1','0'],afterPath:['frames','0','1','0'],before:'node',after:'null'},{id:'body',op:'remove',path:['frames','1','1','2'],afterPath:['frames','0','1','2'],before:{body:'synthetic'},after:null},{id:'id',op:'remove',path:['frames','1','1','1'],afterPath:['frames','0','1','1'],before:7,after:null},{id:'clock',op:'remove',path:['frames','0'],before:['clock'],after:null}]};S.compareStructural(b,a,d);const wrong=structuredClone(a);wrong.frames[0][1].push('extra');throws(()=>S.compareStructural(b,wrong,d),'DELTA-PREDICATE');});

test('retained-frame addition requires absent original cell and exact final descriptor',()=>{const b={frames:[['clock'],['guard',[]]]},a={frames:[['guard',[['reason','lost']]]]};const d={aliases:[],cells:[{id:'reason',op:'add',path:['frames','1','1','0'],afterPath:['frames','0','1','0'],before:null,after:['reason','lost']},{id:'clock',op:'remove',path:['frames','0'],before:['clock'],after:null}]};S.compareStructural(b,a,d);const occupied=structuredClone(b);occupied.frames[1][1].push(['existing']);throws(()=>S.compareStructural(occupied,a,d),'DELTA-PREDICATE');const wrong=structuredClone(a);wrong.frames[0][1][0][1]='different';throws(()=>S.compareStructural(b,wrong,d),'DELTA-PREDICATE');});

test('nonRED original cell cannot omit or soften its executed masking reason',()=>{for(const id of ['D27','D44']){const a=structuredClone(artifact),cell=a.inventory.find(r=>r.defect===id).rawExpectations.find(c=>c.day==='2026-09-07');cell.maskingReason=null;throws(()=>A.validate(a),'RAW-EXPECTATION-OUTCOME');delete cell.maskingReason;throws(()=>A.validate(a),'RAW-EXPECTATION-SCHEMA');}});
