'use strict';
// Assembly-boundary checks use empty synthetic deltas, never product evidence.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const B=require('../helpers/build-set-one-era-acceptance.cjs'),A=require('../acceptance.cjs'),T=require('../target.cjs'),root=path.resolve(__dirname,'../../../../..');
const {parseExact}=require('../strict-json.cjs');
const {parseCompactExact}=require('../helpers/set-one-era-compact-json.cjs');
const row=A.stepParentArtifact(root).inventory.find(r=>r.defect==='D30'),matrix=A.BASE.matrix;
function raw(){return {method:'SYNTHETIC assembly fixture only',law:structuredClone(row.law),outputDeltas:matrix.map((cell,i)=>({...cell,originalVerdict:'RED',candidateVerdict:'GREEN',originalTraceSha256:row.rawExpectations[i].originalTraceSha256,delta:{aliases:[],cells:[]}}))};}
test('assembly preserves exact source-preimage pins and every supplied synthetic delta cell',()=>{const r=raw();assert.deepEqual(B.rawDeltas(r,row,matrix),r.outputDeltas.map(({originalVerdict,candidateVerdict,...x})=>x));});
for(const [name,mutate,code]of [
 ['wrong raw law',r=>r.law.id='V4-D30-SET-ONE-ERA','ERA-BUILD-RAW-LAW'],['missing matrix cell',r=>r.outputDeltas.pop(),'ERA-BUILD-RAW-MATRIX'],['reordered matrix',r=>r.outputDeltas.reverse(),'ERA-BUILD-RAW-MATRIX'],['changed original trace',r=>r.outputDeltas[0].originalTraceSha256='0'.repeat(64),'ERA-BUILD-RAW-PREIMAGE'],['old status green',r=>r.outputDeltas[0].originalVerdict='GREEN','ERA-BUILD-RAW-PREIMAGE'],['new status red',r=>r.outputDeltas[0].candidateVerdict='RED','ERA-BUILD-RAW-PREIMAGE'],['extra acceptance flag',r=>r.outputDeltas[0].approved=true,'ERA-BUILD-RAW-SCHEMA']
])test('assembly refuses '+name,()=>{const r=raw();mutate(r);assert.throws(()=>B.rawDeltas(r,row,matrix),{code});});
test('execution inventory includes immutable parents, source fixtures and the builder; excludes only its own outputs',()=>{const pins=B.executionPins(root);for(const file of [A.FILE,A.STEP_FILE,A.envelopeFile('M2-IMPORT-GUARDS'),A.envelopeFile('M2-STEP-EFFICACY'),B.FIXTURE,'rebuild/conform/v4/postfix/helpers/build-set-one-era-acceptance.cjs'])assert.equal(pins[file],T.sha(fs.readFileSync(path.join(root,file))));assert(!Object.hasOwn(pins,A.ERA_FILE));assert(!Object.hasOwn(pins,A.envelopeFile('M2-SET-ONE-ERA')));});
test('builder CLI cannot issue review receipts or accept an arbitrary input path',()=>{for(const args of [[],['--accept'],['--write','--review','ACCEPTED'],['--raw','arbitrary.json']]){const r=cp.spawnSync(process.execPath,[path.join(root,'rebuild/conform/v4/postfix/helpers/build-set-one-era-acceptance.cjs'),...args],{cwd:root,windowsHide:true,encoding:'utf8',timeout:30000});assert.equal(r.status,1);assert.equal(r.stdout,'');assert.equal(r.stderr.trim(),'ERA ARTIFACT BUILD FAIL ERA-BUILD-ARGS');}});
test('compact canonical bytes have a separate fixed parser; historical pretty parser remains closed',()=>{const value={a:[1,true,null,'x']},compact=Buffer.from(JSON.stringify(value)+'\n'),pretty=Buffer.from(JSON.stringify(value,null,2)+'\n');assert.deepEqual(parseCompactExact(compact),value);assert.deepEqual(parseExact(pretty),value);assert.throws(()=>parseExact(compact),{code:'JSON-NONCANONICAL-BYTES'});assert.throws(()=>parseCompactExact(pretty),{code:'JSON-NONCANONICAL-BYTES'});});
for(const [name,text,code]of [
 ['duplicate key','{"a":1,"a":2}\n','JSON-DUPLICATE-KEY'],['decoded duplicate key','{"a":1,"\\u0061":2}\n','JSON-DUPLICATE-KEY'],['nested duplicate','{"x":[{"a":1,"a":2}]}\n','JSON-DUPLICATE-KEY'],['trailing comma','{"a":1,}\n','JSON-SYNTAX'],['missing LF','{"a":1}','JSON-NONCANONICAL-BYTES'],['alternate whitespace','{ "a":1}\n','JSON-NONCANONICAL-BYTES'],['negative zero','-0\n','JSON-NONCANONICAL-BYTES'],['overflow','1e999\n','JSON-NONCANONICAL-BYTES'],['rounded integer','9007199254740993\n','JSON-NONCANONICAL-BYTES'],['alternate escape','"\\u0061"\n','JSON-NONCANONICAL-BYTES']
])test('compact parser refuses '+name,()=>assert.throws(()=>parseCompactExact(Buffer.from(text)),{code}));
test('compact parser refuses invalid UTF8 without replacement',()=>assert.throws(()=>parseCompactExact(Buffer.from([34,255,34,10])),{code:'JSON-UTF8'}));
test('compact parser refuses a UTF8 BOM and CRLF canonical drift',()=>{for(const b of [Buffer.concat([Buffer.from([239,187,191]),Buffer.from('{}\n')]),Buffer.from('{}\r\n')])assert.throws(()=>parseCompactExact(b),{code:'JSON-NONCANONICAL-BYTES'});});
test('carrier verifies the original parser and exactly reverses its sole formatting projection',()=>{const H=require('../helpers/set-one-era-compact-json.cjs'),bytes=fs.readFileSync(path.join(root,'rebuild/conform/v4/postfix/strict-json.cjs')),projected=H.sourceProjection(bytes);assert.equal(T.sha(bytes),H.ORIGINAL_SHA);assert.equal(projected.split(H.AFTER).length,2);assert(Buffer.from(projected.replace(H.AFTER,H.BEFORE)).equals(bytes));assert.throws(()=>H.sourceProjection(Buffer.concat([bytes,Buffer.from('\n')])),{code:'ERA-JSON-SOURCE-PIN'});assert.throws(()=>H.sourceProjection(Buffer.from(bytes.toString().replace('JSON-DUPLICATE-KEY','IGNORED-KEY'))),{code:'ERA-JSON-SOURCE-PIN'});});
