'use strict';
// Synthetic successor-schema/source tests. No final artifact or product verdict
// is authorized by these fixtures or by their deliberately forged receipts.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const A=require('../acceptance.cjs'),S=require('../source-proof.cjs'),L=require('../legacy-gates.cjs'),T=require('../target.cjs'),P=require('../package-runner.cjs'),CI=require('../ci-second-gate.cjs');
const root=path.resolve(__dirname,'../../../../..'),parent=A.stepParentArtifact(),binding=A.stepParentBinding(),copy=structuredClone;
const line=L.object(root,A.ERA_ANCHOR,'rebuild/DECISIONS.md').toString().split(/\r?\n/)[81];
const original=L.object(root,parent.baseline.auditCommit,S.ERA_FILE).toString('utf8');
const throws=(fn,code)=>assert.throws(fn,e=>e.code===code);
function fixture({present=false}={}){
  const a=copy(parent);Object.assign(a,{packageId:'M2-SET-ONE-ERA',codeBaseAnchor:A.ERA_ANCHOR,requiredIds:A.requiredIds('M2-SET-ONE-ERA'),selectedApprovedFixIds:A.requiredIds('M2-SET-ONE-ERA'),newlySelectedIds:['D30'],carriedAcceptedIds:copy(A.STEP_REQUIRED),acceptedParent:copy(binding),contracts:[...a.contracts,copy(A.ERA_CONTRACT)],caseModule:'rebuild/conform/v4/postfix/laws/set-one-era.cjs',helperFiles:{hosts:'rebuild/conform/v4/postfix/helpers/set-one-era-frozen.cjs',frozen:'rebuild/conform/v4/postfix/helpers/set-one-era-frozen.cjs'}});
  a.authorizations.theme={role:'cowork',line,lineSha256:T.sha(line)};a.authorizations.review={role:'cowork',prefix:'POSTFIX-ACCEPTANCE M2-SET-ONE-ERA',terminal:'ACCEPTED'};
  const r=a.inventory.find(r=>r.defect==='D30');r.themeAcceptance='theme';for(const c of r.rawExpectations)c.candidateStatus='GREEN';
  if(present){r.implementation='PRESENT';r.sourceDeltas=['source-setOneRead','binding-forksOf','binding-sameEra'];a.sourceChanges.push(...S.proposeSetOneEraChanges(original));a.candidateEngine['volume.cjs']=T.sha(S.applySetOneEraChanges(original,a.sourceChanges.slice(6)));}return a;
}
function envelope(a){const e=JSON.parse(fs.readFileSync(path.join(root,binding.operational.file)));e.acceptanceFile=A.artifactFile(a);e.acceptanceSha256=T.sha(JSON.stringify(a,null,2)+'\n');e.candidateBase=A.ERA_ANCHOR;
  for(const k of ['owner','contract','theme'])e.receipts[k]={commit:A.ERA_ANCHOR,path:'rebuild/DECISIONS.md',line:a.authorizations[k].line,lineSha256:a.authorizations[k].lineSha256};e.receipts.review={status:'PENDING',receipt:null};return e;}
test('ERA is an enumerated cumulative profile; empty future evidence cannot become complete',()=>{const a=fixture();A.validate(a);assert.deepEqual(a.requiredIds,['D30','D12','D33','D34','D35']);assert.equal(a.inventory.length,45);assert.equal(a.nonD.length,15);assert.equal(a.gates.length,19);assert.equal(a.inventory.filter(r=>r.implementation==='PRESENT').length,4);assert(A.missing(a).includes('D30 implementation pending'));assert(A.missing(a).some(x=>x.includes('six inherited')));});
test('nine source edits alone still leave cases, deltas and mutants pending',()=>{const a=fixture({present:true});A.validate(a);assert.equal(a.sourceChanges.length,9);assert(A.missing(a).includes('D30 cases pending'));assert(A.missing(a).includes('D30 mutants pending'));assert(A.missing(a).includes('D30 outputDeltas pending'));});
test('actual STEP/import parent artifacts retain their old schema behavior',()=>{A.validate(parent);A.validate(A.parentArtifact());assert.equal(A.artifactFile(parent),A.STEP_FILE);assert.equal(A.envelopeFile('M2-SET-ONE-ERA'),'rebuild/conform/v4/postfix/manifest-set-one-era.json');throws(()=>A.profile('M2-SET-ONE-ERA-CUSTOM'),'PACKAGE-INVENTORY');});
for(const [name,change,code]of [
  ['old anchor',a=>a.codeBaseAnchor=parent.codeBaseAnchor,'PACKAGE-INVENTORY'],['extra selected repair',a=>a.newlySelectedIds.push('D31'),'PACKAGE-INVENTORY'],['lost carried D12',a=>a.carriedAcceptedIds.shift(),'PACKAGE-INVENTORY'],['reordered union',a=>a.requiredIds.reverse(),'PACKAGE-INVENTORY'],
  ['parent artifact hash',a=>a.acceptedParent.artifact.sha256='0'.repeat(64),'ACCEPTED-PARENT-BINDING'],['parent receipt prose',a=>a.acceptedParent.receipt.line+=' accepted','ACCEPTED-PARENT-BINDING'],['parent candidate',a=>a.acceptedParent.candidateCommit=A.ERA_ANCHOR,'ACCEPTED-PARENT-BINDING'],['extra parent trust field',a=>a.acceptedParent.trust=true,'ACCEPTED-PARENT-BINDING'],
  ['altered STEP source',a=>a.sourceChanges[5].after+='\n','INHERITED-SOURCE-CHANGES'],['partial new source set',a=>a.sourceChanges.push(S.proposeSetOneEraChanges(original)[0]),'INHERITED-SOURCE-CHANGES'],['lost inherited case',a=>a.inventory.find(r=>r.defect==='D12').cases.pop(),'CARRIED-OR-UNSELECTED-INVENTORY'],['lost inherited fault',a=>a.inventory.find(r=>r.defect==='D33').mutants.pop(),'CARRIED-OR-UNSELECTED-INVENTORY'],
  ['changed D45 custody',a=>a.inventory.find(r=>r.defect==='D45').consequence=null,'CARRIED-OR-UNSELECTED-INVENTORY'],['changed D27 fixture outcome',a=>a.inventory.find(r=>r.defect==='D27').rawExpectations[2].candidateStatus='RED','CARRIED-OR-UNSELECTED-INVENTORY'],['changed D44 exception',a=>a.inventory.find(r=>r.defect==='D44').rawExpectations[2].exception.name='Error','CARRIED-OR-UNSELECTED-INVENTORY'],['unselected delta permission',a=>a.inventory.find(r=>r.defect==='D31').outputDeltas.push({ignored:true}),'CARRIED-OR-UNSELECTED-INVENTORY'],
  ['D30 raw stays RED',a=>a.inventory.find(r=>r.defect==='D30').rawExpectations[0].candidateStatus='RED','RAW-EXPECTATION-OUTCOME'],['D30 raw law renamed',a=>a.inventory.find(r=>r.defect==='D30').law.id='V4-D30-SET-ONE-ERA','RAW-LAW-PIN'],['old theme receipt',a=>a.authorizations.theme=copy(parent.authorizations.theme),'THEME-AUTHORIZATION-PIN'],['old review prefix',a=>a.authorizations.review=copy(parent.authorizations.review),'REVIEW-CLAIM'],
  ['another contract hash',a=>a.contracts[3].sha256='0'.repeat(64),'CONTRACT-PIN'],['arbitrary law import path',a=>a.caseModule='rebuild/conform/v4/postfix/laws/other.cjs','THEME-PATH'],['arbitrary helper',a=>a.helperFiles.hosts=parent.helperFiles.hosts,'HELPER-PATH'],['nonD omitted',a=>a.nonD.pop(),'NON-D-INVENTORY'],['gate omitted',a=>a.gates.pop(),'GATE-OR-MODE-INVENTORY'],
])test('ERA refuses '+name,()=>{const a=fixture();change(a);throws(()=>A.validate(a),code);});
test('actual ancestor receipts verify but do not accept the new pending package',()=>{const a=fixture();assert.equal(A.verifyAcceptedParent(root,a).packageId,'M2-STEP-EFFICACY');assert.equal(A.verifyReceipts(root,a,envelope(a),Buffer.from(JSON.stringify(a,null,2)+'\n')),false);});
test('synthetic terminal wording cannot manufacture an actual ERA acceptance receipt',()=>{const a=fixture(),e=envelope(a),line='- synthetic · cowork · POSTFIX-ACCEPTANCE M2-SET-ONE-ERA '+A.ERA_ANCHOR+' '+A.ERA_FILE+' '+e.acceptanceSha256+' ACCEPTED';e.receipts.review={status:'ACCEPTED',receipt:{commit:A.ERA_ANCHOR,path:'rebuild/DECISIONS.md',line,lineSha256:T.sha(line)}};A.envelope(e);throws(()=>A.verifyReceipts(root,a,e,Buffer.from(JSON.stringify(a,null,2)+'\n')),'RECEIPT-EXACT-LINE-MISSING');});
test('actual parent ACCEPTED receipt cannot authorize ERA',()=>{const a=fixture(),e=envelope(a);e.receipts.review={status:'ACCEPTED',receipt:{...copy(binding.receipt),commit:A.ERA_ANCHOR}};throws(()=>A.verifyReceipts(root,a,e,Buffer.from(JSON.stringify(a,null,2)+'\n')),'REVIEW-EXACT-VERDICT');});
test('missing review receipt cannot coexist with ACCEPTED',()=>{const e=envelope(fixture());e.receipts.review.status='ACCEPTED';throws(()=>A.envelope(e),'REVIEW-STATUS-CONTRADICTION');});
test('ERA source construction changes exactly the declaration and two bound delegates',()=>{const changes=S.proposeSetOneEraChanges(original),after=S.applySetOneEraChanges(original,changes);assert.equal(after,original.replace(S.ERA_BINDING,S.ERA_BINDING+'const forksOf = (...args) => E.forksOf(...args);\nconst sameEra = (...args) => E.sameEra(...args);\n').replace(S.ERA_GUARD,S.ERA_GUARD+S.ERA_QUERY).replace(S.ERA_LOOP,S.ERA_LOOP+S.ERA_SKIP));assert.deepEqual(S.proposeSetOneEraChanges(original,after),changes);});
for(const [name,change,code]of [
  ['missing delegate',d=>d.pop(),'ERA-SOURCE-INVENTORY'],['extra delegate',d=>d.push(copy(d[1])),'ERA-SOURCE-INVENTORY'],['wrong source file',d=>d[0].file='rebuild/engine/plan.cjs','ERA-SOURCE-SCHEMA'],['unconditional clock',d=>{d[0].after=d[0].after.replace('forks.length ? isoOf(todayStart()) : null','isoOf(todayStart())');d[0].afterSha256=T.sha(d[0].after);},'ERA-DECLARATION-SCOPE'],['future cutoff',d=>{d[0].after=d[0].after.replace(S.ERA_SKIP,S.ERA_SKIP+'    if (d > at) continue;\n');d[0].afterSha256=T.sha(d[0].after);},'ERA-DECLARATION-SCOPE'],['changed binding receiver',d=>{d[1].after=d[1].after.replace('E.forksOf','E.other');d[1].afterSha256=T.sha(d[1].after);},'ERA-BINDING-SCOPE'],['relocated declaration',d=>d[0].start++,'ERA-SOURCE-PREIMAGE-SCOPE'],['relocated delegate',d=>{d[1].start++;d[1].end++;},'ERA-SOURCE-PREIMAGE-SCOPE']
])test('closed volume source proof refuses '+name,()=>{const d=S.proposeSetOneEraChanges(original);change(d);throws(()=>S.applySetOneEraChanges(original,d),code);});
test('extra full-file source change remains forbidden',()=>{const after=S.applySetOneEraChanges(original,S.proposeSetOneEraChanges(original));throws(()=>S.proposeSetOneEraChanges(original,after+'\n'),'UNAPPROVED-SOURCE-DELTA');});
test('raw identity remains fixed while direct ERA/STEP dispatch is explicitly mapped',()=>{const a=fixture();assert.equal(P.directLawId(a,a.inventory.find(r=>r.defect==='D30')),'V4-D30-SET-ONE-ERA');assert.equal(P.directLawId(a,a.inventory.find(r=>r.defect==='D12')),'V4-D12-STEP-EFFICACY');assert.equal(a.inventory.find(r=>r.defect==='D30').law.id,'P-D30-first-set-trend-respects-the-recorded-technique-era');});
test('closed carrier dispatch preserves19 identities/28 invocations and only one witness4/second gate',()=>{const a=fixture(),spec=P.carrierProfile(a),gates=require('../run.cjs').GATES;assert.equal(gates.length,19);let n=0;for(const g of gates){const id=P.carrierId(g[0],true,true);n+=spec.ids.includes(id)?P.carrierModes(a,id).length:1;}assert.equal(n,28);assert.deepEqual(P.carrierModes(a,'defect-witnesses-4'),['frozen']);assert.deepEqual(P.carrierModes(a,'second-gate'),['frozen']);assert.deepEqual(P.carrierModes(a,'writers-differential'),['frozen','native','trap']);assert.equal(spec.ids.length,10);assert.equal(P.carrierId('witnesses-4',true,false),'witnesses-4');});
test('CI accepts only the two exact inherited/current profile spellings',()=>{assert.equal(CI.args(['--profile','M2-SET-ONE-ERA']),'M2-SET-ONE-ERA');assert.equal(CI.args(['--profile','M2-STEP-EFFICACY']),'M2-STEP-EFFICACY');for(const args of [[],['--profile','M2-ANY'],['--profile','M2-SET-ONE-ERA','--skip']])throws(()=>CI.args(args),'CI-PROFILE');});
const scratchParent=path.join(root,'.tmp/postfix/era-profile-tests');fs.mkdirSync(scratchParent,{recursive:true});const scratch=fs.mkdtempSync(path.join(scratchParent,'source-'));
test.after(()=>{assert(path.resolve(scratch).startsWith(path.resolve(scratchParent)+path.sep));fs.rmSync(scratch,{recursive:true,force:true});});
test('whole-source proof checks original plus both accepted parents and refuses disk/HEAD discrepancy',()=>{
  cp.execFileSync('git',['clone','--shared','--no-checkout','--quiet',root,scratch],{windowsHide:true,stdio:['ignore','pipe','pipe']});cp.execFileSync('git',['-C',scratch,'update-ref','--no-deref','HEAD',A.ERA_ANCHOR],{windowsHide:true,stdio:['ignore','pipe','pipe']});
  const write=(p,b)=>{const f=path.join(scratch,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,b);},a=fixture({present:true}),importBinding=A.parentBinding();
  for(const pin of [binding.artifact,binding.operational,importBinding.artifact,importBinding.operational])write(pin.file,L.object(root,pin.commit,pin.file));
  for(const file of Object.keys(parent.candidateEngine))write('rebuild/engine/'+file,L.object(root,binding.candidateCommit,'rebuild/engine/'+file));write(S.ERA_FILE,S.applySetOneEraChanges(original,a.sourceChanges.slice(6)));
  assert.equal(S.verifyProductSources({root:scratch,baseline:root,acceptance:a,gitHead:false}).changes.length,9);throws(()=>S.verifyProductSources({root:scratch,baseline:root,acceptance:a,gitHead:true}),'UNCOMMITTED-PRODUCT-PIN');fs.appendFileSync(path.join(scratch,'rebuild/engine/plan.cjs'),'\n');throws(()=>S.verifyProductSources({root:scratch,baseline:root,acceptance:a,gitHead:false}),'UNAPPROVED-SOURCE-DELTA');
});
test('only the fixed ERA artifact loader accepts compact bytes; byte pins still bind every character',()=>{const a=fixture(),e=envelope(a),bytes=Buffer.from(JSON.stringify(a)+'\n'),file=path.join(scratch,A.ERA_FILE),manifest=path.join(scratch,'synthetic-compact-envelope.json');fs.mkdirSync(path.dirname(file),{recursive:true});e.acceptanceSha256=T.sha(bytes);fs.writeFileSync(file,bytes);fs.writeFileSync(manifest,JSON.stringify(e,null,2)+'\n');assert.equal(A.load(scratch,manifest).acceptance.packageId,'M2-SET-ONE-ERA');fs.appendFileSync(file,' ');throws(()=>A.load(scratch,manifest),'ACCEPTANCE-BYTE-PIN');fs.writeFileSync(file,JSON.stringify(a,null,2)+'\n');e.acceptanceSha256=T.sha(fs.readFileSync(file));fs.writeFileSync(manifest,JSON.stringify(e,null,2)+'\n');throws(()=>A.load(scratch,manifest),'JSON-NONCANONICAL-BYTES');});
test('compact bytes cannot enter either historical profile or an operational envelope',()=>{const e=envelope(fixture()),manifest=path.join(scratch,'synthetic-cross-profile.json');for(const a of [parent,A.parentArtifact()]){const file=path.join(scratch,A.artifactFile(a)),bytes=Buffer.from(JSON.stringify(a)+'\n');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,bytes);e.acceptanceFile=A.artifactFile(a);e.acceptanceSha256=T.sha(bytes);fs.writeFileSync(manifest,JSON.stringify(e,null,2)+'\n');throws(()=>A.load(scratch,manifest),'JSON-NONCANONICAL-BYTES');}fs.writeFileSync(manifest,JSON.stringify(e)+'\n');throws(()=>A.load(scratch,manifest),'JSON-NONCANONICAL-BYTES');});
