'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const B=require('../helpers/build-step-efficacy-expectations.cjs'),M=require('../laws/step-efficacy.cjs'),Parent=require('../laws/import-guards.cjs'),T=require('../target.cjs'),S=require('../structural-delta.cjs');
const root=path.resolve(__dirname,'../../../../..'),base=require('../manifest.json');let source;
function get(){return source||(source=B.createFrozenSource({root}));}
const trace=r=>({frames:r.frames,detail:r.detail});
function input(caseId){const src=get(),pins={...base.baseline.publicPins};for(const f of ['helpers/step-efficacy-frozen.cjs','helpers/import-guards-frozen.cjs','helpers/import-guards-hosts.cjs','laws/import-guards.cjs']){const rel='rebuild/conform/v4/postfix/'+f;pins[rel]=B.sha(fs.readFileSync(path.join(root,rel)));}const file=path.join(root,'rebuild/conform/v4/postfix/laws/step-efficacy.cjs');return{kind:'direct-frozen',bundle:src.bundle,bundleSha256:src.bundleSha256,frozenHelper:'rebuild/conform/v4/postfix/helpers/step-efficacy-frozen.cjs',hostsHelper:'rebuild/conform/v4/postfix/helpers/step-efficacy-frozen.cjs',helperRoot:root,helperPins:pins,caseFile:file,caseSha256:B.sha(fs.readFileSync(file)),lawId:M.D12.id,caseId,traceProfile:2,mode:'frozen',day:'2026-09-03'};}
test('only explicit frozen source receipt; caller cannot supply candidate bundle',()=>{assert.throws(()=>B.createFrozenSource({root,bundle:path.join(root,'rebuild/engine')}),/FROZEN-ONLY/);});
test('pointing source authoring at the extracted engine directory refuses before reading product',()=>{assert.throws(()=>B.createFrozenSource({root:path.join(root,'rebuild/engine')}),/SE12-EXPECTED-REPO/);});
test('parent case/assertion/law inventory is inherited unchanged',()=>{assert.deepEqual(M.CASES.filter(c=>c.defect!=='D12'),Parent.CASES);assert.deepEqual(M.ASSERTION_INVENTORY.filter(c=>c.defect!=='D12'),Parent.ASSERTION_INVENTORY);assert.deepEqual(M.laws.slice(1),Parent.laws);assert.equal(new Set(M.INVENTORY).size,M.INVENTORY.length);});
test('invented inherited offer uses actual frozen writer prose/payload and coherent Monday identity',()=>{const H=require('../helpers/step-efficacy-frozen.cjs');for(const day of ['2026-09-03','2026-09-07']){const T=H.createFrozenEngine({root,bundle:get().bundle,clock:{today:()=>day,nowMs:()=>Date.parse(day+'T16:00:00Z')},drafts:{length:0,key(){return null;}}}),c={T,day,hosts:H.createHosts({root,engine:T,record(){}})},s=M.FIXTURE.consumer(c,'NEGATIVE'),out=T.runAdaptive(s,day),actual=out.proposals.find(p=>p.rid.startsWith('steppush_')),inherited=M.FIXTURE.legacyOffer(c);assert.ok(actual);for(const key of ['rid','title','why','apply','resolved','pg'])assert.deepEqual(inherited[key],actual[key]);assert.equal(inherited.d,inherited.rid.slice(9));assert.equal(inherited.id,inherited.rid+'_'+inherited.d);}});
test('exact actual frozen target agrees with source-only unprojected producer',async()=>{const a=await B.produce({source:get(),caseId:'SE12-POSITIVE',mode:'frozen',day:'2026-09-03'}),b=await T.worker(input('SE12-POSITIVE'));assert.deepEqual(trace(a),trace(b));assert.equal(a.status,'RED');});
test('source projection fixes dimensional claim and retains negative zero in typed trace',async()=>{const r=await B.produce({source:get(),caseId:'SE12-TINY-NEGATIVE-LIVE',mode:'native',day:'2026-09-07',project:true});assert.equal(r.status,'GREEN');assert.match(JSON.stringify(r.frames),/\["number","-0"\]/);});
test('arbitrary fabricated source receipt is refused',async()=>{await assert.rejects(B.produce({source:{...get()},caseId:'SE12-POSITIVE',mode:'frozen',day:'2026-09-03'}),/EXPECTED-RECEIPT/);});
test('exact cells reject unlisted receipt/value changes',async()=>{const args={source:get(),caseId:'SE12-LAB-POSITIVE',mode:'frozen',day:'2026-09-03'},a=trace(await B.produce(args)),b=trace(await B.produce({...args,project:true})),delta=B.exactCells(a,b,args.caseId);S.compareStructural(a,b,delta);const wrong=structuredClone(b);wrong.frames[0].name='unlisted';assert.throws(()=>S.compareStructural(a,wrong,delta));});
test('parent source pin is mandatory for the only permitted successor import',async()=>{const i=input('SE12-POSITIVE');i.helperPins['rebuild/conform/v4/postfix/laws/import-guards.cjs']='0'.repeat(64);await assert.rejects(T.worker(i),/HELPER-SOURCE-PIN/);});
// Fail before source execution: path-specific policy has exactly one allowed import.
for(const request of ['node:fs','./unknown.cjs','../helpers/import-guards-frozen.cjs'])test('direct arbitrary import remains forbidden: '+request,()=>{
 const source=fs.readFileSync(path.join(root,'rebuild/conform/v4/postfix/target.cjs'),'utf8');const start=source.indexOf('const successor='),end=source.indexOf('const law=mod.laws',start);const body=source.slice(start,end);
 const compile=(_file,req)=>req(request);assert.throws(()=>new Function('path','input','compile','pinnedHelper','fail',body)(path,{caseFile:path.join(root,'rebuild/conform/v4/postfix/laws/step-efficacy.cjs'),helperRoot:root},compile,()=>{throw Error('UNEXPECTED-HELPER');},code=>{throw Error(code);}),/DIRECT-CASE-IMPORT/);
});
