'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),Module=require('node:module'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../../../../..'),base=path.join(root,'.tmp/er-native-capture'),HP=path.join(root,'rebuild/m4/workout/test/b1b2-evidence.cjs'),OP=path.join(root,'rebuild/lanes/b/tooling/b1b2-native-capture.cjs');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),HS=fs.readFileSync(HP,'utf8'),OS=fs.readFileSync(OP,'utf8');assert.equal(hash(HS),'73a075ea7792cdb716ca0129928ab4206f4537a29b9d9b41c49796176df5c398');assert.equal(hash(OS),'0dcbab59bda0d78a6933630d69740a39a8bb923c8337022500b317749e94b70d');
const records=[],controls=[];fs.mkdirSync(base,{recursive:true});
const child=path.join(base,'independent-child.cjs');
fs.writeFileSync(child,String.raw`'use strict';
const fs=require('node:fs'),path=require('node:path'),H=require(process.env.ER_NATIVE_HELPER),mode=process.env.ER_NATIVE_MODE,dir=process.env.EARNED_B1B2_CAPTURE_DIR;
const observations=()=>{const a=Object.fromEntries(H.READERS.map(k=>[k,{value:1}]));H.approvedNativeDifference('second-readers',a,structuredClone(a));H.approvedNativeDifference('second-applyRead',{reads:[],trend:1},{reads:[],trend:1});return a;};
if(mode.startsWith('manual-')){
 if(mode==='manual-pending'){const rows=['second-readers','second-applyRead'].map((kind,i)=>({v:1,seq:i+1,kind,categories:[],differenceCount:0,comparisonVerdict:'MATCH'}));fs.writeFileSync(path.join(dir,'native-diagnostics.jsonl'),rows.map(x=>JSON.stringify(x)+'\n').join(''));}
 else observations();
 const directive=mode==='manual-skip'?' # SKIP invented':mode==='manual-todo'?' # TODO invented':'';
 process.stdout.write('TAP version 13\nok 1 - invented'+directive+'\nok 2 - invented\nok 3 - invented\nok 4 - invented\n'+(mode==='manual-bailout'?'Bail out! invented\n':'')+'1..4\n# tests 4\n# suites 0\n# pass 4\n# fail 0\n# cancelled 0\n# skipped 0\n# todo 0\n# duration_ms 1\n');
}else{
 const test=require('node:test');for(let i=1;i<=3;i++)test('ER unchanged synthetic '+i,()=>{});
 test('ER actual observation lifecycle',()=>{const a=observations();if(mode==='before-exit')H.approvedNativeDifference('second-readers',a,a);if(mode==='late-exit')process.once('exit',()=>{const marker=path.join(dir,'capture-manifest.json'),before=fs.existsSync(marker);H.approvedNativeDifference('second-readers',a,a);fs.writeFileSync(path.join(dir,'er-late-reach.json'),JSON.stringify({called:true,completionMarkerBefore:before,completionMarkerAfter:fs.existsSync(marker)}));});});
}
`);
function operator(mode,source=OS){const m=new Module(OP,module);m.filename=OP;m.paths=Module._nodeModulePaths(path.dirname(OP));const real=m.require.bind(m);m.require=n=>{assert(['node:fs','node:path','node:child_process','node:crypto','node:string_decoder'].includes(n));if(n!=='node:child_process')return real(n);return {...cp,spawn(exe,args,options){assert.equal(exe,process.execPath);assert.deepEqual(args,['--test','--test-reporter=tap','rebuild/m4/workout/test/b1b2-supersede-second-gate.test.cjs']);assert.equal(options.cwd,root);assert.deepEqual(options.stdio,['ignore','pipe','pipe']);const env={...options.env,ER_NATIVE_HELPER:HP,ER_NATIVE_MODE:mode};delete env.NODE_TEST_CONTEXT;return cp.spawn(exe,mode.startsWith('manual-')?[child]:['--test','--test-reporter=tap',child],{...options,env});}};};m._compile(source,OP);return m.exports;}
async function capture(mode,source=OS){const op=operator(mode,source),dir=op.createDirectory(),result=await op.capture(dir);const rec={mode,operatorSha256:hash(source),helperSha256:hash(HS),directory:path.relative(root,dir),result,privateManifest:JSON.parse(fs.readFileSync(path.join(dir,'capture-manifest.json'))),rawStdout:fs.readFileSync(path.join(dir,'stdout.raw'),'utf8'),rawStderr:fs.readFileSync(path.join(dir,'stderr.raw'),'utf8'),syntheticOnly:true};if(fs.existsSync(path.join(dir,'er-late-reach.json')))rec.lateReach=JSON.parse(fs.readFileSync(path.join(dir,'er-late-reach.json')));records.push(rec);return rec;}
function helper(dir,source=HS){const m=new Module(HP,module);m.filename=HP;m.paths=Module._nodeModulePaths(path.dirname(HP));const proc=Object.create(process),exits=[];proc.env={...process.env,EARNED_B1B2_CAPTURE_DIR:dir};proc.once=(event,fn)=>{assert.equal(event,'exit');exits.push(fn);return proc;};const real=m.require.bind(m);m.require=n=>{assert(['node:assert/strict','node:fs','node:path','node:child_process','node:crypto','node:module','./b1b2-source-changes.json'].includes(n));return real(n);};m.__process=proc;m._compile('const process=module.__process;\n'+source,HP);return {...m.exports,finish(){for(const f of exits)f();}};}
function pair(h){const a=Object.fromEntries(h.READERS.map(k=>[k,{value:1}]));return [a,structuredClone(a)];}
test('ER real child with two observations has complete capture',async()=>{const r=await capture('normal');assert.equal(r.result.captureVerdict,'PASS');assert.equal(r.result.pass,4);assert.equal(r.result.childExit,0);});
test('ER observation before natural exit makes capture fail while gate stays green',async()=>{const r=await capture('before-exit');assert.equal(r.result.gateVerdict,'PASS');assert.equal(r.result.childExit,0);assert.equal(r.result.captureVerdict,'FAIL');});
test('ER observation in a later exit listener must keep capture failed',async()=>{const r=await capture('late-exit');assert.equal(r.result.gateVerdict,'PASS');assert.equal(r.result.childExit,0);assert.equal(r.lateReach.called,true);assert.equal(r.result.captureVerdict,'FAIL','ER-LATE-EXIT must retain the observer failure after completion listener');});
test('ER canonical invented manual census remains a positive control',async()=>{const r=await capture('manual-good');assert.equal(r.result.captureVerdict,'PASS');});
for(const mode of ['manual-skip','manual-todo','manual-bailout'])test('ER contradictory TAP '+mode+' must refuse capture',async()=>{const r=await capture(mode);assert.equal(r.result.childExit,0);assert.equal(r.result.captureVerdict,'FAIL','ER-TAP-CONSISTENCY must reject '+mode+' despite a forged all-pass trailer');});
test('ER real hardlink on diagnostics cannot pass capture',async()=>{const op=operator('manual-pending'),dir=op.createDirectory(),h=helper(dir),[a,b]=pair(h);h.approvedNativeDifference('second-readers',a,b);fs.linkSync(path.join(dir,'native-diagnostics.jsonl'),path.join(dir,'er-diagnostic-link'));h.approvedNativeDifference('second-applyRead',{},{});h.finish();assert(fs.existsSync(path.join(dir,'capture-manifest.json')));assert.equal(fs.statSync(path.join(dir,'native-diagnostics.jsonl')).nlink,2);});
async function reversal(id,source,anchor,replacement,check){assert.equal(source.split(anchor).length,2);await check(source);const changed=source.replace(anchor,replacement);let caught;try{await check(changed);}catch(e){caught=e;}assert(caught&&caught.code==='ERR_ASSERTION'&&caught.message.includes(id),id+' exact reviewer assertion must fail; no setup/loader credit');await check(source);controls.push({id,originalSha256:hash(source),mutantSha256:hash(changed),anchor,replacement,mutantFailure:{name:caught.name,code:caught.code,message:caught.message},baselinePassed:true,freshRestoredPassed:true,originalDiskUnchanged:true});}
test('ER four actual guard reversals lose their named assertion and restore',async()=>{
 await reversal('ER-HOOK-OBSERVATION',HS,'  observeNativeDifference(kind,actual,before,after);','  // deliberate observer removal',async source=>{const dir=operator('normal').createDirectory(),h=helper(dir,source),[a,b]=pair(h);h.approvedNativeDifference('second-readers',a,b);assert.equal(fs.existsSync(path.join(dir,'native-diagnostics.jsonl')),true,'ER-HOOK-OBSERVATION');});
 await reversal('ER-COMPLETION-REFUSAL',OS,"need(!fs.existsSync(path.join(dir,'capture-manifest.json'))&&observed.length===2,'DIAGNOSTIC');",'/* deliberate completion guard removal */',async source=>{const r=await capture('manual-pending',source);assert.equal(r.result.captureVerdict,'FAIL','ER-COMPLETION-REFUSAL');});
 await reversal('ER-OUTPUT-WHITELIST',HS,'id=matches[0];}', 'id=p;}',async source=>{const dir=operator('normal').createDirectory(),h=helper(dir,source),[a,b]=pair(h);b.nowModel={ER_CAPTURE_SECRET_KEY:2};assert.throws(()=>h.approvedNativeDifference('second-readers',a,b),{code:'ERR_ASSERTION'});const raw=fs.readFileSync(path.join(dir,'native-diagnostics.jsonl'),'utf8');assert.equal(raw.includes('ER_CAPTURE_SECRET_KEY'),false,'ER-OUTPUT-WHITELIST');});
 await reversal('ER-FIRST-FAILURE',HS,"  assert.equal(JSON.stringify(actual)===JSON.stringify(approved),true,'exact admitted native field deltas '+kind+'; measured '+actual.length+' (values retained process-locally)');",'  /* deliberate first-failure assertion removal */',async source=>{const dir=operator('normal').createDirectory(),h=helper(dir,source),[a,b]=pair(h);b.nowModel.value=2;let writerReached=false;try{h.approvedNativeDifference('second-readers',a,b);writerReached=true;}catch(e){assert.equal(e.code,'ERR_ASSERTION');assert(e.message.startsWith('exact admitted native field deltas'));}assert.equal(writerReached,false,'ER-FIRST-FAILURE');});
});
test.after(()=>{assert.equal(hash(fs.readFileSync(HP)),hash(HS));assert.equal(hash(fs.readFileSync(OP)),hash(OS));fs.writeFileSync(path.join(base,'independent-evidence.json'),JSON.stringify({candidate:'f9e45f922bcb489d8ef4a4eded83b968356f16e4',records,controls,originalNativeInvoked:false,protectedInputsRead:false,authorOutcomesRead:false},null,2)+'\n');});
