'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../../../..'),base=path.join(root,'.tmp/er-native-capture'),dest=path.join(root,'.tmp/reviewer-identity/work/pm-caretaker/b1b2-native-capture'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const pre=JSON.parse(fs.readFileSync(path.join(base,'source-audit.json'))),rows=pre.manifest.inputs.filter(x=>x.role==='candidate');assert.equal(rows.length,6);assert.equal(process.version,'v22.23.2');assert.equal(sha(fs.readFileSync(process.execPath)),pre.node.sha256);
function contained(p,file=false){assert(p.startsWith(root+path.sep));let d=file?path.dirname(p):p;for(;;){const s=fs.lstatSync(d);assert(s.isDirectory()&&!s.isSymbolicLink());assert.equal(fs.realpathSync(d).toLowerCase(),d.toLowerCase());if(d===root)break;d=path.dirname(d);}if(file){const s=fs.lstatSync(p);assert(s.isFile()&&!s.isSymbolicLink()&&s.nlink===1);}}
function check(){contained(dest);for(const row of rows){const p=path.join(dest,row.path);contained(p,true);assert.equal(sha(fs.readFileSync(p)),row.sha256,row.path);}const runtime=path.join(dest,'.tmp/runtime/node.exe');contained(runtime,true);assert.equal(sha(fs.readFileSync(runtime)),pre.node.sha256);for(const p of ['.git','rebuild/engine/seed.cjs','rebuild/conform/engines/engine-main.cjs','rebuild/m4/workout/test/h3-supersede-second-gate.test.cjs','ledger/state.json','src/app.jsx','rebuild/lanes/b/BUILD-B1B2-NATIVE-CAPTURE.md'])assert(!fs.existsSync(path.join(dest,p)));assert.equal(cp.execFileSync('git',['rev-parse','--show-toplevel'],{cwd:dest,windowsHide:true,encoding:'utf8'}).trim().replace(/\\/g,'/').toLowerCase(),root.replace(/\\/g,'/').toLowerCase());return runtime;}
if(process.argv[2]==='prepare'){
 assert(!fs.existsSync(dest));fs.mkdirSync(dest,{recursive:true});contained(dest);
 for(const row of rows){const b=fs.readFileSync(path.join(root,row.path));assert.equal(sha(b),row.sha256);const p=path.join(dest,row.path);fs.mkdirSync(path.dirname(p),{recursive:true});contained(path.dirname(p));fs.writeFileSync(p,b,{flag:'wx'});}
 const runtime=path.join(dest,'.tmp/runtime/node.exe');fs.mkdirSync(path.dirname(runtime),{recursive:true});contained(path.dirname(runtime));fs.copyFileSync(process.execPath,runtime,fs.constants.COPYFILE_EXCL);check();
 fs.writeFileSync(path.join(base,'identity-copy-manifest.json'),JSON.stringify({candidate:pre.candidate,destination:dest,gitMetadataRoot:root,inputs:rows,nodeSha256:pre.node.sha256,canonicalNoLinks:true,scope:'PM336 clarification: synthetic identity transport, exact six public input copies, original child STATIC ONLY; no original native/operator invocation.'},null,2)+'\n');console.log(JSON.stringify({prepared:true,destination:dest,copies:6,nodeSha256:pre.node.sha256}));
}else{
 assert.equal(process.argv[2],'run');assert.equal(process.argv[3],'closure-inspected');const runtime=check();
 const env={...process.env,TZ:'America/New_York',TEMP:path.join(dest,'.tmp/temp'),TMP:path.join(dest,'.tmp/temp')};fs.mkdirSync(env.TEMP,{recursive:true});
 for(const k of Object.keys(env))if(/^(NODE_OPTIONS|NODE_PATH|NODE_TEST_CONTEXT|NODE_TEST_WORKER_ID|NODE_V8_COVERAGE|V8_COVERAGE|V8_FLAGS|EARNED_B1B2_CAPTURE_COMMISSION|EARNED_B1B2_CAPTURE_DIR|MEASURED_TEST_NOW|PL_ENGINE|PL_LAWS_LIB)$/i.test(k))delete env[k];
 const rooted=process.argv[4]==='metadata-root',prefix=rooted?'identity-rooted':'identity';assert(process.argv[4]===undefined||rooted);
 if(rooted){
  const priorEvidence=path.join(dest,'.tmp/native-capture-tests/public-evidence.json');fs.copyFileSync(priorEvidence,path.join(base,'identity-first-public-evidence.json'),fs.constants.COPYFILE_EXCL);
  const captureRoot=path.join(dest,'.tmp/b1b2-native-capture'),priorCaptures=fs.readdirSync(captureRoot).map(id=>{assert(/^[0-9a-f]{32}$/.test(id));const dir=path.join(captureRoot,id);contained(dir);return {id,manifest:JSON.parse(fs.readFileSync(path.join(dir,'capture-manifest.json'))),stdout:fs.readFileSync(path.join(dir,'stdout.raw'),'utf8'),stderr:fs.readFileSync(path.join(dir,'stderr.raw'),'utf8')};});fs.writeFileSync(path.join(base,'identity-first-captures.json'),JSON.stringify(priorCaptures,null,2)+'\n');
  env.GIT_DIR=cp.execFileSync('git',['rev-parse','--absolute-git-dir'],{cwd:root,windowsHide:true,encoding:'utf8'}).trim();env.GIT_WORK_TREE=dest;
  assert.equal(cp.execFileSync('git',['rev-parse','--show-toplevel'],{cwd:dest,env,windowsHide:true,encoding:'utf8'}).trim().replace(/\\/g,'/').toLowerCase(),dest.replace(/\\/g,'/').toLowerCase());
  assert.equal(cp.execFileSync('git',['rev-parse','--show-prefix'],{cwd:dest,env,windowsHide:true,encoding:'utf8'}).trim(),'');
  assert.equal(cp.execFileSync('git',['rev-parse','HEAD'],{cwd:dest,env,windowsHide:true,encoding:'utf8'}).trim(),pre.candidate);
 }
 const argv=['--test','--test-reporter=tap','--test-name-pattern=production identity/argv/root checks|actual main emits only safe schema|actual main success','rebuild/lanes/b/tooling/test/b1b2-native-capture.test.cjs'],start=new Date().toISOString(),t=performance.now();
 const r=cp.spawnSync(runtime,argv,{cwd:dest,env,windowsHide:true,encoding:'utf8',maxBuffer:4*1024*1024});
 fs.writeFileSync(path.join(base,prefix+'.stdout.tap'),r.stdout||'');fs.writeFileSync(path.join(base,prefix+'.stderr.log'),r.stderr||'');check();
 const record={candidate:pre.candidate,argv,node:runtime,nodeSha256:pre.node.sha256,start,durationMs:performance.now()-t,status:r.status,signal:r.signal,error:r.error&&r.error.message,stdoutSha256:sha(r.stdout||''),stderrSha256:sha(r.stderr||''),sourceUnchanged:true,originalNativeInvoked:false,syntheticIdentityTransport:true,gitMetadataRoot:root,syntheticGitWorkTree:rooted?dest:null,syntheticGitDirectory:rooted?env.GIT_DIR:null,closure:'Copied exact full synthetic test inspected before execution. Only selected identity, raw-sentinel main, and successful main fixtures run; top-level reads helper/operator, creates invented child. verifyCommission uses author explicit fake Git/fs commission for identity checks, actual fixed production guards; capture transport asserts original argv then substitutes invented child. Real helper validation uses public map and parent ER Git metadata only. Rooted transport sets GIT_WORK_TREE to the invented copy and GIT_DIR to parent ER metadata, preserving original assertions and root-relative Git pathspec semantics without any Git write. No original child/body/native/frozen/seed/history load or fallback.',tail:(r.stdout||'').split(/\r?\n/).slice(-12)};
 fs.writeFileSync(path.join(base,prefix+'-result.json'),JSON.stringify(record,null,2)+'\n');console.log(JSON.stringify(record));if(r.error)throw r.error;process.exitCode=r.status===null?1:r.status;
}
