'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../../../..'),base=path.join(root,'.tmp/er-native-capture/author-reconciliation'),C='f9e45f922bcb489d8ef4a4eded83b968356f16e4',A='553a88d8f772b8fcb5f3a01307baf7f1a8718713',F='9de7bb79778224d581ddb9648ccbc5a44bd2ad13',prefix='rebuild/lanes/b/reviews/b1b2-native-capture-evidence/',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const git=(...a)=>cp.execFileSync('git',a,{cwd:root,windowsHide:true,maxBuffer:4e6});assert.equal(git('rev-parse','HEAD').toString().trim(),F);assert.equal(git('rev-parse',A+'^').toString().trim(),C);fs.mkdirSync(base,{recursive:true});
const report=git('show',C+':rebuild/lanes/b/BUILD-B1B2-NATIVE-CAPTURE.md');assert.equal(report.length,8071);assert.equal(sha(report),'7baed34a8b24c999ad22180f61000a164248c96dafc0da2ff341b0d683e0570d');assert.equal(report.toString().trimEnd().split('\n').length,33);
const index=git('show',A+':'+prefix+'INDEX.md'),mapBytes=git('show',A+':'+prefix+'MAPPING.json');assert.equal(sha(index),'816b04c4e6176efa07c8d8a917066ac1867f8bbd798542f88cacd1f3fc472df5');assert.equal(sha(mapBytes),'d00da676e02d1007da2c44a700731f1702979b1686a77727184d6cb627ecbacc');const map=JSON.parse(mapBytes);assert.equal(map.files.length,14);assert.equal(map.candidate,C);
assert.deepEqual(git('diff-tree','--no-commit-id','--name-only','-r',A).toString().trim().split('\n').sort(),[prefix+'INDEX.md',prefix+'MAPPING.json',...map.files.map(x=>x.archivePath)].sort());
const contents=new Map(),verified=[];for(const row of map.files){assert(row.archivePath.startsWith(prefix)&&!row.archivePath.includes('..'));const b=git('show',A+':'+row.archivePath);assert.equal(b.length,row.bytes);assert.equal(sha(b),row.sha256);const rel=row.archivePath.slice(prefix.length);contents.set(rel,b);const file=path.join(base,rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,b);verified.push({...row,verified:true});}assert.equal(verified.reduce((s,x)=>s+x.bytes,0),112232);
fs.writeFileSync(path.join(base,'author-report.md'),report);fs.writeFileSync(path.join(base,'INDEX.md'),index);fs.writeFileSync(path.join(base,'MAPPING.json'),mapBytes);
const replay=JSON.parse(contents.get('replay-evidence.json')),d1=JSON.parse(contents.get('d1-static.json'));fs.writeFileSync(path.join(base,'context-view.json'),JSON.stringify({replay,d1},null,2)+'\n');
const runs=[];for(const [name,expectedPass,expectedFail,inputs]of [['first',9,13,'inputs.json'],['second',17,5,'inputs-retrospective.json'],['third',28,0,'inputs.json']]){
 const tap=contents.get(name+'/stdout.tap').toString(),stderr=contents.get(name+'/stderr.log');assert.equal(stderr.length,0);const results=[...tap.matchAll(/^(not ok|ok) (\d+) - (.*)$/gm)].map(x=>({status:x[1],number:+x[2],name:x[3]}));assert.equal(results.filter(x=>x.status==='ok').length,expectedPass);assert.equal(results.filter(x=>x.status==='not ok').length,expectedFail);const census=Object.fromEntries([...tap.matchAll(/^# (tests|suites|pass|fail|cancelled|skipped|todo|duration_ms) (\d+(?:\.\d+)?)$/gm)].map(x=>[x[1],+x[2]]));assert.equal(census.pass,expectedPass);assert.equal(census.fail,expectedFail);
 const blocks=tap.split(/(?=# Subtest: )/).filter(x=>/^# Subtest: /m.test(x)&&/^not ok /m.test(x)).map(x=>{const lines=x.split('\n'),loc=lines.findIndex(s=>s==='  ...');return (loc>=0?lines.slice(0,loc+1):lines).filter(s=>!/^    (at |TestContext\.|async Test|Test\.run|Test\.process|Test\.post|node:|Module\.|helper \(|Object\.)/.test(s)).join('\n');});
 const input=JSON.parse(contents.get(name+'/'+inputs)),evidence=JSON.parse(contents.get(name+'/public-evidence.json')),authorRun=replay.runs.find(x=>x.name===name);assert.equal(input.source,authorRun.source);assert.deepEqual(input.argv,replay.command);assert.deepEqual(evidence.controls,authorRun.controls);assert.equal(evidence.helperSha256,input.files.find(x=>x.path.endsWith('b1b2-evidence.cjs')).sha256);assert.equal(evidence.operatorSha256,input.files.find(x=>x.path.endsWith('b1b2-native-capture.cjs')).sha256);assert.equal(evidence.nodeSha256,replay.node.sha256);for(const [k,v]of Object.entries(authorRun.actual))assert.equal(census[k],v);for(const f of authorRun.files){const row=map.files.find(x=>x.originalPath===f.path);assert(row);assert.equal(f.bytes,row.bytes);assert.equal(f.sha256,row.sha256);}if(name==='second')assert(input.manifestTiming.includes('Retrospective'));if(name==='third'){assert.equal(input.source,'8986d493058f1f6488781a105586c3177dd4f3fc');for(const f of replay.sourceFiles){const row=input.files.find(x=>x.path===f.path);assert.equal(row.sha256,f.sha256);assert.equal(sha(fs.readFileSync(path.join(root,f.path))),f.sha256);}}
 fs.writeFileSync(path.join(base,name+'-complete-json-view.txt'),JSON.stringify({input,evidence})+'\n');fs.writeFileSync(path.join(base,name+'-tap-view.json'),JSON.stringify({results,census,failureBlocks:blocks},null,2)+'\n');runs.push({name,census,results,controlRecords:evidence.controls,input,allRawBytesVerified:true,replayInputsOutcomesAndControlsCrossBound:true});
}
const custody={firstVerdict:F,authorAccessAfterFirstVerdictSent:true,candidate:C,archive:A,report:{bytes:report.length,sha256:sha(report),lines:33},index:{bytes:index.length,sha256:sha(index)},mapping:{bytes:mapBytes.length,sha256:sha(mapBytes)},archiveDirectChild:true,files:verified,totalCopiedBytes:112232,runs,originalNativeInvoked:false,historicalD1SourceRead:false,verdict:'REJECT unchanged: R1/R2 independent counterexamples are outside author coverage'};
fs.writeFileSync(path.join(__dirname,'AUTHOR-RECONCILIATION-CUSTODY.json'),JSON.stringify(custody,null,2)+'\n');console.log(JSON.stringify({archive:A,files:16,copiedBytes:112232,runs:runs.map(x=>({name:x.name,census:x.census,controls:x.controlRecords})),views:base}));
