'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../../../..'),base=path.join(root,'.tmp/er-native-capture'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),pre=JSON.parse(fs.readFileSync(path.join(base,'source-audit.json')));
const inputs=pre.manifest.inputs.filter(x=>x.role==='candidate');function verify(){for(const row of inputs)assert.equal(sha(fs.readFileSync(path.join(root,row.path))),row.sha256,row.path);for(const file of ['rebuild/engine/seed.cjs','rebuild/m4/workout/test/h3-supersede-second-gate.test.cjs','rebuild/lanes/b/BUILD-B1B2-NATIVE-CAPTURE.md','ledger/state.json','src/app.jsx'])assert(!fs.existsSync(path.join(root,file)),file+' remains excluded');}
verify();assert.equal(process.version,'v22.23.2');assert.equal(sha(fs.readFileSync(process.execPath)),pre.node.sha256);const env={...process.env,TZ:'America/New_York',TEMP:path.join(base,'temp'),TMP:path.join(base,'temp')};fs.mkdirSync(env.TEMP,{recursive:true});
for(const k of Object.keys(env))if(/^(NODE_OPTIONS|NODE_PATH|NODE_TEST_CONTEXT|NODE_TEST_WORKER_ID|NODE_V8_COVERAGE|V8_COVERAGE|V8_FLAGS|EARNED_B1B2_CAPTURE_COMMISSION|EARNED_B1B2_CAPTURE_DIR|MEASURED_TEST_NOW|PL_ENGINE|PL_LAWS_LIB)$/i.test(k))delete env[k];
const argv=['--test','--test-reporter=tap','rebuild/lanes/b/tooling/test/b1b2-native-capture.test.cjs'],start=new Date().toISOString(),time=performance.now();
const result=cp.spawnSync(process.execPath,argv,{cwd:root,env,windowsHide:true,maxBuffer:4*1024*1024,encoding:'utf8'});fs.writeFileSync(path.join(base,'exact.stdout.tap'),result.stdout||'');fs.writeFileSync(path.join(base,'exact.stderr.log'),result.stderr||'');
let restored;try{verify();restored=true;}catch(e){restored=e.message;}const record={candidate:pre.candidate,argv,node:process.execPath,nodeSha256:pre.node.sha256,root,start,durationMs:performance.now()-time,status:result.status,signal:result.signal,error:result.error&&result.error.message,stdoutSha256:sha(result.stdout||''),stderrSha256:sha(result.stderr||''),restored,tail:(result.stdout||'').split(/\r?\n/).slice(-12),closure:{modules:['committed synthetic test','actual operator','actual helper','public source-map JSON','Node builtins'],helperCalls:'Only approvedNativeDifference -> unchanged validateR9/Repair/Successor (public map plus Git commit/ancestry/name-status metadata) -> unchanged fieldDiff/assertion/return and contained observer. No reconstruction/native/original callback.',subprocess:'Owned Node invented children; Git metadata only; real Windows PowerShell ACL on invented own directories. Test transport checks literal original argv then executes only its generated synthetic child.',identityLimit:'Committed positive identity fixtures assume the builder root leaf b1b2-native-capture; this mandated reviewer root is er-b1b2-native-capture. Preserve any actual root refusal as fixture/setup evidence, not a behavioral kill.'}};
fs.writeFileSync(path.join(base,'exact-result.json'),JSON.stringify(record,null,2)+'\n');console.log(JSON.stringify(record));assert.equal(restored,true);if(result.error)throw result.error;process.exitCode=result.status===null?1:result.status;
