'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../../../..'),scratch=path.join(root,'.tmp/er-native-capture'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
assert(root.replaceAll('\\','/').endsWith('/work/pm-caretaker/er-b1b2-native-capture'));fs.mkdirSync(scratch,{recursive:true});
const git=(...a)=>cp.execFileSync('git',a,{cwd:root,windowsHide:true,maxBuffer:8e6}),C='f9e45f922bcb489d8ef4a4eded83b968356f16e4',T='8986d493058f1f6488781a105586c3177dd4f3fc',A='3bfed63febef002b8540d6ff3c56e19d08368711',G='5b81dc8fa0c8b31f46865b7588e190dcab7f9a15';
assert.equal(git('rev-parse','HEAD').toString().trim(),C);assert.equal(git('write-tree').toString().trim(),'d29ebfbe09df0402a618121073b7ada1f938082a');
const bars=[['rebuild/lanes/astra/B1B2-NATIVE-CAPTURE-REVIEW.md',G,'2f2ded00e400dc5b312c64b96408e4478feca6c4aef1cebdf61dab7f9fd1268d'],['rebuild/lanes/astra/B1B2-NATIVE-CAPTURE-REVIEW-INPUTS.json',G,'ef0c0879a21de55141bfa255abfb16e741fa0a55c5b53b2e766a91afc7c29b0b'],['rebuild/lanes/astra/B1B2-NATIVE-CAPTURE-GO.md',G,'3aca3d79eb6870088350fd801640ace0a4b6fd1c297c0fb05f2bdbb5322682ec'],['rebuild/lanes/b/B1B2-NATIVE-BOUNDARIES-PLAN.json','bcec684876d0f3d941cd4abc8983ebf8a5eb2dd0','7ed4ecead49357b7bf78e65904c2df50188b958d7481dd4aee35f168a1ba0644']].map(([file,ref,expected])=>{const b=git('show',ref+':'+file);assert.equal(sha(b),expected);fs.writeFileSync(path.join(scratch,path.basename(file)),b);return{file,ref,bytes:b.length,sha256:expected};});
const manifest=JSON.parse(fs.readFileSync(path.join(scratch,'B1B2-NATIVE-CAPTURE-REVIEW-INPUTS.json')));assert.equal(manifest.inputs.length,8);assert.equal(manifest.candidate,C);assert.equal(manifest.testedSource,T);assert.equal(manifest.base,A);
const paths=manifest.inputs.filter(x=>x.role==='candidate').map(x=>x.path);assert.equal(paths.length,6);assert(paths.every(p=>!p.includes('..')&&!path.isAbsolute(p)));const sparse=git('rev-parse','--git-path','info/sparse-checkout').toString().trim();fs.writeFileSync(sparse,['/NEXT.md','/AGENTS.md',...paths.map(p=>'/'+p)].join('\n')+'\n');git('read-tree','-mu','HEAD');git('checkout-index','--force','--',...paths);
for(const row of manifest.inputs){const b=git('show',row.ref+':'+row.path);assert.equal(b.length,row.bytes);assert.equal(sha(b),row.sha256);assert.equal(git('rev-parse',row.ref+':'+row.path).toString().trim(),row.gitBlob);if(row.role==='candidate'){assert(b.equals(fs.readFileSync(path.join(root,row.path))));assert(b.equals(git('show',T+':'+row.path)));}else fs.writeFileSync(path.join(scratch,'base-'+path.basename(row.path)),b);}
const expectedChanged=['rebuild/m4/workout/test/b1b2-evidence.cjs','rebuild/lanes/b/tooling/b1b2-native-capture.cjs','rebuild/lanes/b/tooling/test/b1b2-native-capture.test.cjs','rebuild/lanes/b/tooling/packages/B1-B2.json','rebuild/lanes/b/BUILD-B1B2-NATIVE-CAPTURE.md'].sort();assert.deepEqual(git('diff','--name-only',A,C).toString().trim().split('\n').sort(),expectedChanged);assert.equal(git('diff','--name-only',T,C).toString().trim(),expectedChanged.find(p=>p.includes('BUILD-')));
const profile=JSON.parse(fs.readFileSync(path.join(root,'rebuild/lanes/b/tooling/packages/B1-B2.json'))),old=JSON.parse(fs.readFileSync(path.join(scratch,'base-B1-B2.json'))),helper='rebuild/m4/workout/test/b1b2-evidence.cjs',post=profile.product[helper].post;assert.equal(post,sha(fs.readFileSync(path.join(root,helper))));const restored=structuredClone(profile);restored.product[helper].post=old.product[helper].post;assert.deepEqual(restored,old);assert.equal(Object.keys(profile.product).length,112);assert.equal(profile.children.length,26);assert.equal(profile.dIds.length,24);
const unchanged=['rebuild/engine','rebuild/m3','rebuild/m4/workout/test/b1b2-source-changes.json','rebuild/m4/workout/test/b1b2-supersede-second-gate.test.cjs'].map(p=>{const object=git('rev-parse',C+':'+p).toString().trim();assert.equal(object,git('rev-parse',A+':'+p).toString().trim());return{path:p,gitObject:object};});
for(const file of ['rebuild/engine/seed.cjs','rebuild/m4/workout/test/h3-supersede-second-gate.test.cjs','rebuild/lanes/b/BUILD-B1B2-NATIVE-CAPTURE.md','ledger/state.json','src/app.jsx'])assert(!fs.existsSync(path.join(root,file)),file+' excluded');
const nodeBytes=fs.readFileSync(process.execPath);assert.equal(process.version,'v22.23.2');assert.equal(nodeBytes.length,86997320);assert.equal(sha(nodeBytes),manifest.node.sha256);
const record={candidate:C,tested:T,base:A,authority:G,initialFullIndexTree:'d29ebfbe09df0402a618121073b7ada1f938082a',fullIndexPaths:1610,bars,manifest,changed:expectedChanged,profileOnlyHelperPost:true,unchanged,node:{path:process.execPath,version:process.version,bytes:nodeBytes.length,sha256:sha(nodeBytes)},originalProtectedPathsUnmaterialized:true,authorReportRead:false,authorOutcomesRead:false,setupCorrection:'read-tree -mu HEAD applied sparse flags but did not create the two named instruction files on this no-checkout index; explicit checkout-index of NEXT/AGENTS completed hydration. Full index remained exact, only those two absent paths were reported, no excluded materialization or staging.'};
fs.writeFileSync(path.join(scratch,'source-audit.json'),JSON.stringify(record,null,2)+'\n');console.log(JSON.stringify({candidate:C,paths:paths.length,inputs:8,changed:5,profileOnlyHelperPost:true,protectedAbsent:true,index:git('write-tree').toString().trim()}));
