'use strict';
// PM330 public synthetic entry only. No original H3/native program is invoked.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),Module=require('node:module');
const ROOT=path.resolve(__dirname,'../../../../..'),HELPER=path.join(ROOT,'rebuild/m4/workout/test/b1b2-evidence.cjs'),OP=path.join(ROOT,'rebuild/lanes/b/tooling/b1b2-native-capture.cjs');
const base=path.join(ROOT,'.tmp','native-capture-tests');fs.mkdirSync(base,{recursive:true});
const originalHelper=fs.readFileSync(HELPER),originalOperator=fs.readFileSync(OP),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const evidence={node:process.version,nodeSha256:hash(fs.readFileSync(process.execPath)),helperSha256:hash(originalHelper),operatorSha256:hash(originalOperator),cases:[],controls:[]};
function record(row){evidence.cases.push(row);fs.writeFileSync(path.join(base,'public-evidence.json'),JSON.stringify(evidence,null,2)+'\n');}
function directory(){const parent=path.join(ROOT,'.tmp','b1b2-native-capture');fs.mkdirSync(parent,{recursive:true});const p=path.join(parent,crypto.randomBytes(16).toString('hex'));fs.mkdirSync(p);fs.writeFileSync(path.join(p,'capture-manifest.json'),'{"v":1,"pending":true}\n');return p;}
function helper(dir,overrides={},source=fs.readFileSync(HELPER,'utf8')){
  const m=new Module(HELPER,module);m.filename=HELPER;m.paths=Module._nodeModulePaths(path.dirname(HELPER));
  const proc=Object.create(process),exits=[];proc.once=(event,fn)=>{assert.equal(event,'exit');exits.push(fn);return proc;};proc.env={...process.env};if(dir===null)delete proc.env.EARNED_B1B2_CAPTURE_DIR;else proc.env.EARNED_B1B2_CAPTURE_DIR=dir;
  const real=m.require.bind(m);m.require=n=>{assert(['node:assert/strict','node:fs','node:path','node:child_process','node:crypto','node:module','./b1b2-source-changes.json'].includes(n),'closed helper loader');return n==='node:fs'?{...fs,...overrides}:real(n);};
  m.__process=proc;m._compile('const process=module.__process;\n'+source,HELPER);return {...m.exports,finish:()=>{for(const fn of exits)fn();}};
}
function operator(overrides={},procOverrides={},source=fs.readFileSync(OP,'utf8')){
  const m=new Module(OP,module);m.filename=OP;m.paths=Module._nodeModulePaths(path.dirname(OP));const real=m.require.bind(m);
  m.require=n=>{assert(['node:fs','node:path','node:child_process','node:crypto','node:string_decoder'].includes(n),'closed operator loader');return own(overrides,n)?overrides[n]:real(n);};
  m.__process={...process,...procOverrides,env:{...process.env,...procOverrides.env},argv:procOverrides.argv||[process.execPath,OP],cwd:procOverrides.cwd||(()=>ROOT),stdout:procOverrides.stdout||process.stdout};
  m._compile('const process=module.__process;\n'+source,OP);return m.exports;
}
const own=(o,k)=>Object.hasOwn(o,k);
function pair(h){const a=Object.fromEntries(h.READERS.map(k=>[k,{value:1}]));return [a,structuredClone(a)];}
function commitRows(dir,rows){fs.writeFileSync(path.join(dir,'native-diagnostics.jsonl'),rows.map(x=>JSON.stringify(x)+'\n').join(''));fs.unlinkSync(path.join(dir,'capture-manifest.json'));}
const row=(seq,kind,count=0,categories=[])=>({v:1,seq,kind,categories,differenceCount:count,comparisonVerdict:count?'DIFFERENT':'MATCH'});
const GOOD=[row(1,'second-readers'),row(2,'second-applyRead')];
const FOOTER='TAP version 13\nok 1 - synthetic\nok 2 - synthetic\nok 3 - synthetic\nok 4 - synthetic\n1..4\n# tests 4\n# suites 0\n# pass 4\n# fail 0\n# cancelled 0\n# skipped 0\n# todo 0\n# duration_ms 1\n';
const fixture=path.join(base,'public-child.cjs');
fs.writeFileSync(fixture,String.raw`'use strict';const fs=require('node:fs'),path=require('node:path'),test=require('node:test');
const mode=process.env.SYNTHETIC_CAPTURE_MODE||'pass';
if(mode.startsWith('bulk-')){const stream=mode==='bulk-stdout'?process.stdout:process.stderr;const count=mode==='bulk-stdout'?268435457:67108865;const b=Buffer.alloc(65536,120);let n=0;function write(){while(n<count){const k=Math.min(b.length,count-n);n+=k;if(!stream.write(b.subarray(0,k)))return stream.once('drain',write);}process.stdout.write(process.env.SYNTHETIC_TAP);}write();}
else if(mode==='signal'){process.kill(process.pid,'SIGTERM');}
else if(mode==='manual'){process.stdout.write(process.env.SYNTHETIC_TAP);if(process.env.SYNTHETIC_STDERR)process.stderr.write(process.env.SYNTHETIC_STDERR);process.exitCode=+process.env.SYNTHETIC_EXIT||0;}
else {const H=require(process.env.SYNTHETIC_HELPER);for(let i=1;i<=3;i++)test('synthetic preserved '+i,()=>{});test('actual helper hook',()=>{const a=Object.fromEntries(H.READERS.map(k=>[k,{value:1}])),b=structuredClone(a);if(mode==='reader-fail')b.nowModel.value=2;H.approvedNativeDifference('second-readers',a,b);fs.writeFileSync(process.env.SYNTHETIC_WRITER_MARKER,'reached');const state={reads:[],trend:1},after=structuredClone(state);if(mode==='writer-fail')after.trend=2;H.approvedNativeDifference('second-applyRead',state,after);});}
`.replace(/\\`/g,'`'));
function transport(mode,opts={}){
  return {...cp,spawn(exe,args,options){assert.equal(exe,process.execPath);assert.deepEqual(args,['--test','--test-reporter=tap','rebuild/m4/workout/test/b1b2-supersede-second-gate.test.cjs']);assert.equal(options.cwd,ROOT);assert.deepEqual(options.stdio,['ignore','pipe','pipe']);record({transport:'actual operator spawn',mode,argv:args});
    const env={...options.env,SYNTHETIC_HELPER:HELPER,SYNTHETIC_WRITER_MARKER:path.join(options.env.EARNED_B1B2_CAPTURE_DIR,'synthetic-writer-marker'),SYNTHETIC_CAPTURE_MODE:mode,SYNTHETIC_TAP:opts.tap||FOOTER,SYNTHETIC_STDERR:opts.stderr||'',SYNTHETIC_EXIT:String(opts.exit||0)};
    // Strip only Node's enclosing synthetic-runner IPC marker; production environment remains untouched.
    delete env.NODE_TEST_CONTEXT;
    return cp.spawn(exe,mode==='manual'||mode==='signal'||mode.startsWith('bulk-')?[fixture]:['--test','--test-reporter=tap',fixture],{...options,env});}};
}
async function run(mode,opts={}){const dir=directory();if(opts.rows)commitRows(dir,opts.rows);const cpOverride=opts.cp||transport(mode,opts);const op=operator({'node:child_process':cpOverride,...(opts.fs?{'node:fs':{...fs,...opts.fs}}:{})});const result=await op.capture(dir);record({mode,dir:path.relative(ROOT,dir),result});return {dir,result};}
function noLeak(result,sentinels){const text=JSON.stringify(result);for(const x of sentinels)assert(!text.includes(x),'public sentinel leak');assert.deepEqual(Object.keys(result),['gateVerdict','captureVerdict','childExit','childSignal','tests','pass','fail','cancelled','skipped','todo','comparisons','fixedFailureCode']);}

test('public closure and owned Node22 are exact',()=>{assert.equal(process.version,'v22.23.2');assert.equal(evidence.nodeSha256,'0d0f5e39f9f3d9587bc19f73eab3c2c9c4903fd02d6dbf9c853dd81b3d95fad4');assert(!fs.existsSync(path.join(ROOT,'rebuild/engine/seed.cjs')));assert(!fs.existsSync(path.join(ROOT,'rebuild/conform/engines/engine-main.cjs')));record({closure:['this test','operator','helper','public source-map JSON','Node builtins','Git metadata validateR9 only','invented child','owned Node22','Windows ACL on invented directory'],native:false});});
test('actual hook passes with identical objects and unchanged return; disabled writes nothing',()=>{const dir=directory(),h=helper(dir),[a,b]=pair(h),pre=JSON.stringify(a);const r=h.approvedNativeDifference('second-readers',a,b);assert.equal(r.deltaCount,0);h.approvedNativeDifference('second-applyRead',{reads:[]},{reads:[]});h.finish();assert.equal(JSON.stringify(a),pre);assert(!fs.existsSync(path.join(dir,'capture-manifest.json')));assert.equal(operator().diagnostics(fs.readFileSync(path.join(dir,'native-diagnostics.jsonl'))).length,2);const disabled=helper(null);disabled.approvedNativeDifference('second-readers',a,b);assert.equal(JSON.stringify(a),pre);});
test('actual reader differences produce fixed categories but original assertion still fails',()=>{const dir=directory(),h=helper(dir),[a,b]=pair(h);b.nowModel={'SECRET-DYNAMIC-2034-01-01':'SECRET-VALUE'};const before=JSON.stringify(a);assert.throws(()=>h.approvedNativeDifference('second-readers',a,b),{code:'ERR_ASSERTION'});const rows=operator().diagnostics(fs.readFileSync(path.join(dir,'native-diagnostics.jsonl')));assert.equal(rows[0].comparisonVerdict,'DIFFERENT');assert(rows[0].categories.every(x=>x.id==='nowModel'));assert(!JSON.stringify(rows).includes('SECRET'));assert.equal(JSON.stringify(a),before);assert(fs.existsSync(path.join(dir,'capture-manifest.json')));});
test('actual state differences use fixed fields and disambiguate dotted dynamic keys',()=>{const dir=directory(),h=helper(dir),[a,b]=pair(h);h.approvedNativeDifference('second-readers',a,b);const state={reads:{},'reads.SECRET':1,'2034-01-01':1},after={reads:{},'reads.SECRET':2,'2034-01-01':2};assert.throws(()=>h.approvedNativeDifference('second-applyRead',state,after),{code:'ERR_ASSERTION'});const rows=operator().diagnostics(fs.readFileSync(path.join(dir,'native-diagnostics.jsonl')));assert.deepEqual(rows[1].categories,[{id:'state-other',count:2}]);assert(!JSON.stringify(rows).includes('SECRET'));});
test('observer write/fsync/close failures are sticky across later valid calls',()=>{for(const site of ['openSync','writeSync','fsyncSync','closeSync']){const dir=directory();let hit=false;const fault={};fault[site]=(...args)=>{if(!hit){hit=true;throw Error('SECRET IO FAILURE');}return fs[site](...args);};const h=helper(dir,fault),[a,b]=pair(h);assert.doesNotThrow(()=>h.approvedNativeDifference('second-readers',a,b));assert.doesNotThrow(()=>h.approvedNativeDifference('second-applyRead',{reads:[]},{reads:[]}));h.finish();assert(hit,site+' fault reached');assert(fs.existsSync(path.join(dir,'capture-manifest.json')),site+' completion marker retained');}});
test('partial writes retry; zero write, marker deletion failure and malformed paths never complete',()=>{const dir=directory();const h=helper(dir,{writeSync:(fd,b,off,len)=>fs.writeSync(fd,b,off,Math.min(3,len))}),[a,b]=pair(h);h.approvedNativeDifference('second-readers',a,b);h.approvedNativeDifference('second-applyRead',{trend:1},{trend:1});h.finish();assert(!fs.existsSync(path.join(dir,'capture-manifest.json')));for(const overrides of [{writeSync:()=>0},{unlinkSync:()=>{throw Error('SECRET');}}]){const d=directory(),x=helper(d,overrides),[c,e]=pair(x);x.approvedNativeDifference('second-readers',c,e);x.approvedNativeDifference('second-applyRead',{},{});x.finish();assert(fs.existsSync(path.join(d,'capture-manifest.json')));}});
test('actual row and key/path limits refuse without altering the original failure',()=>{for(const count of [4097,100001]){const dir=directory(),h=helper(dir),[a,b]=pair(h);if(count===4097){a.nowModel={['x'.repeat(count)]:1};b.nowModel={['x'.repeat(count)]:2};}else {a.nowModel=Array(count).fill(1);b.nowModel=Array(count).fill(2);}assert.throws(()=>h.approvedNativeDifference('second-readers',a,b),{code:'ERR_ASSERTION'});assert(fs.existsSync(path.join(dir,'capture-manifest.json')));assert(!fs.existsSync(path.join(dir,'native-diagnostics.jsonl')));}});
test('every admitted reader/state category comes from actual differing objects',()=>{
  const readers=['nowModel','statusFace','currentRate','calorieTarget','proteinTarget','marchingOrder','readRecency','fiveLevers','recoveryIndex','sleepInfo','observedTDEE','weekDigest','debtLedger','theOneThing','dossierData'];
  const states=['reads','trend','feed','queue','sleep','dailyLogs','sessionLog','model','learned','adjustments','suggestionLog','corrLog','exercises'];
  const dir=directory(),h=helper(dir),before=Object.fromEntries(readers.map(k=>[k,{x:1}])),after=Object.fromEntries(readers.map(k=>[k,{x:2}]));
  assert.throws(()=>h.approvedNativeDifference('second-readers',before,after),{code:'ERR_ASSERTION'});
  const a=Object.fromEntries(states.map(k=>[k,1])),b=Object.fromEntries(states.map(k=>[k,2]));assert.throws(()=>h.approvedNativeDifference('second-applyRead',a,b),{code:'ERR_ASSERTION'});h.finish();
  const rows=operator().diagnostics(fs.readFileSync(path.join(dir,'native-diagnostics.jsonl')));assert.deepEqual(rows[0].categories,readers.sort().map(id=>({id,count:1})));assert.deepEqual(rows[1].categories,states.sort().map(id=>({id,count:1})));assert.deepEqual([rows[0].differenceCount,rows[1].differenceCount],[15,13]);
  const d=directory(),x=helper(d),[c,e]=pair(x);x.approvedNativeDifference('second-readers',c,e);assert.throws(()=>x.approvedNativeDifference('second-applyRead',{},null),{code:'ERR_ASSERTION'});x.finish();assert.deepEqual(operator().diagnostics(fs.readFileSync(path.join(d,'native-diagnostics.jsonl')))[1].categories,[{id:'state-shape',count:1}]);record({actualCategoryCoverage:{readers:15,stateFields:13,stateShape:true,stateOther:'covered separately'}});
});
test('late observer failure cannot revive completion at natural exit',()=>{
  const dir=directory(),h=helper(dir),[a,b]=pair(h);h.approvedNativeDifference('second-readers',a,b);h.approvedNativeDifference('second-applyRead',{},{});assert(fs.existsSync(path.join(dir,'capture-manifest.json')));assert.doesNotThrow(()=>h.approvedNativeDifference('second-readers',a,b));h.finish();assert(fs.existsSync(path.join(dir,'capture-manifest.json')));assert.equal(operator().diagnostics(fs.readFileSync(path.join(dir,'native-diagnostics.jsonl'))).length,2);
});
test('categorizer, access and full-disk observer faults remain failures after later calls',()=>{
  for(const which of ['unknown-reader','directory','full-disk']){const dir=directory(),faults=which==='directory'?{lstatSync(){throw Object.assign(Error('SECRET access'),{code:'EACCES'});}}:which==='full-disk'?{writeSync(){throw Object.assign(Error('SECRET full disk'),{code:'ENOSPC'});}}:{},h=helper(dir,faults),[a,b]=pair(h);if(which==='unknown-reader'){a['SECRET.reader']=1;b['SECRET.reader']=2;assert.throws(()=>h.approvedNativeDifference('second-readers',a,b),{code:'ERR_ASSERTION'});}else assert.doesNotThrow(()=>h.approvedNativeDifference('second-readers',a,b));assert.doesNotThrow(()=>h.approvedNativeDifference('second-applyRead',{},{}));h.finish();assert(fs.existsSync(path.join(dir,'capture-manifest.json')));}
});
test('actual operator and helper pass a real four-test invented child',async()=>{const {dir,result}=await run('pass');assert.equal(result.gateVerdict,'PASS');assert.equal(result.captureVerdict,'PASS');assert.equal(result.pass,4);assert.equal(result.childExit,0);assert(fs.existsSync(path.join(dir,'synthetic-writer-marker')));noLeak(result,['SECRET']);});
test('first real helper failure preserves child outcome and prevents writer reach',async()=>{const {dir,result}=await run('reader-fail');assert.equal(result.gateVerdict,'FAIL');assert.equal(result.childExit,1);assert.equal(result.fail,1);assert.equal(result.comparisons[0].comparisonVerdict,'DIFFERENT');assert.equal(result.comparisons[1].comparisonVerdict,'NOT_OBSERVED');assert(!fs.existsSync(path.join(dir,'synthetic-writer-marker')));});
test('writer failure retains both observations and cannot become capture acceptance',async()=>{const {result}=await run('writer-fail');assert.equal(result.gateVerdict,'FAIL');assert.equal(result.comparisons[1].comparisonVerdict,'DIFFERENT');assert.equal(result.captureVerdict,'FAIL');});
test('enabled and disabled invented gate preserve census, original failure and inputs',()=>{for(const mode of ['pass','reader-fail','writer-fail']){const results=[];for(const enabled of [false,true]){const dir=directory(),env={...process.env,SYNTHETIC_CAPTURE_MODE:mode,SYNTHETIC_HELPER:HELPER,SYNTHETIC_WRITER_MARKER:path.join(dir,'mark')};if(enabled)env.EARNED_B1B2_CAPTURE_DIR=dir;else delete env.EARNED_B1B2_CAPTURE_DIR;delete env.NODE_TEST_CONTEXT;const r=cp.spawnSync(process.execPath,['--test','--test-reporter=tap',fixture],{cwd:ROOT,env,encoding:'utf8',windowsHide:true,maxBuffer:1e6});const t=operator().tapCensus();t.push(Buffer.from(r.stdout));results.push({exit:r.status,signal:r.signal,census:t.finish(),writer:fs.existsSync(path.join(dir,'mark'))});}assert.deepEqual(results[0],results[1]);record({equivalence:mode,...results[0]});}});
test('canonical diagnostic refusal matrix does not echo data',()=>{const op=operator();const cases=[Buffer.from(''),Buffer.from('SECRET'),Buffer.from([0xff,0x0a]),Buffer.from(JSON.stringify(GOOD[0])),Buffer.from(GOOD.map(x=>JSON.stringify(x)).reverse().join('\n')+'\n'),Buffer.from([...GOOD,GOOD[0]].map(x=>JSON.stringify(x)).join('\n')+'\n'),Buffer.from('{"v":1,"v":1}\n')];for(const edit of [x=>x.extra='SECRET',x=>x.kind='SECRET',x=>x.seq=3,x=>x.differenceCount=-1,x=>x.differenceCount=Number.MAX_SAFE_INTEGER+1,x=>x.categories=[{id:'SECRET',count:1}],x=>x.categories=[{id:'nowModel',count:0}],x=>x.differenceCount=1,x=>x.comparisonVerdict='SECRET']){const r=structuredClone(GOOD);edit(r[0]);cases.push(Buffer.from(r.map(x=>JSON.stringify(x)).join('\n')+'\n'));}for(const bytes of cases){assert.throws(()=>op.diagnostics(bytes));}record({diagnosticRefusals:cases.length});});
test('silence, valid later rows after incomplete marker and oversized diagnostics refuse',async()=>{for(const mode of ['missing','marker','overflow','partial']){const dir=directory();if(mode==='marker')fs.writeFileSync(path.join(dir,'native-diagnostics.jsonl'),GOOD.map(x=>JSON.stringify(x)+'\n').join(''));if(mode==='overflow')fs.writeFileSync(path.join(dir,'native-diagnostics.jsonl'),Buffer.alloc(65537,120));if(mode==='partial')commitRows(dir,[GOOD[0]]);const r=await operator({'node:child_process':transport('manual')}).capture(dir);assert.equal(r.gateVerdict,'PASS');assert.equal(r.captureVerdict,'FAIL');}});
test('child nonzero, spawn failure, raw IO failure, missing/duplicate/fake census refuse',async()=>{for(const opts of [{exit:2},{tap:FOOTER+'# pass 4\n'},{tap:FOOTER.replace('ok 4 - synthetic\n','')},{tap:'SECRET\n'},{tap:FOOTER.replace('# skipped 0','# skipped 1')},{fs:{openSync(){throw Error('SECRET raw IO');}}}]){const {result}=await run('manual',{rows:GOOD,...opts});assert.equal(result.captureVerdict,'FAIL');noLeak(result,['SECRET']);}const {result}=await run('manual',{cp:{...cp,spawn(){throw Error('SECRET spawn');}}});assert.equal(result.captureVerdict,'FAIL');assert.equal(result.tests,null);noLeak(result,['SECRET']);});
test('real stdout and stderr cap crossings drain to natural zero exit',async()=>{for(const mode of ['bulk-stdout','bulk-stderr']){const {dir,result}=await run(mode,{rows:GOOD});assert.equal(result.childExit,0);assert.equal(result.childSignal,null);assert.equal(result.captureVerdict,'FAIL');const name=mode.slice(5);assert.equal(fs.statSync(path.join(dir,name+'.raw')).size,operator().CAPS[name]);const meta=JSON.parse(fs.readFileSync(path.join(dir,'capture-manifest.json')));assert.equal(meta.overflow,true);assert(meta.bytes[name]>operator().CAPS[name]);}});
test('actual Windows access restriction and fresh-directory guard',()=>{const op=operator(),dir=op.createDirectory();assert(fs.existsSync(path.join(dir,'capture-manifest.json')));assert.throws(()=>operator({'node:child_process':{...cp,execFileSync(){return 'BAD_ACL';}}}).secureWindowsDirectory(dir));record({actualWindowsAcl:true,directory:path.relative(ROOT,dir)});});
test('directory link escape and stale files are refused by actual helper',()=>{const d=directory(),target=path.join(base,'junction-target-'+crypto.randomBytes(4).toString('hex'));fs.mkdirSync(target);const link=path.join(d,'native-diagnostics.jsonl');fs.writeFileSync(link,'STALE');const h=helper(d),[a,b]=pair(h);h.approvedNativeDifference('second-readers',a,b);assert.equal(fs.readFileSync(link,'utf8'),'STALE');assert(fs.existsSync(path.join(d,'capture-manifest.json')));const linked=path.join(ROOT,'.tmp','b1b2-native-capture',crypto.randomBytes(16).toString('hex'));fs.symlinkSync(target,linked,'junction');const x=helper(linked),[c,e]=pair(x);assert.doesNotThrow(()=>x.approvedNativeDifference('second-readers',c,e));assert.equal(fs.readdirSync(target).length,0);});
function commissioned(overrides={},processExtra={}){
  const child='rebuild/m4/workout/test/b1b2-supersede-second-gate.test.cjs',profile='rebuild/lanes/b/tooling/packages/B1-B2.json',map='rebuild/m4/workout/test/b1b2-source-changes.json';
  const files=new Map([[process.execPath,Buffer.from('synthetic-node')],[OP,originalOperator],[HELPER,originalHelper],[path.join(ROOT,profile),Buffer.from('synthetic-profile')],[path.join(ROOT,child),Buffer.from('synthetic-child')],[path.join(ROOT,map),Buffer.from('synthetic-map')]]);
  const c={v:1,source:'a'.repeat(40),nodeSha256:hash(files.get(process.execPath)),operatorSha256:hash(originalOperator),helperSha256:hash(originalHelper),profileSha256:hash(files.get(path.join(ROOT,profile))),childSha256:hash(files.get(path.join(ROOT,child)))};
  const fakeFs={...fs,lstatSync(p){if(files.has(p))return {isFile:()=>true,isSymbolicLink:()=>false,nlink:1};return fs.lstatSync(p);},readFileSync(p,...rest){return files.has(p)?files.get(p):fs.readFileSync(p,...rest);}};
  const fakeCp={...cp,execFileSync(cmd,args){assert.equal(cmd,'git');if(args[0]==='rev-parse')return Buffer.from(args[1]==='HEAD'?c.source+'\n':'b'.repeat(40)+'\n');if(args[0]==='merge-base'||args[0]==='diff')return Buffer.alloc(0);if(args[0]==='show')return files.get(path.join(ROOT,args[1].slice(args[1].indexOf(':')+1)));throw Error('unexpected synthetic git');}};
  const op=operator({'node:fs':fakeFs,'node:child_process':fakeCp,...overrides},{env:{EARNED_B1B2_CAPTURE_COMMISSION:JSON.stringify(c),EARNED_B1B2_CAPTURE_DIR:undefined,NODE_OPTIONS:undefined,NODE_PATH:undefined,NODE_TEST_CONTEXT:undefined},...processExtra});return {op,c,files,fakeFs,fakeCp};
}
test('production identity/argv/root checks cannot be weakened by fixture transport',()=>{const {op}=commissioned();assert.doesNotThrow(()=>op.verifyCommission());for(const args of [[process.execPath,OP,'extra']])assert.throws(()=>commissioned({}, {argv:args}).op.verifyCommission());const f=commissioned();f.files.set(HELPER,Buffer.from('ALTERED'));assert.throws(()=>f.op.verifyCommission());assert.throws(()=>commissioned({}, {cwd:()=>path.dirname(ROOT)}).op.verifyCommission());for(const field of ['source','nodeSha256','operatorSha256','helperSha256','profileSha256','childSha256']){const x=commissioned();const bad={...x.c,[field]:'0'.repeat(field==='source'?40:64)};assert.throws(()=>operator({'node:fs':x.fakeFs,'node:child_process':x.fakeCp},{env:{EARNED_B1B2_CAPTURE_COMMISSION:JSON.stringify(bad),EARNED_B1B2_CAPTURE_DIR:undefined,NODE_OPTIONS:undefined,NODE_PATH:undefined,NODE_TEST_CONTEXT:undefined}}).verifyCommission());}});
test('fresh path collisions, escaped roots and borrowed runtime are refused',()=>{
  const d=directory(),id=path.basename(d);assert.throws(()=>operator({'node:crypto':{...crypto,randomBytes:()=>Buffer.from(id,'hex')}}).createDirectory(),{code:'EEXIST'});assert.deepEqual(fs.readdirSync(d),['capture-manifest.json']);
  const bad=path.join(ROOT,'.tmp','native-capture-tests','outside');fs.mkdirSync(bad,{recursive:true});const h=helper(bad),[a,b]=pair(h);assert.doesNotThrow(()=>h.approvedNativeDifference('second-readers',a,b));h.finish();assert.equal(fs.readdirSync(bad).length,0);
  assert.throws(()=>commissioned({}, {execPath:path.join(path.dirname(ROOT),'borrowed','node.exe')}).op.verifyCommission());assert.throws(()=>commissioned({}, {env:{NODE_TEST_CONTEXT:'child-v8'}}).op.verifyCommission());
});
test('premature plans and forged complete census cannot pass',async()=>{for(const tap of [FOOTER.replace('TAP version 13\n','TAP version 13\n1..4\n').replace('ok 4 - synthetic\n1..4','ok 4 - synthetic'),FOOTER.replace('# suites 0','# suites 1'),FOOTER+'ok 5 - synthetic\n',FOOTER.replace('ok 4 - synthetic','ok 7 - synthetic')]){const {result}=await run('manual',{rows:GOOD,tap});assert.equal(result.captureVerdict,'FAIL');assert.equal(result.tests,null);}});
test('real signal and raw fsync/close failures never pass capture',async()=>{const signaled=await run('signal',{rows:GOOD});assert.equal(signaled.result.captureVerdict,'FAIL');assert(signaled.result.childSignal!==null||signaled.result.childExit!==0);for(const key of ['fsyncSync','closeSync']){let hit=false;const f={};f[key]=(...args)=>{if(!hit){hit=true;throw Error('SECRET FINAL IO');}return fs[key](...args);};const {result}=await run('manual',{rows:GOOD,fs:f});assert(hit);assert.equal(result.childExit,0);assert.equal(result.captureVerdict,'FAIL');noLeak(result,['SECRET']);}});
test('actual main emits only safe schema after real invented raw sentinel streams',async()=>{const x=commissioned();let printed='';const ipc={...x.fakeCp,spawn:transport('manual',{tap:FOOTER,stderr:'SECRET-RAW-2037-02-02'}).spawn,execFileSync(cmd,args,opts){return cmd==='git'?x.fakeCp.execFileSync(cmd,args,opts):cp.execFileSync(cmd,args,opts);}};const mod=operator({'node:fs':x.fakeFs,'node:child_process':ipc},{env:{EARNED_B1B2_CAPTURE_COMMISSION:JSON.stringify(x.c),EARNED_B1B2_CAPTURE_DIR:undefined,NODE_OPTIONS:undefined,NODE_PATH:undefined,NODE_TEST_CONTEXT:undefined},stdout:{write:s=>{printed+=s;}}});await mod.main();const result=JSON.parse(printed);assert.equal(result.captureVerdict,'FAIL');noLeak(result,['SECRET-RAW-2037-02-02']);assert.equal(printed,JSON.stringify(result)+'\n');});
test('actual main success emits exact fixed JSON after real four-test helper child',async()=>{const x=commissioned();let printed='';const ipc={...x.fakeCp,spawn:transport('pass').spawn,execFileSync(cmd,args,opts){return cmd==='git'?x.fakeCp.execFileSync(cmd,args,opts):cp.execFileSync(cmd,args,opts);}};const mod=operator({'node:fs':x.fakeFs,'node:child_process':ipc},{env:{EARNED_B1B2_CAPTURE_COMMISSION:JSON.stringify(x.c),EARNED_B1B2_CAPTURE_DIR:undefined,NODE_OPTIONS:undefined,NODE_PATH:undefined,NODE_TEST_CONTEXT:undefined},stdout:{write:s=>{printed+=s;}}});await mod.main();const result=JSON.parse(printed);assert.equal(result.captureVerdict,'PASS');assert.equal(result.gateVerdict,'PASS');assert.equal(result.childExit,0);noLeak(result,['SECRET']);assert.equal(printed,JSON.stringify(result)+'\n');record({actualMainPublicSuccess:result});});
test('meaningful source reversals fail intended assertions and restore bytes',async()=>{
  async function fault(file,before,after,check,id){const original=fs.readFileSync(file);const s=original.toString();assert.equal(s.split(before).length,2);fs.writeFileSync(file,s.replace(before,after));try{await assert.rejects(async()=>check(),e=>e&&e.code==='ERR_ASSERTION');evidence.controls.push({id,killedBy:'ERR_ASSERTION',sourceRestored:true});}finally{fs.writeFileSync(file,original);assert(fs.readFileSync(file).equals(original));}record({control:id,restoredSha256:hash(original)});}
  await fault(HELPER,'  observeNativeDifference(kind,actual,before,after);','  // observer removed',()=>{const d=directory(),h=helper(d),[a,b]=pair(h);h.approvedNativeDifference('second-readers',a,b);assert.equal(fs.existsSync(path.join(d,'native-diagnostics.jsonl')),true);},'hook-removal');
  await fault(OP,"need(!fs.existsSync(path.join(dir,'capture-manifest.json'))&&observed.length===2,'DIAGNOSTIC');","/* completion check removed */",async()=>{const d=directory();fs.writeFileSync(path.join(d,'native-diagnostics.jsonl'),GOOD.map(x=>JSON.stringify(x)+'\n').join(''));const r=await operator({'node:child_process':transport('manual')}).capture(d);assert.equal(r.captureVerdict,'FAIL');},'completion-refusal-removal');
  await fault(OP,"need(out==='ACL_OK','ACCESS');","/* ACL readback removed */",()=>assert.throws(()=>operator({'node:child_process':{...cp,execFileSync:()=> 'NO_ACCESS'}}).secureWindowsDirectory(directory())),'acl-readback-removal');
  await fault(HELPER,"id=matches[0];}","id=p;}",()=>{const d=directory(),h=helper(d),[a,b]=pair(h);b.nowModel={SECRET:1};assert.throws(()=>h.approvedNativeDifference('second-readers',a,b));assert(!fs.readFileSync(path.join(d,'native-diagnostics.jsonl'),'utf8').includes('SECRET'));},'output-whitelist-removal');
  await fault(HELPER,"  assert.equal(JSON.stringify(actual)===JSON.stringify(approved),true,'exact admitted native field deltas '+kind+'; measured '+actual.length+' (values retained process-locally)');","  /* original first-failure assertion removed for invented control only */",async()=>{const {dir,result}=await run('reader-fail');assert.equal(result.childExit,1);assert(!fs.existsSync(path.join(dir,'synthetic-writer-marker')));},'first-failure-guard-removal');
});
test('tracked runtime originals restored and evidence finished',()=>{assert(fs.readFileSync(HELPER).equals(originalHelper));assert(fs.readFileSync(OP).equals(originalOperator));record({allTrackedRuntimeBytesRestored:true});});
